obgm/libcoap

examples/coap-rd.c

According to the Core Resource directory draft [1]. The discovery of the registration should be done using the /.well-known/core and including a Resource Type (rt) with the value "core.rd". Like that:
GET /.well-known/core?rt=core.rd
There is a typo in the libcoap which accept the "core-rd" instead of the "core.rd" parameter. Fixing that in this version.
[1] - https://tools.ietf.org/html/draft-ietf-core-resource-directory-05#section-5.1

Fix typo in the attribute parameter to the right format "core.rd". (Update coap-rd.c)

---

src/net.c

In case of a malformed /.well-known/core discovery method for a unicast request, libcoap should return a "4.00 Bad Request", not "WARN discard malformed PDU"[1]
[1] https://tools.ietf.org/html/draft-ietf-core-resource-directory-05#section-5.1

Fixed: return 4.00 Bad Request in case of a malformed /.well-known/core (Update net.c)

---

.gitignore
.gitmodules

If we compile in this branch with
```
./autogen.sh
./configure --disable-shared
make
```
some files will be generated that we don't need to track.
- updated .gitignore file to ignore the *.o *.lo .deps/ .dirstamp .libs/ in the subfolders of src/ as well.
- updated .gitmodules to ignore the untracked changes in the 'tinydtls' submodules.

dtls branch - ignored some generated files

---

src/resource.c

The loop was always exiting after analysing the first observer,
so in case there were more and the first one on the list of
observers didn't match the one we wanted to remove, the
observer never got removed.
Signed-off-by: Pawel Winogrodzki <pawelwi@microsoft.com>

Fixing coap_remove_failed_observers() loop.

---

examples/client.c
include/coap/coap_io.h
include/coap/encode.h
include/coap/net.h
src/block.c
src/coap_io.c
src/coap_time.c
src/debug.c
src/encode.c
src/mem.c
src/net.c
src/option.c
src/pdu.c
src/resource.c
src/uri.c

Removing all of the /W4 level warnings from the code.
No functional changes.
A side effect of fixing the warnings is also making sure all
length/size casts don't end up with data loss.
Signed-off-by: Pawel Winogrodzki <pawelwi@microsoft.com>

Fixing /W4 warnings for Windows builds.

---

include/coap/net.h
src/net.c

While removing W4 warnings I've accidentally modified coap_transaction_id(), even though it was not necessary.

Reverting coap_transaction_id() to work the way it did.

---

src/coap_notls.c

Remove `return 0` in coap_dtls_handle_timeout in coap_notls.c

---

examples/coap-rd.c
examples/coap-server.c
include/coap/resource.h
include/coap/subscribe.h
include/coap/uri.h
libcoap-1.sym
src/net.c
src/resource.c
src/uri.c

Remember the query string used during the observe request and pass it to the resource handler.
Support partial notification of observers based on the query string.

Query string dependent observe.

---

include/coap/coap_io.h
include/coap/coap_session.h
include/coap/net.h
libcoap-1.sym
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c

Add a new handler callback to notify the application when libcoap bails out on sending a confirmable message.

Add handler for lost CON messages.

---

include/coap/debug.h
libcoap-1.sym
src/debug.c

In some applications having libcoap write to stdout is not what you want, a global log handler allows the application to push libcoap messages into its own logs instead.

Add a log handler callback.

---

examples/coap-server.c
src/coap_session.c

Remove the two unused parameter warnings I have when compiling.

Unused parameter warning

---

configure.ac
examples/Makefile.am
libcoap-1.pc.in
tests/Makefile.am

I encountered a few issues while building libcoap with DTLS support and I would like to push the fixes.
The first two concern building outside the source tree (for cleaner builds). 
The third one is to avoid exposing the SSL lib via pkg-config to libcoap users when not required as it can create problems in some scenarios.

Assorted build fixes

---

src/net.c

Not seting that relative time to zero will only (in the pop process) increase the next node relative time with this one. 
e.g. if node1->t = 1000 (1 sec), and node2->t = 1000 ( + 1 sec),
after 1 sec, we pop node1 and node2 become first with t = 2000 (as pop will do node2->t += node1->t. But in reality, 1 second already elapsed, so node2->t should be 1000 instead.

Set relative time 't' to zero when it actually expire

---

examples/coap-server.c
examples/contiki/server.c
include/coap/net.h
include/coap/resource.h
src/resource.c

Changes in resource.c, resource.h:
The value of the observe option is kept for each resource rather than being global to the context.
The value of the observe option must wrap to be stay below 2^24.
The value of the observe option must be different from the initial value when a notification is sent.
Note that the dirty flag must no longer be touched by the application, coap_resource_set_dirty() must be called instead as it takes care of incrementing the observe value. The examples have been updated accordingly

Fix issues #90, #91 and #92

---

include/coap/coap_dtls.h
libcoap-1.map
libcoap-1.sym
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

Add in support for determining TLS library type that libcoap was built against, as well as the TLS library version.

TlS: Determine TLS library support

---

include/coap/coap_dtls.h
include/coap/coap_session.h
include/coap/net.h
libcoap-1.map
libcoap-1.sym
src/coap_io.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c

For the TLS libraries that support it, there is a requirement for PKI support as well as PSK support.
PKI support is a little different from PSK support as the (D)TLS sessions setup is different, and optional callback flexibility needs to get added in.
In principle the set-up sequence for CoAP Servers looks like
----
coap_new_context()
coap_context_set_pki() and/or coap_context_set_psk() if encryption is required
coap_new_endpoint()
----
In principle the set-up sequence for CoAP Clients looks like
----
coap_new_context()
coap_new_client_session(), coap_new_client_session_pki() or coap_new_client_session_psk()
----

Addition of PKI support

---

src/coap_openssl.c

For a client, if a DTLS session is closed with ICMP unavailable packet, when
the TLS session is closed in the application with SSL_shutdown(), the OpenSSL
underlying library triggers a BIO_write() which calls coap_dgram_write() which
then 'assert's in coap_session_send().
(sock->flags == COAP_SOCKET_EMPTY && session->endpoint == NULL).
Fix is not to call coap_session_send() from coap_dgram_write() if socket is
closed and this is not an endpoint (not a server).

coap_openssl.c: client assert error if DTLS error closed socket

---

src/coap_io.c

If a TCP connection connection fails, or a an ICMP Unreachable is received
for a UDP packet, then the file descriptor is not closed off.  Eventually
all fails when no more file descriptors are allowed.

coap_io.c: Fix file descriptor leaks when "connections" fail

---

include/coap/net.h
src/net.c

This change provides the ability to define ping or pong handlers, so that an application can intercept the traffic and handle, for example, missing pings.

Ping Pong handlers: Need for applications to see ping requests / pong responses

---

examples/coap-server.c

fill_keystore() now needs to be before coap_new_endpoint() is called as per
In principle the set-up sequence for CoAP Servers looks like
coap_new_context()
coap_context_set_pki() and/or coap_context_set_psk() if encryption is required
coap_new_endpoint()

coap-server: Re-order code (move fill_keystore) to support PKI

---

include/coap/debug.h
src/coap_io.c

Append GNU '__attribute__ ((format(printf, 2, 3))' to the coap_log_impl() function definition.
This then catches an issue in coap_run_once() not being correctly formatted.

Add in GNU compiler checking of parameter syntax for coap_log() functions

---

src/coap_io.c

When determing whether to do a re-transmit timeout based on
coap_dtls_get_timeout, if s->tls is not set (unable to set up TLS session,
TLS error etc.), then coap_write() assert's when calling
coap_dtls_get_timeout().  This fix just sets the timeout to 0 if s->tls is not
set.

coap_write can assert if s->tls is not set when determining next to resend packet

---

include/coap/coap_session.h
include/coap/net.h
libcoap-1.map
libcoap-1.sym
src/coap_session.c
src/net.c

As per "RFC7252: 4.8.1.  Changing the Parameters", support is required for being able to modify the message transmission parameters.  This change proves the functions to be able to do this, along with the other code changes required to support the per session configuration.

Require support for configuring session recovery parameters

---

examples/coap-client.txt.in
include/coap/coap_session.h
src/coap_io.c
src/net.c

If COAP_SOCKET_CONNECTED is not set whilst establishing a TLS based
TCP sesson, coap_read_session() will assert while reading the underlying TLS
packets during PKI exchange.

coap_io.c: Set COAP_SOCKET_CONNECTED before connect() for TCP

---

src/resource.c

When freeing off a subscriber entry, free off the saved query at
the same time.  Already done once, needs to be done in the three
other instances.

resource.c: Fix memory leaks when deleting observers

---

include/coap/resource.h

The library API lacks a way to store context for the handlers. A
LED-handler for example needs to now on which pin the specific LED
is connected in order to control it. Or a higher level API would like to save the
object pointer to the object responsible for the resource.
This change will introduce a void pointer for the user to save context.
He can then retrive the context in the handler if needed.

resource.h: Introduce new field user_data

---

examples/client.c
include/coap/coap_session.h
src/coap_openssl.c

Make use of the MAX-RETRANSMIT parameter value (default 4) to limit the number of DTLS setup retries before raising COAP_NACK_TLS_FAILED as a session failure.

DTLS session setup retries to establish DTLS many times before failure

---

src/net.c

Because of incorrect free order, if there are open TLS connections when
coap_free_context() is called a use after free will occur as OpenSSL tries to
shutdown the connections.

net.c: use after free in coap_free_context()

---

src/net.c
src/resource.c

Making sure that "if" statements have opening brackets
on the same line to fit with the rest of the code.

net.c: correct brackets in if-statement

---

include/coap/resource.h

Possible values of the flags option of the coap_resource_init have been documented. This change also affects the documentation generated by doxygen

flags option in coap_resource_init documented

---

win32/coap-client/coap-client.vcxproj
win32/coap-rd/coap-rd.vcxproj
win32/coap-server/coap-server.vcxproj
win32/install/install.vcxproj
win32/install/install.vcxproj.filters
win32/libcoap.props
win32/libcoap.sln
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters
win32/testdriver/testdriver.vcxproj
win32/testdriver/testdriver.vcxproj.filters
win32/testdriver/testdriver.vcxproj.user

This pull requests does not touch the source code, only the visual studio project files with the goal of packaging the win32 build for general use.
It adds two missing files in testdriver and upgrades to Visual Studio 2017 with an up to date toolchain and SDK, which will make it easier for those building with the free edition of visual studio.
Windows does not have a configure, so I added a property sheet for the libcoap project with user variables to configure the target installation directory and location of openssl library from within the
Visual Studio GUI and in a manner compatible with msbuild. This method, using native visual studio features, is inspired by the windows build system of the GTK project. It supports out of tree builds, although the default is an in tree build to the …

Improve win32 build configuration and installation.

---

configure.ac
examples/Makefile.am
examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/coap_list.c
examples/coap_list.h
include/coap/coap.h.in
include/coap/debug.h
include/coap/mem.h
include/coap/option.h
include/coap/pdu.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap.txt.in
man/coap_attribute.txt.in
man/coap_context.txt.in
man/coap_handler.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_tls_library.txt.in
src/coap_notls.c
src/coap_tinydtls.c
src/option.c
src/pdu.c
win32/coap-client/coap-client.vcxproj
win32/coap-client/coap-client.vcxproj.filters

Anyone building a coap client will need to copy a lot of the code for handling CoAP Options from examples/client.c (see Issue #154 ).  This Pull Request moves the code into libcoap with the definitions of a new structure coap_optlist_t and a set of coap_optlist_* functions.  These new functions simplify the setting up of PDUs etc.  
coap_list_t was not moved into libcoap as it is likely that this structure has been copied into many clients.
The new functions are
coap_new_optlist()
coap_insert_optlist()
coap_add_optlist_pdu()
coap_delete_optlist()
At the same time, the example executables have been cleaned up to remove compiler warnings, the logging macros debug() and warn() has been replaced with coap_logging() as well as all the logging messages now have a trailing \n.
The local variable …

Move handling of CoAP Options into libcoap, instead of it all being held in coap-client

---

src/net.c

response pdu is created at the beginning of handle_request() and then re-created if there is not a handler for the request type for the resource , leading to a memory leak.

Fix CID 1382587 response resource leak

---

src/coap_session.c

Check that the same tid is not getting re-used in violation of RFC7252
in coap_session_delay_pdu().
To prevent duplication issues highlighted in Issue #163 as per below
`It looks like you are calling coap_send() for the same PDU 3 times - correct?
(sent at 17:09:57, 17:09:59 and 17:10:01)`

Verify tid is not being re-used in a session

---

include/coap/async.h
include/coap/option.h
src/async.c
src/option.c

To support C++, variable "uint8_t data[]" in coap_optlist_t has been changed to "unit8_t *data".
coap_new_optlist() has been updated to handle this.
coap_add_optlist_pdu() needs no change.

option.[ch]: Fix "warning: ISO C++ forbids flexible array member 'data'

---

src/coap_tinydtls.c

We need to fire an event on DTLS error, when we use tinydtsl, so we can handle this error on upper layers. 
On other implmetations of DTLS, like OpenSSL,this event is fired.
This is a fix of the PR #156

coap_tinydtls.c: On DTLS error, fire and event that could be catch by upper layers

---

include/coap/coap_session.h

This was the only match for a project-wide grep on 'coap_contex_t'.

fix typographical error in forward declaration

---

src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

#pragma GCC diagnostic push
#pragma GCC diagnostic pop
is not supported by gcc version less than 4.6
[I also think the push/pop is not needed as it is at the end of the
file and only one file is complied at one time]
gcc in general does not complain about (when the only entry in the file)
static inline void dummy(void) {
}
Also current code before fix is unlikely to work on Windows so the
additional compiler wrapper tests should fix this.

coap_{notls|openssl|tinydtls}.c: Support older gcc compilers

---

src/net.c

Make sure that stale response pdu is freed off in all cases in handle_request()

Cleaner fix for CID 1382587 that catches another case

---

examples/client.c
include/coap/option.h
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
src/option.c
tests/test_pdu.c

coap_add_optlist_pdu() sorted the options for insertion, but did not update
the coap_optlist_t head (whch may then no longer point to the first entry in the
sorted chain) and so when coap_delete_optlist() was called, the first few
entries of the sorted chain may not get deleted.
Fixed by making it
`coap_add_optlist_pdu(coap_pdu_t *pdu, coap_optlist_t** optlist_chain)`
instead of
`coap_add_optlist_pdu(coap_pdu_t *pdu, coap_optlist_t* optlist_chain)`
Addtionally named options_start() coap_options_start() and options_next()
coap_options_next() - Issue #184.
Fix coap_add_optlist_pdu() call
include/coap/options.h:
Rename to coap_options_start() and coap_options_next()
Fix coap_add_optlist_pdu() call
libcoap-2.{map|sym}:
Add in coap_options_start()
man/coap_observe.txt.in: …

options: Fix subtle memory leak in coap_add_optlist_pdu()

---

tests/oss-fuzz/pdu_parse_target.c

Moves fuzzer test to source tree. Partly addresses #211

oss-fuzz: Move test from oss-fuzz repo

---

examples/client.c
examples/coap-server.c
man/coap-client.txt.in
man/coap-server.txt.in

Add in support for configuring the coap-client and coap-server to use PKI by specifying a PEM file that contains both the CERTIFICATE and PRIVATEKEY.
coap-server can also have a different PSK defined.  If both PSK and PKI are required to accept connections of either type, then they both have to be defined.
At the same time, I have updated the respective Usage statements and man pages to reflect the new options as well as document all the other missing options.

Add in support for PKI for coap-client and coap-server

---

build-env/Dockerfile.build-env
scripts/build.sh
src/option.c
src/pdu.c
src/uri.c
tests/test_pdu.c
tests/test_uri.c

build-env/Dockerfile.build-env
scripts/build.sh
Add in valgrind testing of the tests
src/option.c
#199 Better fix of ADVANCE_OPT_CHECK()
src/pdu.c
#214 Validate token length in coap_pdu_parse_header()
src/uri.c
#212 Check not reading off end of buffer in dots()
tests/test_pdu.c
tests/test_uri.c
Tests updated to include tests for #212 & #214

Fix reported issues #212, #214 and refix #199, add in valgrind to do extra testing

---

include/coap/coap_dtls.h
include/coap/coap_session.h
include/coap/encode.h
include/coap/net.h
include/coap/str.h
include/coap/subscribe.h
src/resource.c

include/coap/coap_dtls.h
include/coap/coap_session.h
include/coap/encode.h
include/coap/net.h
include/coap/str.h
include/coap/subscribe.h
src/resource.c
Several functions have been better commented as well.

Remove doxygen warnings re text in header files by correcting parameter names

---

include/coap/coap_session.h
src/net.c
src/resource.c

https://tools.ietf.org/html/rfc7641#section-4.5
In order not to cause congestion, servers MUST strictly limit the number of
simultaneous outstanding notifications/responses that they transmit to a given
client to NSTART (1 by default; see Section 4.7 of RFC 7252 [RFC7252]).
An outstanding notification/response is either a confirmable message for which
an acknowledgement has not yet been received and whose last retransmission
attempt has not yet timed out or a non-confirmable message for which the
waiting time that results from the following rate-limiting rules has not yet
elapsed.
Delay sending of PDUs if active CON request waiting for ACK.
Do not start of another Observer unsolicited response if active CON waiting
waiting for ACK.
Display outgoing PDU if log level DEBUG or higher to help …

Limit outstanding CON requests to 1 per session for congestion control

---

examples/client.c
examples/contiki/coap-observer.c
include/coap/debug.h
include/coap/pdu.h
libcoap-2.map
libcoap-2.sym
src/debug.c
src/net.c
tests/test_pdu.c
tests/test_wellknown.c

Output COAP_OPTION_SIZE2 option as well
For binary data, output ascii readable equivalent immediately under the
hex output for ease of debugging.
This then allows the coap_set_log_handler() log handler to be used.
Currently in the code, there are several code fragments of the form
```` 
if (LOG_DEBUG <= coap_get_log_level()) {
coap_show_pdu(pdu);
}
````
Should coap_show_pdu() become `coap_show_pdu(coap_log_t level, coap_pdu_t *pdu)` to simplify the code ?

debug.c: Make coap_show_pdu() use fprintf() or coap_log() for output

---

Makefile.am
configure.ac
examples/client.c
examples/coap-server.c
include/coap/coap_dtls.h
include/coap/coap_session.h
include/coap/debug.h
include/coap/net.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap-client.txt.in
man/coap-server.txt.in
man/coap.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_session.txt.in
src/coap_io.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c

A late change to the PKI Pull request got missed for the TLS case
in coap_dtls_context_set_pki() for the mapping of private key types to
the OpenSSL version.  Have pulled common DTLS and TLS code into a separate
function
Fixed coap_(d)tls_free_session to not shut down a session that is not yet
fully started, as well as calling SSL_shutdown() twice if appropriate.
The ssl parameter is set to NULL after shutdown to prevent re-use
Made coap_dtls_context_set_psk() smarter in what whas updated, depending on
whether a client or server
Make sure that coap_dtls_psk_client_callback is defined in
coap_dtls_context_set_psk() in case coap_dtls_context_set_pki() was called
first.  This fixes the first time issue after startup where a PSK client
was unable to establish a DTLS session - subsequent times …

coap_openssl tidy up, fix first PSK fails if both PSK and PKI are enabled on server

---

examples/coap-server.c
man/coap-server.txt.in
man/coap_resource.txt.in

Add in -d option, which then causes coap_resource_unknown_init() to get
called to support creation of dynamic resources for unknown resources.

coap-server: Support for being able to create dynamic resources on the fly

---

src/debug.c

If a loss level is configured using coap_debug_set_packet_loss(), it
is not possible to restore full flow using 0% - as 0 is rejected as
being invalid.  This fix allows 0% to restore full traffic flows again.

src/debug.c: Allow loss level of 0% to restore full flow

---

src/net.c

The RST to a CoAP Ping was not decrementing the con_active count, so
all new CON requests were waiting for the Ping to expire.

Missing case for #201 to close down con_active

---

examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/contiki/server.c
examples/etsi_iot_01.c
include/coap/resource.h
include/coap/str.h
include/coap/subscribe.h
man/coap_observe.txt.in
src/net.c
src/resource.c
src/str.c
src/uri.c
tests/test_options.c

New struct coap_binary_t - same as coap_string_t, used for tokens
Deprecate struct str with the intent of removing it downstream as it
polutes namespace.
Make byte after end of allocated coap_string_t data a NUL for string terminators - an extra byte is allocated for this.
coap_string_t still contains uint_8_t* - it makes sense to do this as a seperate PR depending on the outcome of the discussion in thread https://sourceforge.net/p/libcoap/mailman/message/36335932/
Files:
examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/contiki/server.c
examples/etsi_iot_01.c
include/coap/resource.h
include/coap/str.h
include/coap/subscribe.h
man/coap_observe.txt.in
src/net.c
src/resource.c
src/str.c
src/uri.c
tests/test_options.c

Replace str with coap_string_t.  Make tokens coap_binary_t

---

src/coap_io.c
src/net.c

The node queue uses time deltas between each entry in the queue for
retransmissions.  The head entry does not have a time delta.
When the head of the head of the queue is taken off for retransmission
the next in the queue needs to have the time delta updated to be an
absolute value.  However, this does not happen if the current head has had
the time offset force set to 0 and so the retransmit timer fires more frequently
than expected.
There are 2 ways to fix this - not maintain time deltas between queue
entries, or not force set the head entries time to 0.
Doing the latter means that code that relies on the deltas (I can only
find the test suite) continue to work before calling coap_retransmit().
See Issue #197 for further information.

coap_io.c,net.c: Fix head of node queue re-transmit timeouts

---

include/coap/coap_session.h
src/coap_io.c
src/coap_session.c
src/net.c

This better describes what is going on here (as they are created by
coap_session_delay_pdu()) and are only released off this queue when
either the session becomes established, or the outstanding CON requests
falls below COAP_DEFAULT_NSTART (a value of 1).
This is to remove confusion with the use of coap_context_t sendqueue
which is used for retransmitting data after no response detected for a
CON request.
include/coap/coap_session.h
src/coap_io.c
src/coap_session.c
src/net.c
As discussed in #230 comment.

Rename coap_session_t sendqueue variable to delayqueue

---

include/coap/coap_event.h
include/coap/coap_session.h
include/coap/net.h
libcoap-2.map
libcoap-2.sym
man/coap_handler.txt.in
src/coap_event.c
src/coap_openssl.c
src/coap_session.c
src/net.c

dtls_event is a static variable, declared outside of all the functions which
tracks (D)TLS errors for generating events etc.
If there are multiple SSL sessions being set up to the same server (as per 
Happy Eyeballs for the DOTS protocol) it is possible to asynchronously get 
dtls_event updated and the wrong SSL session then acts on it. 
Make dtls_event a part of coap_session_t to maintain separation.
Preset dtls_event to -1 in coap_make_session().
Update coap_event_handler() to have the 3rd parameter as
coap_session_t *session instead of void *arg as the parameter is always session.
Updated coap_event_handler_t to have session as the 3rd parameter.
Add in new registration handler coap_register_event_handler() to be consistent
with all the other coap_register_XXX_handler()s.
Consequently, …

openssl.c: Global dtls_event variable causing confusion when events happen

---

.gitignore
Makefile.am
autogen.sh
doc/Doxyfile.in
doc/Makefile.am
doc/build_man_files.sh
doc/main.md
include/coap/debug.h
include/coap/encode.h
include/coap/option.h
include/coap/pdu.h
include/coap/prng.h
man/Makefile.am
man/coap.txt.in
man/coap_attribute.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_handler.txt.in
man/coap_logging.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/coap_tls_library.txt.in

Added in a new landing page for Main Page
doc/DOC.md (new)
Enabled Tree View of whats available
Disable Related Pages TAB as it fills up with the man pages
- updated doc/Doxyfile.in
Get a2x to also generate html man pages which are then included.  These
html files are updated to correct the lowercasing of NAME and SYNOPSIS.
The SEE ALSO references to other man pages are made hyper links.
- done by doc/build_man_files.sh (new)
Created a new TAB Manual Pages
Created a new TAB Depricated Items
- done by modifing DoxygenLayout.xml file using doc/build_man_files.sh
Updated .gitignore to ignore additional files and autogen.sh to clean them up
man/coap*txt.in updated to display as expected in Doxygen.
This only updates documentation
.gitignore
Makefile.am
autogen.sh
doc/DOC.md
doc/Doxyfile.in …

Include man pages into Doxygen.  Add landing page for Doxygen

---

src/coap_session.c
src/net.c

This allows a Coap Ping sent after a CON request to then go through the
cycle of retries and then timeout after the original CON fails.

net.c: Flush out delayqueue if a CON times out

---

examples/client.c
examples/coap-server.c
include/coap/coap_dtls.h
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_session.txt.in
src/coap_openssl.c

OpenSSL 1.1.0 has support for making decisions during receipt of
the Client Hello - the call back function is set up using
SSL_CTX_set_tlsext_servername_callback() which is called later in the
Client Hello processing - but called every Client Hello.
Certificates and Preshared Keys have to be set up in the SSL CTX before
SSL_Accept() is called, making the code messy to decide whether this is a
PKI or PSK incoming request to handle things accordingly if both are
defined.  SNI has to create a new SSL CTX to handle different server names
with different crtificates.
OpenSSL 1.1.1 introduces a new function SSL_CTX_set_client_hello_cb().
The call back is invoked early on in the Client Hello processing giving
the ability to easily use different Preshared Keys, Certificates etc.
Certificates do …

Add in support for OpenSSL 1.1.1 to support TLS1.3 (RFC8446)

---

src/coap_session.c

COAP_EVENT_SESSION_CONNECTED is only for CSM exchange events for reliable
protocols only as per include/coap/coap_event.h
In handling_signaling(), if session->state == COAP_SESSION_STATE_CSM, then
COAP_EVENT_SESSION_CONNECTED needs to be generated. This is done by calling
coap_session_connected().
coap_session_connected() is called from other places, used to flush out
any pending queues after connection has taken place.  It is also called
when CON limiting needs to release any panding queues.
Make coap_session_connected() only call coap_handle_event() if current
session->state == COAP_SESSION_STATE_CSM to limit the event generation.

coap_session.c: Only generate event COAP_EVENT_SESSION_CONNECTED as appropriate

---

.gitignore
autogen.sh

Fixes to 4.2.0-rc1 to allow lwIP and Contiki builds

lwIP and Contiki coap2 fixes to allow builds

---

src/resource.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

The Visual C++ project must be adapted for the changed in release 4.2.
For portability on windows, C99 VLA syntax cannot be used.
A read after free condition causes the server to crash when an observation is canceled.

Windows build is broken and libcoap crash on observer release.

---

include/coap2/resource.h
man/coap_resource.txt.in
src/net.c

include/coap2/resource.h
man/coap_resource.txt.in
modified:   src/net.c (comment only)

Clarify coap_resource_unknown_init() usage documentation

---

examples/client.c
examples/contiki/coap-observer.c
examples/etsi_iot_01.c
include/coap2/debug.h
src/async.c
src/block.c
src/coap_io.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/debug.c
src/mem.c
src/net.c
src/option.c
src/pdu.c
src/resource.c
src/uri.c

This then removes the need for name polution/confict of debug(), info() and
warn() when building other projects that use libcoap and need to #include the
libcoap header files
Updated:
examples/client.c
examples/contiki/coap-observer.c
examples/etsi_iot_01.c
include/coap2/debug.h
src/async.c
src/block.c
src/coap_io.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/debug.c
src/mem.c
src/net.c
src/option.c
src/pdu.c
src/resource.c
src/uri.c
If the debug() etc. macros are still required, then the change to
include/coap2/debug.h just needs to be reverted.
There are also a couple of space changes - to cause log output to be columnar
e.g "ERR" was padded to "ERR ", so that "EMRG" or "ERR " log output output was
aligned in the same way.
This is a replacement for PR#51, and partially …

Replace debug(), info() & warn() macros with appropriate coap_log()

---

src/net.c

Compilation using define 'WITH_CONTIKI' complains on missing semicolon.

Add missing semicolon.

---

examples/client.c
examples/coap-server.c

examples/client.c
examples/coap-server.c
For the client, the next block to transmit is always now the last acknowledged (by 2.31 response)
block plus one (unless of course if there is a block size change which adjusts the block numbers).
If the client receives a duplicate BLOCK1  2.31 (or 2.01 or 2.04) acknowledge response, the duplicate 2.31 acknowledge response is ignored by checking the message ids.  The duplication may happen if  the server server is slow to respond to a CON request, and the client re-transmits the CON request after a timeout.
For the server, it no longer rejects a duplicate BLOCK1 request, but does
still object if there is a gap in the provided data due to a missing block.
In other words, the blocks must arrive sequentially from the client.

Fix packet recovery support for BLOCK1 option in examples for lossy connections

---

examples/client.c

Thus it must not be postfixed with a colon character in the optstring.
While at it move the option to the beginning of the opstring to the
other options which don't expect an argument.
Without this commit the -U option is unusable.

coap-client: The -U option doesn't expect an argument

---

.gitignore
examples/Makefile.am
examples/etsi_coaptest.sh
examples/etsi_iot_01.c
examples/etsi_testcases.sh
examples/tiny.c
scripts/build.sh

These are now included in the standard build (by running 'make check')
to catch any other API changes.  Named as coap-etsi_iot_01 and coap-tiny.
They are not installed.
etsi test case scripts have been corrected to get things working.
However, there does not appear to be all the functionality required to
cover all the test cases.  E.g. /large-create was not defined as a
resource.
.gitignore:
Ignore new binaries
examples/Makefile.am:
Build coap-etsi_iot_01 and coap-tiny (when 'make check' is run).
scripts/build.sh:
Include 'make check' for checking coap-etsi_iot_01 and coap-tiny.
examples/etsi_coaptest.sh:
examples/etsi_testcases.sh:
Minor fix changes
examples/tiny.c:
Updated to use new API
Fixes request raised in #274

Update etsi_iot_01 and tiny examples to build with current API

---

BUILDING
src/coap_io.c
tests/test_session.c

src/coap_io.c:
ifdef out IPv4 struct in_pktinfo code that does not compile, copying what
has been done later in the same coap_network_send() function.
tests/test_session.c
Correctly reverse the parameters to coap_new_client_session() in t_session6()
so that the test application does not bind to local-address, port 5683 twice.
[It seems that other distrubutions are happy with this when just SO_REUSEADDR
is used on the socket, but FreeBSD needs SO_REUSEPORT enabled as well.]
BUILDING
Record that gmake is required to build TinyDTLS for FreeBSD, not make.
Most of #89 is already in the develop branch - this PR just completes the ability to build and test.
Issue #87 is covered as well

Support FreeBSD 11.2 builds

---

Makefile.am
include/coap2/coap_session.h
libcoap-2.map
libcoap-2.sym
src/coap_io.c
src/coap_session.c

Information set up in the pseudo session held in endpoint->hello is not freed
off when coap_free_endpoint() is called.
A solution is to split coap_session_free() into two parts with
coap_session_free() calling a new function coap_session_mfree().
Then coap_mfree_endpoint() can call coap_session_mfree() to free off the
endpoint specific hello information.
Makefile.am
Add coap_mfree_endpoint and coap_session_mfree to the CTAGS_IGNORE list.
libcoap-2.{map|sym}
Remove coap_mfree_endpoint as it is not a public function
include/coap2/coap_session.h
Add in new coap_session_mfree() function definition
src/coap_io.c
Call coap_session_mfree() from within coap_mfree_endpoint()
src/coap_session.c
Move some of the functionality out of coap_session_free() into a new
function coap_session_mfree() and …

endpoint->hello information memory leak when coap_free_endpoint() called

---

include/coap2/coap_hashkey.h
include/coap2/str.h

As str structure has been replaced by coap_string_t, remove it from the code
as it is no longer required, has been deprecated for some time and can cause
clashes with other str definitions.
Tidy up comment referring to str.

Remove deprecated str typedef to remove namespace pollution

---

include/coap2/block.h
man/coap_pdu_setup.txt.in

include/coap2/block.h
man/coap_pdu_setup.txt.in
Update documentation on coap_add_data_blocked_response() usage.
Raised in response to query #287

Clarify coap_add_data_blocked_response() usage

---

examples/coap_list.h
include/coap2/address.h
include/coap2/async.h
include/coap2/bits.h
include/coap2/block.h
include/coap2/coap.h.in
include/coap2/coap.h.windows
include/coap2/coap_debug.h
include/coap2/coap_dtls.h
include/coap2/coap_event.h
include/coap2/coap_hashkey.h
include/coap2/coap_io.h
include/coap2/coap_session.h
include/coap2/coap_time.h
include/coap2/encode.h
include/coap2/libcoap.h
include/coap2/mem.h
include/coap2/net.h
include/coap2/option.h
include/coap2/pdu.h
include/coap2/prng.h
include/coap2/resource.h
include/coap2/str.h
include/coap2/subscribe.h
include/coap2/uri.h
src/coap_session.c

include/coap2/libcoap.h
`_LIBCOAP_H_ to _COAP_LIBCOAP_H_`
src/coap_session.c
`_COAP_SESSION_H_ to _COAP_SESSION_C_`
include/coap2/coap_session.h
`_SESSION_H_ to _COAP_SESSION_H_`
Fixes #291

Reserved Identifier fixes

---

examples/coap-server.c
man/coap-server.txt.in

Add in -n option to support making require_peer_cert configurable, by default
it is enabled unless -n is set.
Code changes.
man/coap-server.txt.in
Update documentation

coap-server: Make requirement for clients to have certificates configurable

---

examples/client.c
include/coap2/coap_dtls.h
src/coap_gnutls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

By defining the CA file or Root CAs in the client, the server's certificate
can be validated by the options in coap_dtls_pki_t parameter even if the client
does not define a certificate.
[The server must be configured not to require a Client Cert]
Add in the support to the coap-client to allow any of Root CA, CA and Cert
to be defined to set up PKI checking.
Remove the checks in the OpenSSL and GnuTLS underlying support that previously
used to enforce that both CA and Cert had to be set in the client.
Correct some of the PKI setup error messages to reflect whether the failure is
on the client or the server.
src/coap_notls.c:
Convert …

coap-client: Support using CA or Root CAs, but not Cert files

---

src/coap_gnutls.c

To reproduce:-
Run a GnuTLS-based coap-server with option `-n` and connect with
`openssl s_client` to port 5684. The handshake works and see binary data
(the CoAP/TCP CSM signaling). Now, then interrupt the openssl s_client process
with SIGINT, This generates a lot of these messages:
Feb 14 19:22:39 DEBG ASSERT: ../../lib/record.c[_gnutls_recv_int]:1766
Feb 14 19:22:39 DEBG ASSERT: ../../lib/buffers.c[_gnutls_io_read_buffered]:589
Feb 14 19:22:39 DEBG ASSERT: ../../lib/record.c[_gnutls_recv_int]:1766
Feb 14 19:22:39 DEBG ASSERT: ../../lib/buffers.c[_gnutls_io_read_buffered]:589
Feb 14 19:22:39 DEBG ASSERT: ../../lib/record.c[_gnutls_recv_int]:1766
Feb 14 19:22:39 DEBG ASSERT: ../../lib/buffers.c[_gnutls_io_read_buffered]:589
Feb 14 19:22:39 DEBG ASSERT: …

coap-server: GnuTLS does not correctly detect closure by a client using TCP

---

examples/client.c

If there is an issue during DTLS setup, the coap-client will keep on retrying
and then getting the same failure.
This fix introduces using coap events into coap-client, and on detection of
a close event, the coap-client closes down

coap-client: Clean exit on detection of DTLS closure

---

include/coap2/coap_dtls.h
src/coap_gnutls.c

To reproduce the issue:
Server session
$ coap-server -v9 -n -k secretPSK -c server.pem -C ca.pem -R /etc/ssl/certs
Client session
$ examples/coap-client -v9  coaps://127.0.0.1/
If neither coap_new_client_session_pki() or coap_new_client_session_psk()
is called, but coap_new_client_session() is (as done by coap-client if
no PKI or PSK options set), then set up a default PKI session to be
able to talk to a coap server.

Support coap-client with no PKI or PSK defined, but using (D)TLS in GnuTLS

---

src/coap_gnutls.c

GnuTLS 3.6.0 or later requires that gnutls_certificate_set_x509_system_trust()
is set up if PSK is not being used and PKI is not defined and the session
is to be DTLS based.
Add in call to gnutls_certificate_set_x509_system_trust() in
setup_pki_credentials() if PKI has not been set up.
See discussion on #300

Support for clients with no PKI or PSK defined for GnuTLS > 3.6 and coaps

---

Makefile.am
man/Makefile.am
man/coap_context.txt.in

Makefile.am:
Correct the name of the libcoap-*.pc in distclean-local: of Makefile.am
Determine additional man pages created by a2x with A2X_EXTRA_PAGES.
Set EXTRA_PAGES for the hand crafted additional man pages.
Clean out the additional installed coap_*.3 man pages using uninstall-man:
in man/Makefile.am
man/coap_context.txt.in:
Remove spurious reference to coap_endpoint_str
Addresses issue raised in #305

Fix 'make distcheck' by removing the manpage additional generated .3 files

---

BUILDING
configure.ac
scripts/build.sh

When building tinydtls version, Travis fails with the following error
tests/testdriver: error while loading shared libraries: libtinydtls.so:
cannot open shared object file: No such file or directory
The new version of TinyDTLS now builds a libtinydtls.so file which is
linked against in preference to libtinydtls.a when using -ltinydtls,
but Travis does not have an installed version libtinydtls.so to load
during execution of tests/testbriver - hence failure.
scripts/build.sh:
Add in LD_LIBRARY_PATH=ext/tinydtls if building tinydtls.
BUILDING:
configure.ac:
With libtinydtls.so being available, there is no need to enforce
--disable-shared for tinydtls.  Remove this requirement.
If --disable-shared is set, link in with libtinydtls.a.
Fixes issue reported in #318

Travis tests/testdriver fails with libtinydtls.so missing error

---

src/coap_debug.c

When compiling libcoap with format truncation warnings enabled,
GCC warns about the potential issue with "%u.%02u" format string,
since the first argument may produce more than one byte of output:
error: '%02u' directive output may be truncated writing 2 bytes
into a region of size between 0 and 3 [-Werror=format-truncation=]
The first argument (class) is limited to 3 bits according to the
specification. Mask the higher bits to fix the warning.

coap_debug.c: fix format warning when compiling with GCC 8

---

src/coap_gnutls.c

Correct typo when null terminating username.

Client crashes in gnutls psk setup

---

src/coap_session.c

In coap_session_free(), as coap_session_mfree() is called after
the session has been deleted out the endpoint or context sessions,
dtls_send_to_peer() is unable to find the session to send out the
Alert/Warning Close Notify message packet.
Move coap_session_mfree() to before setting deleting session out of endpoint or context sessions in coap_session_free().
Note: TinyDTLS has been separately updated to not report ALRT on a
Close Notify - see https://github.com/eclipse/tinydtls/pull/5.

dtls_send_to_peer: cannot find local interface reported on coap_session_free

---

examples/contiki/README
examples/lwip/README
src/coap_session.c

As a server, idle sessions are left around in case the client wants to do
further work using the same 5 tuple IP information.
With constrained systems, the number of sessions is limited, and so it is
easy to run out of sessions.
If there is an idle session, context->max_idle_sessions is not set and
a new session cannot be created, free off the oldest session and retry
the creation again.
examples/contiki/README:
examples/lwip/README:
Tidy up the documentation

server (lwip & contiki) run out of sessions

---

src/coap_gnutls.c

While #321 prevented a core dump, that fix still caused memory corruption.
Correct the code to correctly NULL terminate the created username.

Fix #321 was not correctly implemented

---

src/coap_session.c

Following on from #324 where coap_session_mfree() had to be moved in
coap_session_free() to correctly allow for tinydtls cleanup, session->endpoint
and session->context should not be cleared out prior to call of
coap_sesson_free() in coap_free_endpoint().
Remove lines setting session->endpoint and session->context to NULL

coap_free_endpoint does not clean up tinydtls encryption sessions

---

examples/coap-rd.c
examples/coap-server.c
include/coap2/net.h
libcoap-2.map
libcoap-2.sym
man/coap-rd.txt.in
src/net.c

As coap-server now sets up 2 (or 4) endpoints, UDP and TCP based, all
subsequent endpoints are pre-pended to the ctx->endpoint list. Thus
ctx->endpoint will always be TCP based.  Setting IPV6_JOIN_GROUP on a TCP
socket is a no-no.
As join() is complex function, it should be within libcoap so as to not require
detailed knowledge of how internal structures work (which really should be 
opaque to the application writer).
src/net.c:
libcoap-2.map:
libcoap-2.sym:
Create coap_join_mcast_group() in src/net.c (as it is a network layer
function using the (fixed) join() code. (Iterate through the ctx->endpoint list 
looking for UDP based endpoints and only do the IPV6_JOIN_GROUP on them.)
There is no support for WITH_CONTIKI or WITH_LWIP at this point (returns -1). …

Fix mcast registrations when using TCP

---

Makefile.am
coap_config.h.contiki
coap_config.h.lwip
include/coap2/coap_mutex.h
src/coap_debug.c
src/coap_io.c
src/net.c

When there is a limited stack size, having large data items on the stack
can easily cause stack overflows.
This makes integration with any constrained stack O/S a lot easier.
include/coap2/coap_mutex.h:
Create coap_ mutex functions which are platform independent.
Makefile.am:
Include include/coap2/coap_mutex.h for distribution
coap_config.h.contiki:
coap_config.h.lwip:
As CONTIKI and LWIP have constrained stacks, set #define COAP_CONSTRAINED_STACK
src/coap_io.c:
src/net.c:
coap_show_pdu()
coap_log_impl()
coap_run_once()
coap_read_session()
coap_read_endpoint()
Move large data items out of the functions' stack and make them static
variables if COAP_CONSTRAINED_STACK is defined.
Protect the usage of these static variables by mutexes.
Note: if "-DCOAP_CONSTRAINED_STACK=0" …

For limited stacks, remove large items off the stack and make them static

---

include/coap2/coap_dtls.h

Adding in new structures to .h files that are typedef'd to not include
"struct" which are then referenced by other .h files can easily set up
recursive requirements that cannot be fulfilled.
In particular, adding in a new typedef'd struct to coap_dtls.h cannot
easily be used by coap_session.h
In coap_dtls.h, forward reference the (outside of the file) structures
and then prefix the coap_*_t entries with "struct", so making the
entries "struct coap_*_t" entries as appropriate

coap_dtls.h: Remove inter .h file dependencies

---

Makefile.am
include/coap2/coap_session.h
src/coap_gnutls.c
src/coap_io.c
src/coap_session.c
src/net.c

endpoint->hello is used to hold the 5 tuple etc. information about a new
connection that has come in.  Once the DTLS handshake has been completed
a new coap_session_t is created for the ongoing encrypted work.
However, if a second new DTLS request comes in before the first session
has completed the DTLS handshakes, it will overwrite the endpoint->hello
information causing the first request to stall / get lost.
GnuTLS already has to check that the initial DTLS packet is a Client Hello
before starting up a GnuTLS session, so moving this logic up a level to
the initial DTLS packet makes sense to create a coap_session_t at this
point and getting rid of the temporary endpoint->hello gets rid of this
issue.
Makefile.am:
Replace coap_endpoint_new_dtls_session with coap_session_new_dtls_session …

 Fix DTLS session loss when multiple connections in a short time

---

configure.ac
src/coap_io.c

configure.ac:
Test for the presence of 'struct cmsghdr' and set HAVE_STRUCT_CMSGHDR
if appropriate.
src/coap_io.c:
Revert to recvfrom() and sendto() if HAVE_STRUCT_CMSGHDR is not defined,
instead of using recvmsg() and sendmsg().

Handle platforms that do not have 'struct cmsghdr' defined

---

examples/client.c
src/coap_session.c

Once a ICMP Port Unreachable message is received, the session is
disconnected by a call to coap_session_disconnect().  However if the session
is of type CON,  the logic currently tries to retransmit the packet, but
nothing gets sent out.
Make sure that any entries on the context->sendqueue for the disconnected
session are removed.
Add in a Nack handler so that the client immediately exits on the session
disconnect.  Additionally this also tidies up the exit after transmission
retries.
Fixes the issue picked up by #347

Fix handling ICMP Port Unreachable messages

---

examples/client.c

Issue reproducable with (coap-server also running)
coap-client -b32 coap+tcp://[::1]
and note the partial response.
Set doing_getting_block if processing Block2 responses.
Add in a doing_getting_block test to not break out of the main while(){} loop.
[coap_can_exit() always returns 1 for TCP connections as there is nothing on
the session->delayqueue]

coap-client: Fix using -b NN with TCP connections

---

include/coap2/async.h
include/coap2/net.h
src/net.c

It appears that message_id was left in coap_context_t and coap_async_t
when coap_session_t was created.
include/coap2/async.h:
Remove message_id.
src/net.c:
No longer just set message_id.

Remove unused message_id from coap_context_t and coap_async_t

---

include/coap2/libcoap.h

include/coap2/libcoap.h:
Simplify COAP_DEPRECATED definition to generically handle Windows
or other builds when setting the define for COAP_DEPRECATED.
Fixes #363

Fix COAP_DEPRECATED for Windows C++ builds

---

include/coap2/subscribe.h
src/net.c
src/resource.c

Code works as expected for confirmable observes as the sent pdu is
retained for potential re-transmission.
For non-confirmable observes, the RST is seen in the response packet but
previously had no way of finding the observe/subscription to cancel (see #331)
Keep the last sent message id in coap_subscription_t (as tid) and when the
RST comes in, search for the subscription that has the same message id as
the pdu and remove that subscription.
include/coap2/subscribe.h:
Add in tid to coap_subscription_t (as per coap_pdu_t).
src/net.c:
Match tid in incoming RST pdu with a subscription.  If found, delete the
subscription.
Save tid in both pdu and subscription when sending off an observe response.
To test code, make the following temporary change to coap-client
diff --git …

Fix RST deleting observer for non-confirmable observe

---

examples/client.c

As per https://tools.ietf.org/html/rfc7959#section-4
...
Implementation Notes:
o  As a quality of implementation consideration, block-wise transfers
for which the total size considerably exceeds the size of one
block are expected to include size indications, whenever those can
be provided without undue effort (preferably with the first block
exchanged)
...
Include SIZE1 Option when sending data using BLOCK1 Option.
Picked up by #362

Add SIZE1 Option when sending BLOCK1 Option in packets in Client

---

scripts/build.sh
src/coap_openssl.c
tests/valgrind_suppression

Issue introduced by OpenSSL 1.1.1c causes valgrind errors to be reported.  See
https://www.mail-archive.com/openssl-commits@openssl.org/msg21701.html and
https://github.com/openssl/openssl/pull/8606 which did not make 1.1.1c
scripts/build.sh:
tests/valgrind_suppression:
Temporarily suppress valgrind errors when SSL_CTS_new() is called when running
the tests.
Note: This suppression will also need to be applied when running valgrind
against other CoAP executables using OpenSSL 1.1.1c to prevent the valgrind
errors getting reported.

Stop valgrind errors when using OpenSSL 1.1.1c

---

examples/client.c
src/net.c

src/net.c:
Corect the length for the final block size.
Add in an ETAG and SIZE2 option into the response as suggested by RFC7959.
Warn if URI path is too long for internal buffer (found when testing that
a large WellKnown response triggered sending BLOCK2 correctly).
Increase internal buffersize to allow longer URIs.
To reproduce issue
coap-client -b 256 coap://127.0.0.1/.well-known/core
As reported by Zafi Ramarosandratana.  See #360 which this fixes.

Fix final data size in last BLOCK2 response for .well-known/core

---

src/coap_gnutls.c

If a CoAP client using GnuTLS does not have PSK or PKI security defined
but communicatioes with coaps:// with a CoAP server that has PKI defined,
then there is a memeory leak when the session is closed down.
Free off PKI credentials if a client and PSK or PKI was not explicitly
defined in coap_dtls_free_gnutls_env().

Fix memory leak in GnuTLS client that does not have security defined

---

include/coap2/coap_dtls.h
src/coap_gnutls.c
src/coap_io.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

GnuTLS currently does not retry to send the Client Hello packets if there was
no (Server Hello) response.  This was never correctly implemented.
Fix receive_timout() so that it differentiates between DTLS and TLS.
If DTLS, if data has already been read in, indicate this.
if this is a coap_dtls_handle_timeout() call, only check readfds
(writefds will always be true, causing confusion).
Set DTLS timeouts where appropriate.
Update coap_dtls_*_timeout() functions to return the correct values.
src/coap_io.c:
src/coap_notls.c:
Add in coap_tick_t now parameter to coap_dtls_get_timeout() for better
accuracy.

Fix GnuTLS DTLS retries when Client Hello is not responded to

---

examples/coap-server.c

Only call coap_resource_notify() whenever a PUT is done to a created dynamic
resource, instead of once a second.
Issue found by Andy Ryan.

Make coap-server only trigger any observers when dynamic resource is updated

---

include/coap2/coap_io.h
libcoap-2.map
libcoap-2.sym
src/coap_io.c
src/coap_session.c
src/net.c

When try to use this library, I found two minor bugs.
1. Sometimes the session remote_addr and local_addr are not updated from the packet received. I just found the address copy function made the wrong direction.
2. Remove the endpoint from context list when free'd in coap_free_endpoint().

Fixed two minor bugs in endpoint free and session address update

---

configure.ac

Add in option so default is to only output the compile line as in
CC     src/libcoap_2-openssl_la-coap_event.lo
instead of
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fPIC
-fPIE -I./include/coap2 -I./include/coap2 -pedantic -Wall -Wcast-qual -Wextra
-Wformat-security -Winline -Wmissing-declarations -Wmissing-prototypes
-Wnested-externs -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-default
-Wswitch-enum -Wunused -Wwrite-strings  -Wlogical-op -I/opt/openssl/include
-std=c99 -ggdb3 -DCOAP_CONSTRAINED_STACK -DDTLS_CONSTRAINED_STACK
-D_GNU_SOURCE -MT src/libcoap_2-openssl_la-coap_event.lo -MD -MP
-MF src/.deps/libcoap_2-openssl_la-coap_event.Tpo -c
-o src/libcoap_2-openssl_la-coap_event.lo `test -f 'src/coap_event.c' ||
echo './'`src/coap_event.c
libtool: …

configure.ac: Enable silent compiles by default

---

src/coap_time.c

With
define Q(frac,fval) ((coap_tick_t)(((1 << (frac)) * (fval))))
and
tmp = SHR_FP(tv.tv_nsec * Q(FRAC, (COAP_TICKS_PER_SECOND/1000000000.0)), FRAC);
The Q function alwayes returns 0 in error - e.g.
(gdb) p ((coap_tick_t)(((1 << (FRAC))*((COAP_TICKS_PER_SECOND/1000000000.0)))))
$6 = 0
(gdb) p ((((1 << (FRAC))*((COAP_TICKS_PER_SECOND/1000000000.0)))))
$7 = 0.001024
whereas we need the value 0.001024 to multiple with tv_nsec.
This change fixes this by moving the coap_tick_t from Q to SHR_FP.
Found when debugging #374

coap_time.c: Make coap_ticks() more accurate than to the nearest second

---

include/coap2/coap_time.h
src/net.c

This is done by calling prng_init() with a non-zero value in coap_startup().
Change 7fb4ace2b709994bbbebab4c2d367ac76140eee9 modified the parameter to
prng_init() from a computed value to 0 when the code was re-organized.
This change uses the current time in microseconds as the seed to prng_init().
include/coap2/coap_time.h:
Add in coap_ticks_to_rt_us() support for lwIP and Contiki
src/net.c:
Update call to prng_init() in coap_startup() to use time in microsecs as the
seed parameter
See #373 where the issue was raised.

net.c: Start new coap_context with a random message identifier

---

configure.ac
examples/client.c
include/coap2/coap_session.h
include/coap2/net.h
man/Makefile.am
man/coap-client.txt.in
man/coap.txt.in
man/coap_handler.txt.in
man/coap_keepalive.txt.in
man/coap_observe.txt.in
src/coap_io.c
src/coap_session.c
src/net.c

Add in support for both reliable and unreliable sessions when calling
coap_context_set_keepalive().
include/coap2/coap_session.h:
Track the last ping mid in coap_session_t.
src/coap_io.c:
Support both reliable and unreliable sending of pings in coap_write().
src/net.c:
Determine whether RST packet response is associated with a CoAP Empty Ping
that was sent and handle accordingly.
configure.ac:
man/coap-client.txt.in:
man/coap.txt.in:
man/coap_handler.txt.in:
man/coap_keepalive.txt.in: (New)
man/coap_observe.txt.in:
Add in a new man page (coap_keepalive).
Update documentation to remove references to TCP and reliable only.

Update Keepalive support to include unreliable sessions

---

src/coap_gnutls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c

When an idle server (D)TLS session times out, no event is reported to a
defined event handler.  COAP_EVENT_DTLS_CLOSED is reported whenever there is
a read / write issue, and this fix also reports the event COAP_EVENT_DTLS_CLOSED
when the (D)TLS session is closed.
Some extra code had to be added in to prevent event COAP_EVENT_DTLS_CLOSED
being reported twice.
Report event COAP_EVENT_DTLS_CLOSED when coap_dtls_free_session() and
coap_tls_free_session() are called.
Do not log spurious (D)TLS Alert packets received after session is closed.

Report event COAP_EVENT_DTLS_CLOSED when idle (D)TLS session times out

---

examples/coap-rd.c
include/coap2/coap_io.h
include/coap2/coap_session.h
src/coap_io.c
src/coap_io_lwip.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c
src/resource.c

Make endpoint->sessions and context->sessions a hashed chain of sessions
based on a key comprising of local and remote addresses and ports instead of
a linked list that has to be linearly searched.
include/coap2/coap_io.h:
include/coap2/coap_session.h:
Create a new struct coap_addr_tuple_t for the local and remote addresses/ports to be
used as the hash key.  Update coap_packet_t and coap_session_t appropriately.
Create SESSIONS_* macros to Add, Delete, Find and Iterate through the hashed
chain.
src/coap_io.c:
src/coap_io_lwip.c:
src/net.c:
Update with the new struct element names and replace the LL_* functions with
SESSIONS_* as appropriate.
Update coap_endpoint_get_session() to use …

Make sessions list hashed to make lookups faster

---

src/coap_openssl.c

Give the function that abstracts the Subject Alternative Name (SAN),
or the CN= if SAN is not available, a better descriptive name to prevent
possible confusion.

Rename get_common_name_from_cert() to get_san_or_cn_from_cert()

---

tests/oss-fuzz/pdu_parse_target.c
tests/oss-fuzz/split_uri_target.c

This PR
- Adds coap_show_pdu() to existing test harness (CC #214)
- Creates a new oss-fuzz test harness for coap_split_uri() (CC #212)

Add coap_show_pdu() and coap_split_uri() to existing/new oss fuzz test harness

---

include/coap2/coap_dtls.h
include/coap2/coap_session.h
include/coap2/pdu.h
man/coap_encryption.txt.in
man/coap_tls_library.txt.in
src/net.c

As suggested in #292 , several lists of #define could easily be defined
as enum instead - which allows for extra compiler checking.
The challenge was for where the (#define/enum) parameter defined in a
structure was one byte in size.  Doxygen was picky and got confused, not
maintaining the fact that it was an enum if macros were used to differentiate
between using Microsoft or GCC when changing the enum size default from that
of an int.
include/coap2/coap_session.h:
include/coap2/pdu.h:
Use enums instead of #define where practical.
src/net.c:
Handle all the enum cases.
man/coap_tls_library.txt.in:
Update man documentation.

Convert #define to enum where possible

---

doc/Doxyfile.in
doc/Makefile.am

doc/Doxyfile.in:
SORT_GOUPNAME = YES to sort Modules
doc/Makefile.am:
Sort the MAN_FILES list.  coap(7) first and examples last.

Order the doxygen Modules and Manual Pages listings alphabetically

---

examples/client.c

In a [fix](https://github.com/RIOT-OS/RIOT/pull/11002#issuecomment-515543372) to RIOT's block implementation, we found that the libcoap client example does not show the payload on the final response of a block1 exchange. However, the client does show the payload when there is not a block option present.
This PR simply outputs the response payload in the block1 case.

Client example show payload on block1 completion

---

src/net.c

Move the coap_log() entry to after updating the session information.
Seen when coap-client is doing multicast request sends

net.c: Log correct address in coap_read_session()

---

src/net.c

Enforce RFC7252 8.1 "Such multicast requests MUST be Non-confirmable"
by logging the PDU error and dropping the PDU tranamission.

net.c: Enforce non-confirmable for multicast request messages

---

man/coap_handler.txt.in

Document why certain parameters may be NULL.

coap_handler.txt.in: Add in clarification notes for handler parameters

---

examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
examples/tiny.c

examples/tiny.c:
Make the applications ignore SIGPIPE.
Support clean exit for SIGTERM / SIGQUIT for valgrind testing.

Fix SIGPIPE causing unexpected exit of example applications

---

examples/coap-server.c
include/coap2/str.h
libcoap-2.map
libcoap-2.sym
src/resource.c
src/str.c

As pointed out in issue #368 [1], C++ officially forbids aggregate
initialization for non-aggegrates. This change therefore introduces
an alternative version (which works for both C and C++) to provide
the required functionality.
Fix parameter type in coap_add_attr() call.
Static variables can no longer make use of coap_make_str_const().
Fixes #368.
[1] https://github.com/obgm/libcoap/issues/368

str.h: Fix coap_make_str_const() for C++

---

Makefile.am
configure.ac
examples/coap-server.c
include/coap2/coap_io.h
include/coap2/net.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap.txt.in
man/coap_io.txt.in
src/coap_io.c
src/coap_openssl.c
src/coap_session.c
src/net.c

If epoll is available, use it within libcoap to speed things up, as well as
present to applications a file descriptor that can be used in a select() or
returned as an event in a epoll_wait() call.
Whenever coap_new_context() is called. set up a new epoll infrastructure with
epoll_create() and destroy it with coap_free_context().
For each new endpoint or session, add the socket fd to epoll.  When the socket
is closed, remove the socket fd from epoll.
Whenever a socket wants a write, the appropriate epoll event gets EPOLLOUT
added and when the write happens reset the event back to just EPOLLIN.
As there may be a packet retry event sometime in the future, a timerfd is
created and added to the epoll structure (done in coap_new_context) which gets
freed off in coap_free_context. If …

Add in internal epoll support to expose a monitor-able file descriptor

---

coap_config.h.contiki
coap_config.h.lwip
coap_config.h.windows

coap_config.h.contiki:
coap_config.h.lwip:
coap_config.h.windows:
Strip leading _ in the file protection wrappers.
See #294

Remove reserved identifiers from coap_config.h for specific builds

---

src/coap_io.c

It appears that MAC OX X (10.13.2) builds do not like the size of the sa to
be larger than the size of struct sockaddr_in when working with IP v4
addresses.
src/coap_io.c
Update the bind() calls to use the correct address sizes.
Identified in #150

Fix bind() address size for Mac OS X

---

Makefile.libcoap
examples/client.c
examples/etsi_iot_01.c
examples/lwip/Makefile
include/coap2/address.h
libcoap-2.map
libcoap-2.sym
src/address.c

This is compiler version dependent when doing static inline expansions.
Make hex2char() just static.
Make coap_add_payload() just static.
include/coap2/address.h:
src/address.c:
Make coap_address_init() an actual function.
libcoap-2.map:
libcoap-2.sym:
Expose coap_address_init() as a function.

Fix -Winline compiler warnings about inlining failed

---

include/coap2/coap_dtls.h
include/coap2/coap_session.h
include/coap2/pdu.h
man/coap_encryption.txt.in
src/net.c

include/coap2/coap_dtls.h
include/coap2/coap_session.h
include/coap2/pdu.h
man/coap_encryption.txt.in
src/net.c
Revert out all the #define -> enum in #386 that require the enum to be
one byte long.
#394 and #267 flagged up the VS2017/VS2019 compilation issue.

Revert out changes to make 1 byte enums

---

configure.ac
include/coap2/coap_mutex.h

This PR proposes a configure-time check for pthread mutexes as discussed in PR #401 which would then be obsolete.

Pthread configure check

---

configure.ac

Add in support for --enable-small-stack to define
COAP_CONSTRAINED_STACK in coap_config.h

configure.ac: Make COAP_CONSTRAINED_STACK configurable

---

TODO
configure.ac
examples/client.c
include/coap2/coap_internal.h
include/coap2/coap_io.h
include/coap2/net.h
include/coap2/resource.h
src/address.c
src/block.c
src/coap_debug.c
src/coap_io.c
src/coap_session.c
src/encode.c
src/mem.c
src/net.c
src/option.c
src/pdu.c
src/resource.c
src/str.c
src/subscribe.c
src/uri.c

Let configure enable (the default) or disable assert() code.
configure.ac:
Add in --enable-assert (the default) / --disable-assert support in libcoap.
Previously this was always enabled unless -DNDEBUG was passed in as a compiler
option.  Now NDEBUG is set or unset as appropriate in coap_config.h
This does not affect how assert()s work within the examples etc., only in the
library.
TODO:
HAVE_ASSERT_H is now cleaned up, so remove entry.
include/coap2/coap_internal.h:
Include assert.h for the library.
include/coap2/coap_io.h:
include/coap2/resource.h:
src/address.c:
src/block.c:
src/encode.c:
src/mem.c:
src/option.c:
src/pdu.c:
src/subscribe.c:
src/uri.c:
Remove un-needed '#include <assert.h>'
Note: address.h and utlist.h still include assert.h as …

Add --disable-assert support for the library

---

BUILDING

Add in instructions as to how to build libcoap on a Windows platform
as well as update the other information with how to get the libcoap
code.
See question initially raised in #267

BUILDING: Update adding Windows build information

---

include/coap2/encode.h
libcoap-2.map
libcoap-2.sym
src/encode.c

Options such as COAP_OPTION_ETAG are up to 8 bytes in size.  While
being opaque, they can internally be represented as an 8 byte number.
include/coap2/encode.h:
libcoap-2.map:
libcoap-2.sym:
src/encode.c:
Create 8 byte versions coap_decode_var_bytes8() and coap_encode_var_safe8().

encode.c: Support encoding/decoding 8 byte options

---

configure.ac

The "ac_cv_header-..." macros are either set to "yes" or "no" and never to
the empty string.

Fix epoll detection

---

include/coap2/net.h
libcoap-2.map
libcoap-2.sym
src/coap_io.c
src/net.c

It is possible to miss a packet retransmission if it is just about to happen
and the coap_run_once() logic takes the time past the packet retransmission.
The retransmission will take place when coap_run_once() is next run, but that
could be significantly later.
1) Create a new coap_io_prepare_epoll() function that calls coap_write(), but
sets the etimer within this function instead of at the end of coap_run_once().
2) Handle the etimer trigger within coap_io_do_events() rather than loop
checking coap_io_do_events() within coap_run_once().
Define coap_io_prepare_epoll().
Update coap_io_do_events() to be type void.
src/coap_io.c:
Add in coap_io_prepare_epoll().
Update coap_run_once() to use new/updated functions.
src/net.c:
Update coap_io_do_events().
Make …

Fix timing window in epoll logic

---

include/coap2/coap_debug.h
man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in
src/coap_debug.c
src/coap_openssl.c

Remove NULL as a valid cipher from the cipher list.
Add in TLSv1.3 ciphers if OpenSSL 1.1.1 (they are already included in
TLSv1.2 definition, but this is to document this is happening).
Remove the TLSv1.0 deprecated ciphers.
Cipher strings can now be overridden during compilation by
using -DCOAP_OPENSSL_CIPHERS=xxx compiler option where xxx is the 
cipher string as defined in 
https://www.openssl.org/docs/man1.1.0/man1/ciphers.html
Explicit PSK cipher strings can now be overridden during compilation
by using -DCOAP_OPENSSL_PSK_CIPHERS=xxx compiler option where xxx is the
cipher string.
Log the client ciphers presented, and the cipher chosen.
include/coap2/coap_debug.h:
Add in LOG_CIPHERS as a debug level (value 9) which matches getting the
cipher …

OpenSSL: Update ciphers

---

Makefile.am
examples/client.c
examples/coap-server.c
include/coap2/coap_debug.h
include/coap2/coap_dtls.h
include/coap2/coap_session.h
include/coap2/net.h
include/coap2/str.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_handler.txt.in
man/coap_logging.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
src/coap_gnutls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c
src/str.c

Currently, a server cannot differentiate between different presented Identities and so use different PSK keys on a per client basis.  Furthermore, different Identity Hints cannot be presented to clients based on their SNI information received by the server.
This update creates 2 new interfaces - coap_context_set_psk2() and coap_new_client_session_psk2() which allow callbacks to be defined in a similar way to the *_pki() functions.  The existing _psk() functions now just call the *_psk2() with the appropriate parameters set up. 
This update has been split up into 5 parts - each part has fully operational code in its own right.
Testing has been for all combinations of openssl, gnutls and tinydtls, using Openssl 1.1.0g and 1.1.1 and GnuTLS 3.3.0 and 3.6.4 (TinyDTLS does not support SNI).
In …

Add in PSK support for SNI, Identity and Hint checking to enable PSK changes

---

examples/client.c
examples/coap-server.c
man/coap-server.txt.in

Add in -S option to support changing certificate/ca if there is as SNI match.
man/coap-server.txt.in:
Update man page with new -S option.

coap-server: Add in support for SNI to change PKI certificates

---

src/resource.c

The r->partiallydirty is set to 0 before the limitation. A new
request will be dropped when last request hasn't receive it's ACK.
Restore r->partiallydirty to 1 in the condition.

bugfix: ea72c3d7 outstanding CON requests limitation may drop new request.

---

include/coap2/net.h
libcoap-2.map
libcoap-2.sym
man/coap_io.txt.in
src/coap_io.c

coap_write() and coap_read() are really internal functions that are called
from within coap_run_once() separated by a select() to wait for i/o and
ideally should not be used in applications.
However, currently, coap_write() and coap_read() are needed instead of
coap_run_once() if there is no epoll support in libcoap so that if additional
non libcoap FDs need to be set up and monitored by the select() call they
then can be processed accordingly if the non libcoap FDs are set in the
select() response.
coap_io_process_with_fds() is a new function extending coap_run_once() that
allows non libcoap FDs to be monitored in the coap_run_once() internal
select() call and can then be tested by the caller of
coap_io_process_with_fds().
coap_run_once() now calls coap_io_process_with_fds() with …

coap_io.c: Add in additional FD checking support for coap_run_once()

---

include/coap2/resource.h
man/coap_observe.txt.in
man/coap_resource.txt.in
src/resource.c

https://tools.ietf.org/html/rfc7641#section-4.5 requires that non-confirmable
observe responses should be sent as confirmable at least once every 24 hours.
However there is a requirement to override this periodical confirmable sending
behavior in lossy under DDoS attack type environments.
https://tools.ietf.org/html/draft-ietf-dots-signal-channel-41#section-4.4.2.1
Add in support for, and document, a new coap_resource_init() flag
COAP_RESOURCE_FLAGS_NOTIFY_NON_ALWAYS to handle this non RFC7641 requirement.

observe: Add in support for all observe responses to be non-confirmable

---

examples/client.c
examples/coap-server.c
src/coap_openssl.c

Add in specific _WIN32 definitions for the missing functionality from
recent PR updates.
R_OK (used by access())
strndup()
strcasecmp()

Windows: Update code to build on Windows

---

examples/coap-rd.c
man/coap-rd.txt.in

Add in basic (D)TLS support using code and options from coap-server.
Closes #435

coap-rd: Add in (D)TLS support

---

.travis.yml
Makefile.am
README.md
build-env/Dockerfile.build-env
build-env/Dockerfile.develop
configure.ac
examples/coap-server.c
include/coap2/coap_dtls.h
man/coap_attribute.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_handler.txt.in
man/coap_logging.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/coap_tls_library.txt.in
scripts/build.sh
scripts/dist.sh
src/coap_debug.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
tests/test_tls.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Add in MbedTLS support as an alternative (D)TLS encryption.  Currently TLS is not supported.
Add in MbedTLS support
Add in MbedTLS library support as another alternative TLS library
Makefile.am:
Include new src/coap_mbedtls.c file.
configure.ac:
Add in --with-mbedtls support which generates HAVE_MBEDTLS in coap_config.h.
Add in TLS Library type COAP_TLS_LIBRARY_MBEDTLS and make COAP_TLS_LIBRARY_*
defines an enum.
Add in PKI Key type COAP_PKI_KEY_PEM_BUF for passing in PEM information
that is held in memory instead of in a file.
Output MbedTLS information if appropriate.
src/coap_mbedtls.c: (New)
Contains the MbedTLS interface code.
src/coap_notls.c:
Do not use code if MbedTLS is being built.
Fix socket closure order in …

Add in MbedTLS support

---

src/coap_io.c

Wrap calls to coap_dtls_handle_timeout() with coap_session_reference() and
coap_session_release() so that the session pointer can continue to be used.
Found when a DTLS session timed out using OpenSSL.

coap_io.c: Stop calls to coap_dtls_handle_timeout() dereferencing the session

---

include/coap2/coap_dtls.h
src/coap_gnutls.c

coap_dtls_get_timeout() may continue to return 'now' if the underlying
GnuTLS library gets confused by duplicate packets and so clears out
the data is to be retransmitted flag.  If there is a DTLS timeout retry, the
underlying logic does not reset 'last retransmit' on retrying the re-send
of the (now) non-existent data, so causing a spin in the coap_write() logic.
This fix is to return 'now+dtls_timout' on the second and subsequents attempts 
to return 'now'.
Make use of the new #defines that #353 is using so that this code compiles.

coap_gnutls.c: Fix potential spin in DTLS retransmit timeout loop

---

include/coap2/pdu.h
include/coap2/resource.h
man/coap_handler.txt.in
src/resource.c

Make the COAP_REQUEST_* #defines enum coap_request_t for clarity.
This should help prevent mistakes such as in #448.

Make COAP_REQUEST_* enum for clarity

---

src/net.c

Only update con_active if PDU has been successfully sent

net.c: Correct setting of con_active if error

---

doc/main.md
include/coap2/coap_tcp_internal.h
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c

Missing COAP_DISABLE_TCP wrapper in OpenSSL 1.1.0 - 1.1.1 specific code
doc/main.md:
Update Copyright year.
include/coap2/coap_tcp_internal.h:
Update documentation for the internal TCP functions

coap_openssl.c: OpenSSL < 1.1.1 fails to build with --disable-tcp

---

src/coap_session.c

`coap-server(1)` segfaults when invoked as:
$ coap-server -A '2001:db8::1'
Feb 09 18:28:49 WARN coap_socket_bind_udp: bind: Address not available
Segmentation fault
In this case, the `ep->context->endpoint` is NULL but `coap_free_endpoint` still attempts to access it. To prevent this invocation from causing a segmentation fault, check if `ep->context->endpoint` is NULL before accessing it.

coap_free_endpoint: fix segfault with incorrect -A argument

---

examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/contiki/coap-observer.c
examples/contiki/server.c
examples/etsi_iot_01.c
include/coap2/net.h
libcoap-2.map
libcoap-2.sym
man/coap_io.txt.in
man/coap_observe.txt.in
src/coap_io.c
src/coap_io_lwip.c
src/net.c
src/pdu.c

coap_read(), coap_write() and coap_run_once() are confusing in their names
and do not really describe what they do.
For example, coap_read() does both reading and writing, coap_write() may
do some writing, but primarily is used to determine what should be monitored
and for how long to wait in the following select() or epoll_wait() calls.
coap_run_once() implies that the code is only to be run once - again confusing.
By renaming coap_read() to coap_io_do_io(), this better describes what this
function does.
By renaming coap_write() to coap_io_prepare_io() this better describes what this
function does.
By renaming coap_run_once() to coap_io_process(), this better describes what
this function does.
By renaming coap_io_do_events() to coap_io_do_epoll(), this better describes what
this function …

Rename coap_run_once() to coap_io_process()

---

src/coap_openssl.c

When libcoap config allows self-signed certificates (`coap_dtls_pki_t.allow_self_signed == 1`) the library should also accept self-signed certificates at depth 0. This is achieved by allowing [X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT](https://www.openssl.org/docs/man1.1.0/man3/X509_STORE_CTX_get_error_depth.html) case.

OpenSSL: Support self-signed certificates at depth 0

---

src/coap_debug.c

This helps to debug timing issues such as DTLS retransmits.

coap_debug.c: Extend date+time to include millisecs reporting

---

src/coap_mbedtls.c

Only include psk_sni_callback() if appropriate.

coap_mbedtls.c: Fix esp-idf build warning if client only

---

include/coap2/pdu.h

The # COAP_RESPONSE_nnn entries were introduced to handle a response change
introduced by draft-ietf-core-coap-04 in 2011.  These are no longer used
and can cause confusion - e.g.
define COAP_RESPONSE_304      COAP_RESPONSE_CODE(203)  /* 2.03 Valid */
as raised in #456.  Entries now removed.

pdu.h: Remove unneeded backward compatible #defines from 2011

---

Makefile.libcoap
examples/client.c
examples/lwip/Makefile
src/coap_session.c
src/uri.c

In the same way that coap_split_uri() allows coaps:// scheme even if DTLS is
not available, it should allow coap+tcp:// and coaps+tcp:// scheme and let
other functions check whether TCP/TLS is available or not.
Verify if TCP is supported for scheme coap+tcp://.
Verify CoAP protocol is supported in coap_session_create_client().
Add verify for TCP protocol in coap_new_endpoint(), as well as always check
if TLS is supported.
src/uri.c:
Always alow coap+tcp:// and coaps+tcp:// in coap_split_uri() as a parsed
scheme in same way that coaps:// is always allowed.

DISABLE_TCP: Make TCP enabled code checking more rigorous

---

examples/coap-server.c
examples/contiki/server.c
include/coap2/net.h
man/coap_io.txt.in
src/coap_io.c

Replace COAP_RUN_BLOCK with COAP_IO_WAIT and COAP_RUN_NOBLOCK with
COAP_IO_NO_WAIT for naming clarity.
Instead of COAP_IO_NO_WAIT being 1, make it -1 to fix 1ms busy loop.
Handle the case when coap_io_prepare_io returns 0 to prevent indefinite
select() wait.
Make the timeout_ms parameter uint32_t in coap_io_process*() functions to
make sure special case of COAP_IO_NO_BLOCK is correctly handled on different
architectures.
Update COAP_IO_NO_BLOCK to -1. 
src/coap_io.c:
Fix the 1ms busy loop and potential infinite wait in the non epoll case.
man/coap_io.txt.in:
Update documentation to reflect the changes.
examples/contiki/server.c:
Update to use COAP_IO WAIT and COAP_IO_NO_WAIT as appropriate.
Extends #462 fix.

coap_io_process: Fix 1ms busy loop and indefinite sleep

---

include/coap2/net.h

Give a hint in the compiler error message about using deprecated
COAP_RUN_BLOCK and COAP_RUN_NO_BLOCK and what they are replaced with.
[Should really have been in #463]

Report on old usage of COAP_RUN_BLOCK and COAP_RUN_NO_BLOCK

---

examples/coap-server.c
include/coap2/net.h
include/coap2/resource.h
man/coap_observe.txt.in
src/resource.c

Track time spent in the epoll branch for the select() and coap_io_Process()
calls to correctly adjust wait_ms.
Adjust wait_ms to be the remaining amount in the current second, so that
any 'time' observers get the updated time just after the new second starts.
Add in support to track that an observe is pending transmission - primarily
a saving of needing to look up if a observe needs to be sent.
include/coap2/resource.h:
Add in support to track the context that 'owns' a resource.
Track the context that 'owns' a resource in coap_add_resource().
Track the fact that when we are making a resource partially dirty by recording
that an observe is pending in coap_notify_observers().
In the epoll case, make sure that timerfd triggers …

coap-server: Make sure observe updates are sent off asap

---

man/Makefile.am
man/coap_session.txt.in
man/coap_tls_library.txt.in

coap_session_str(3) is defined in both coap_session.txt.in and
coap_logging.txt.in.  This fix removes the duplicate so that it is
only part of coap_logging.txt.in.
Correct EXTRA_PAGES definition.
man/coap_session.txt.in:
Remove references to coap_session_str definitions.

Remove man page coap_session_str definition duplications

---

.gitignore
Makefile.am
autogen.sh
configure.ac
man/Makefile.am
man/coap_encryption.txt.in
man/coap_pdu_setup.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/examples-code-check.c
scripts/build.sh

There needs to be an easy way to validate that the examples provided in the
man pages compile without errors.
This PR provides a new executable examples-code-check that can be run against
the .txt.in files that are in the man directory.  It abstracts the code for
each example and then runs the compiler against that stub code reporting errors
and warnings as appropriate for subsequent fixing in the man page.
.gitignore:
Ignore the new executable and the files it generates.
autogen.sh:
Make sure that all the temporary stub code files are cleaned up.
Support building and clean-up of the new examples-code-check.
man/examples-code-check.c: (new)
The code that parses the man pages, looking for examples and the gets
the examples compiled, testing for errors.
The function …

Man examples: Add in support to check that the man example's code compiles

---

src/net.c

Check PDU code before setting up Observe subscription.
https://tools.ietf.org/html/rfc7641#section-4.1 only refers to GET.
https://tools.ietf.org/html/rfc8132#section-2.4 adds in FETCH
Check observe action is one of 0 or 1 to add or delete 
subscriber appropriately as per RFC7641.

net.c: Restrict subscriptions to only GET/FETCH requests

---

examples/client.c
examples/coap-rd.c
examples/coap-server.c
include/coap2/block.h
include/coap2/coap_hashkey.h
src/block.c
src/coap_debug.c
src/coap_hashkey.c
src/coap_io.c
src/coap_openssl.c
src/net.c

include/coap2/block.h:
include/coap2/coap_hashkey.h:
src/block.c:
src/coap_hashkey.c:
src/coap_io.c:
src/net.c:
Fix C4267 windows compilation warnings when using Visual Studio where
size_t variable parameters are being converted  in both size and sign.
There still are some C4116 warnings to fix.

Windows C4267 errors: Fix size_t conversion warnings in windows builds

---

src/coap_openssl.c

Enable the users of libcoap to specify (D)TLS signature_algorithms and supported_groups extension values when used with OpenSSL using optional defines:
```C
/* COAP_OPENSSL_CIPHERS is already supported by libcoap. */
#define COAP_OPENSSL_CIPHERS "ECDHE-ECDSA-AES256-GCM-SHA384"
/* These two defines are added by this patch. Values are case-sensitive. */
#define COAP_OPENSSL_SIGALGS "ed25519"
/* Groups are supported only in OpenSSL v1.1.1 and above. */
#define COAP_OPENSSL_GROUPS "X25519"
```

Support custom (D)TLS signature_algorithms and supported_groups

---

man/Makefile.am
man/coap_attribute.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_handler.txt.in
man/coap_io.txt.in
man/coap_keepalive.txt.in
man/coap_logging.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/coap_tls_library.txt.in

man/coap_attribute.txt.in:
man/coap_context.txt.in:
man/coap_handler.txt.in:
man/coap_io.txt.in:
man/coap_keepalive.txt.in:
man/coap_logging.txt.in:
man/coap_observe.txt.in:
man/coap_pdu_setup.txt.in:
man/coap_recovery.txt.in:
man/coap_resource.txt.in:
man/coap_session.txt.in:
man/coap_tls_library.txt.in:
Make sure the full list is defined in the NAME section
[Gives a2x warnings that there are more than 10 entries, but this is OK]
Update where BUGS can be reported to.
Remove EXTRA_PAGES as all the names are now defined under NAMES

man pages: Tidy up

---

CMakeLists.txt

Change library name from coap to coap-2.

CMakeLists.txt: Make library name libcoap-2 to match name in man pages

---

include/coap2/coap_tcp_internal.h
src/coap_session.c
src/net.c

src/net.c:
Wrap more code with #if !COAP_DISABLE_TCP
See #330.

TCP_DISABLE: reduce more of the dead code when --disable-tcp is in used

---

CMakeLists.txt

Windows testing highlighted that COAP_DISABLED_TCP was not being correctly
set from ENABLE_TCP.
Also sorted some of the lists for ease of maintenance.
#496 needs to also be merged for Windows CMake builds to work that have -DENABLE_TCP=OFF

CMakeLists.txt: Fix COAP_DISABLE_TCP

---

Makefile.am
examples/coap-server.c
examples/etsi_iot_01.c
examples/lwip/Makefile
include/coap2/async.h
include/coap2/net.h
include/coap2/resource.h
libcoap-2.map
libcoap-2.sym
src/async.c
src/net.c

Calling coap_free_context() does not free off any async entries, and so
raises assertion errors when coming to freeing off sessions if any async
entries exist.
async_data_t is a union, but the size of val and ptr are not the same - so
usage can have uninitialized data - hence bad timeout values.
Makefile.am:
Do not expose coap_delete_all*() functions.
Makefile.libcoap:
Include async.c for the Contiki build.
Fix async_data_t issue.
Fix 32 bit compiler warnings using same logic as coap-server for holding the
async timeout value.
examples/lwip/Makefile:
Include async.c for the LwIP build.
include/coap2/async.h
Define coap_delete_all_async() function.
include/coap2/net.h
include/coap2/resource.h
Document coap_delete_all*() functions as internal. …

async: Fix session->ref assertion failure and timeout values

---

BUILDING
CMakeLists.txt

To build shared libraries, either the BUILD_SHARED_LIBS=ON option can be
defined globally for building, otherwise defining BUILD_SHARED_LIBS as an
OPTION in CMakeLists.txt works providing the OPTION is defined before the
add_library() call.
This fix is to move the OPTION BUILD_SHARED_LIBS to before the
add_library() call.
NOTE: Shared Library support is not currently available for Windows as the
appropriate functions are not currently exported.
BUILDING:
Document the Windows limitation and tidy up a bit.

CMakeLists.txt: Put BUILD_SHARED_LIBS option before add_library()

---

tests/oss-fuzz/pdu_parse_target.c

So i went through the code-base, and added a few helper/utility function calls to improve the coverage of the existing Fuzzer.
By doing so, the coverage goes up by 
Line coverage: 2.71% / 213 Lines
Function coverage: 4.54% / 15 functions
Region coverage: 2.36% / 167 new regions
Coverage report:
[https://imgur.com/a/GEnY81L](https://imgur.com/a/GEnY81L)
Let me know if there is any incorrect usage of the Api!

[Oss-Fuzz] Improving pdu_parse_fuzzer

---

include/coap2/coap_session.h
include/coap2/pdu.h
src/coap_session.c
src/net.c

src/net.c:
Add in a sanity check that the PDU length is not more that the negotiated
CSM size for incoming data.
Track CSM remote supports block transfer.
Do not allow Block options if CSM has not negotiated block transfer.
Include block-wise-transfer is supported in the CSM
include/coap2/coap_session.h:
Make MTU size bigger than 32 bits as CSM mtu size can be greater than 32 bits.
Track CSM remote supports block transfer.

TCP: Prevent incorrectly formed PDUs causing RAM exhaustion.

---

src/net.c

If the initial coap_send() PDU initiates a TCP/TLS connection, the PDU is
delayed until the CSM packets are exchanged.  If the initial PDU contains
a BLOCK1 or BLOCK2 option, the PDU gets dropped as Block-Wise-Transfer in the
CSM has not been seen yet.  Seen if '-b X' option is used for coap-client.
The check is now only when the session has fully established and the
situation only logged and the PDU Not dropped.
Issue introduced in #512

net.c: Relax TCP CSM Block-Wise-Transfer tests

---

HOWTO.dual.gnutls
HOWTO.dual.openssl
HOWTO.dual.softhsm2
HOWTO.pkcs11
Makefile.am
examples/client.c
examples/coap-server.c
include/coap2/coap_dtls.h
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_encryption.txt.in
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/net.c

Add in a new PKI_KEY type for PKCS11 URI to get the PKI information from a
smart card or hsm device.
Currently only OpenSSL and GnuTLS are supported.
Makefile.am:
Do not expose coap_dtls_shutdown() function.
Add in support for using pkcs11: URIs for defining the Certificates and
Private Keys.
Add in COAP_PKI_KEY_PKCS11 Key type.
man/coap-client.txt.in:
man/coap-server.txt.in:
Update documentation for supporting PKCS11.
Add in documentation for COAP_PKI_KEY_PKCS11.
Correct some typos.
HOWTO.dual.gnutls (new):
HOWTO.dual.openssl (new):
HOWTO.pkcs11 (new):
HowTo information.
Add in PKCS11 support.
PKCS11 not yet supported.
Add in no-op …

PKCS11: Add in PKCS11 support for PKI

---

configure.ac
tests/Makefile.am

libtool marks functions included in the Makefile.am CTAGS_IGNORE list as
nm type 't' in .so library files so that they are not globally visible.
This means that tests/testdriver is unable to access these functions.
However, when building .a files, these functions remain as nm type 'T', so
are globally available.
This change causes tests/testdriver to always be be built with the .a
library file.
configure.ac:
Always enable --enable-static if --enable-tests is set.
Include this --enable-static requirement in the help information.
tests.Makefile.am
Change the default library type to always be .a and re-order parameters.

testdriver: Add in support for access to libcoap internal functions

---

CMakeLists.txt

Use autoreconf instead of autoconf

cmake: Fix builds with new TinyDTLS

---

src/net.c

coap_add_token() can error for multiple reasons when building the response
PDU - but then the response PDU is not deleted on error if it exists.
The PDU is now deleted on coap_add_token() error.
Fixes #535

net.c: memory leak in handle_request if error input

---

Makefile.am
README.md
examples/client.c
include/coap2/pdu.h
man/coap-client.txt.in
man/coap.txt.in
man/coap_pdu_setup.txt.in
src/coap_debug.c
src/net.c
src/pdu.c
tests/test_pdu.c

All this is handled by libcoap with coap-client having the ability to define
an initial Hop Count value for testing. No other application support is
required.
Incoming requests are checked for the Hop Limit option - if found, the value
is decremented in the PDU before passing it up to the application. If it
decrements to 0, a 5.08 response is generated.
coap_add_option() checks if this is a Proxy option for a request. If so, and
Hop Limit option does not exist, then the Hop Limit option is inserted into
the PDU with the default value (16).
coap_send() checks if it is a 5.08 response and if so, prepends the diagnostic
data with the IP address of the transmitting interface. If the IP address
already exists, then the PDU is dropped as the return path for the 5.08 response
is looping.  An …

RFC8768: Add in support for CoAP Option Hop Limit loop detection

---

examples/client.c
include/coap2/coap_subscribe_internal.h
include/coap2/resource.h
man/coap_pdu_setup.txt.in
src/net.c
src/resource.c

Support observe for both GET and FETCH.
Correct coap-client programatic addition of observe establish option which
"happened" to work previously because COAP_OBSERVE_ESTABLISH was 0.

Observe: Support FETCH

---

src/option.c
src/str.c

These are fixed memory sizes, but applications can ask for a bigger size
which will lead to memory corruption.
src/option.c:
src/str.c:
Check the requesting size to verify that it is within limits.  Contiki
properly checks the sizes.  Return NULL if too large with a logged varning.

LwIP: Check memory allocation sizes for COAP_OPTLIST and COAP_STRING

---

src/net.c

If a client TCP connection connects, EPOLLOUT remains enabled so epoll_wait()
always returns immediately causing a loop until there is other data traffic.
This fix is to enable EPOLLIN and disable EPOLLOUT if COAP_SOCKET_WANT_WRITE
is not set at point of connection successful.

epoll: Stop spin between TCP connect and received data

---

include/coap2/pdu.h
src/coap_io_lwip.c
src/net.c
src/option.c
src/pdu.c
tests/test_pdu.c

include/coap2/pdu.h:
src/pdu.c:
tests/test_pdu.c:
Change parameter max_delta to max_opt to better reflect actual usage.
include/coap2/pdu.h:
src/pdu.c:
Remove unneeded COAP_OPT_LONG and COAP_OPT_END definitions.
Remove unused function coap_add_option_later().
src/pdu.c:
Update coap_pdu_parse_opt() to sanity check the valid lengths of all the
known options.
src/coap_io_lwip.c:
src/net.c:
Send back a RST for UDP/DTLS if malformed PDU.
src/option.c:
Clean up coap_option_filter_get() documentation.

Options: Sanity check CoAP options in the PDU

---

src/pdu.c

PR #476 added in coap_insert_option() which could be called by
coap_add_option() with with a coap_log() message set to LOG_DEBUG.
When PR #539 was merged in, this upped the logging level to LOG_WARNING which
now causes test/testdriver to report unecessary messages.
Logging level reverted to LOG_DEBUG.

coap_add_option: Fix code rebase logging level issue

---

src/coap_gnutls.c

Reduce the level of reporting of Close notify alerts for default logging levels.

coap_gnutls.c: Report Close notify at LOG_DEBUG, not LOG_WARNING

---

examples/etsi_iot_01.c
libcoap-2.map
libcoap-2.sym

Missed from commit 605f990e.
Also fixes a compiler warning now that coap_opt_length() returns uin32_t.

Update libcoap.{map|sym} files

---

HOWTO.pkcs11
Makefile.am
README.md
examples/client.c
examples/coap-server.c
include/coap2/coap_asn1_internal.h
include/coap2/coap_dtls.h
include/coap2/coap_internal.h
include/coap2/str.h
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_session.txt.in
src/coap_asn1.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_tinydtls.c

This supersedes #128
Issue raised in #500 
~~Needs TinyDTLS PR https://github.com/eclipse/tinydtls/pull/32 for TinyDTLS to interoperate with GnuTLS.~~
Currently OpenSSL and MBedTLS do not support RFC7250. See
https://en.wikipedia.org/wiki/Comparison_of_TLS_implementations#Extensions
last column.
GnuTLS >= 3.6.6 required.
~~TinyDTLS update required.~~
New option is_rpk_not_cert added to PKI setup structure which is enabled
in coap-client and coap-server by the -M option and the use of a PUBLIC KEY
instead of a CERTIFICATE in the cert file.
man/coap-client.txt.in:
man/coap-server.txt.in:
Document -M option.
man/coap-server.txt.in:
man/coap_context.txt.in:
Add in documentation for RPK.
Add in support for is_rpk_not_cert …

RPK RFC7250: Add in support

---

man/coap-client.txt.in
src/coap_session.c

When a session is created with `coap_make_session`, libcoap assigns an interface index based on the packet's interface index, and this is never updated if the interface disappears and is recreated, for example if the interface is a tunnel (VPN, etc).
The proposed fix updates the interface index in the session each time a `coap_endpoint_get_session` is called.
Fixes #559; with thanks to @mrdeep1.

Update interface index with received packet's index when getting session

---

TODO
examples/client.c
examples/coap-server.c
include/coap2/net.h
include/coap2/resource.h
include/coap2/uri.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_cache.txt.in
man/coap_resource.txt.in
src/coap_gnutls.c
src/net.c
src/resource.c
src/uri.c

Add code to better support the Proxy-Uri: and Proxy-Scheme: CoAP Options.
Make sure that the Proxy-Uri: option is added (if set) when clearing down an
observation (fixes #112).
Check that Proxy-Uri: option has a maximum data length of 1034 bytes.
Handle user defined Proxy-Scheme: option correctly.
Update -P option to include scheme to be used when connecting to the proxy.
Add in hnd_proxy_uri() handler function. This has support for a direct or ongoing
proxy connection for the coap* protocols. The ongoing connection is set up as a
different CoAP session and is assocated with the incoming session for relaying
requests / responses.
Internal functions taken from client.c are used where appropriate.
Proxy support code has a SERVER_CAN_PROXY wrapper, …

Proxy: Update Proxy support for Proxy-Uri: CoAP option

---

include/coap2/block.h
include/coap2/coap_debug.h
include/coap2/coap_dtls.h
include/coap2/coap_event.h
include/coap2/coap_forward_decls.h
include/coap2/coap_io.h
include/coap2/coap_session.h
include/coap2/net.h
include/coap2/pdu.h
include/coap2/uri.h
src/coap_io.c
src/coap_session.c
src/net.c

Use 'coap_endpoint_t' instead of 'struct coap_endpoint_t' in library source
files where possible.
Remove unnecessary 'struct xxx_t;' forward declarations.
Remove unnecessary 'void coap_free_endpoint(coap_endpoint_t *ep);'

coap_endpoint_t: Update usage of struct coap_endpoint_t to coap_endpoint_t

---

examples/client.c
man/coap-client.txt.in

Add in -n option to add in a NL at end of receiving data - including after
re-assembling a BLOCK2 set of data.
man/coap-client.txt.in:
Document -n option.
Request raised by Issue #473.

coap-client: Add in option to add in newline after receipt of data

---

.gitignore
configure.ac
examples/client.c
examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
man/examples-code-check.c
src/coap_io.c
src/coap_tcp.c

See https://sourceforge.net/p/libcoap/mailman/message/37039434/
Works for
Computer: Windows 10 64 bit & CYGWIN_NT-10.0 x86_64
Cygwin: 3.1.5-1
OpenSSL: 1.1.1g
gcc:9.3.0
and gcc-10.2.0 + openssl1.1.1f
configure.ac:
Support cygwin build environment.  If so, set -D_CYGWIN_ENV in CFLAGS.
libtool: warning: undefined symbols not allowed in x86_64-pc-cygwin shared libraries; building static only
still to be fixed.
.gitignore:
Ignore *.exe filenames
src/coap_io.c:
define ipi_spec_dst as ipi_addr if _CYGWIN_ENV
man/examples-code-check.c:
src/coap_io.c:
src/coap_tcp.c:
Fix compiler warnings.
sizeof(socklen_t) != sizeof(size_t) [-Wsign-compare]
isdigit() etc. complain about byte size array subscripts [-Wchar-subscripts]
snprintf size …

Cygwin: Add in compiler support

---

examples/client.c
examples/coap-server.c

Add indirection to pointer when NULL terminating the 'user' variable in
cmdline_read_user().
See #568

cmdline_read_user: Fix NULL terminating code

---

examples/client.c
examples/coap-server.c
include/coap2/coap_prng.h
include/coap2/pdu.h
libcoap-2.map
libcoap-2.sym
src/coap_openssl.c
src/coap_prng.c
win32/libcoap.vcxproj

1. Since coap_add_option_later() has been removed, so remove coap_add_option_later in lib-coap-2.(map,sym) and pdu.h
2. [PRNG] need include coap_prng.c into visual studio project too, since new
functions for generating pseudo numbers replace the old macro-based
approach.
3. [PRNG] need define coap_prng() coap_prng_init() coap_set_prng() for
windows too since these function are exported in lib-coap-2.(map,sym)

Fix some compile error in windows visual studio

---

include/coap2/coap_asn1_internal.h

There is a small typo in include/coap2/coap_asn1_internal.h.
Should read `updated` rather than `udated`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, udated -> updated

---

src/coap_prng.c

PR #590 unfortunately broke the standard builds.

coap_prng.c: Fix missing coap_prng_impl function.

---

examples/coap-rd.c
examples/etsi_iot_01.c
src/async.c
src/coap_session.c
src/net.c

coap_show_pdu() reports the Message ID (mid) as a hex value prefixes by i:.
Elsewhere it is reported as an integer or unsigned making those entries
difficult to match up with the reported PDU.
src/async.c:
src/net.c:
Replace tid=%d, message %d and transaction %d with mid=0x%x for clarity.

message id: Report everywhere the hex value for consistency

---

configure.ac
examples/client.c
examples/coap-rd.c
examples/coap-server.c
include/coap2/coap_dtls.h
include/coap2/net.h
man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_session.txt.in
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/net.c

The use of the verify_peer_cert and require_peer_cert variables in the
coap_dtls_pki_t structure was giving inconsistent results across all the
TLS libraries.  This primarily was down to the large numbers of options
available to control the TLS handshakes in OpenSSL compared to the limited
control available to mbedTLS port which followed later. require_peer_cert is
not easy to control in mbedTLS as it is an implicit configuration based on how
other, not always related, items were configured.
require_peer_cert was used by the server to control whether the client could
use anonymous certificates or not.  This is now controlled by verify_peer_cert.
require_peer_cert variable has been replaced with check_common_ca, so that
the OpenSSL functionality can continue, but enable GnuTLS / mbedTLS to …

PKI: Make (D)TLS operation consistent across all TLS libraries

---

LICENSE
README.md
include/coap2/coap_dtls.h
man/coap_encryption.txt.in
man/coap_tls_library.txt.in
src/coap_debug.c
src/coap_mbedtls.c

LICENSE:
README.md:
man/coap_tls_library.txt.in:
Replace MbedTLS and mbedTLS with "Mbed TLS".

Mbed TLS: Update MbedTLS and mbedTLS to Mbed TLS to reflect brand name

---

include/coap2/coap_asn1_internal.h
include/coap2/coap_cache.h
include/coap2/coap_cache_internal.h
include/coap2/coap_dtls.h
include/coap2/coap_event.h
include/coap2/coap_session_internal.h
include/coap2/coap_subscribe_internal.h
include/coap2/coap_tcp_internal.h
include/coap2/encode.h
include/coap2/net.h
include/coap2/option.h
include/coap2/str.h
man/coap_cache.txt.in
man/coap_handler.txt.in
man/coap_keepalive.txt.in
man/coap_observe.txt.in
man/coap_string.txt.in

Make documentation more consistent across doxygen output.
Add in caching module.
Add in encoding/decoding module.
Add in application i/o internal module.
Move deprecated items out of respective modules.

doxygen: Tidy up comments and add in missing modules

---

configure.ac
m4/ac_check_cryptolibs.m4
src/coap_mbedtls.c

configure.ac:
Add in explicit library version checking as .pc file is not available.
m4/ac_check_cryptolibs.m4:
Add in AX_CHECK_MBEDTLS_VERSION for checking version compatibility.
configure.ac:
Correct brand name to Mbed TLS.
Helps to solve issues like #594

configure.ac: Determine Mbed TLS library version for validity

---

src/net.c
src/resource.c

src/net.c:
Call coap_delete_all_resources() (which may send a CON observe bumping a
session ref count) before coap_delete_all() to remove any CON transmissions
that are still in flight in cop_free_context().
Delete observer if GET handler does not return a 2.xx code.

Observe: Fix coap_free_context() assert when active observe

---

src/coap_session.c

coap_session_disconnected() does not call the nack handler for any outstanding
CON requests when called with COAP_NACK_ICMP_ISSUE.
Call the nack handler if coap_session_disconnected is called with
COAP_NACK_ICMP_ISSUE.

ICMP reporting: Call nack handler when ICMP unreachable is received

---

include/coap2/async.h
src/coap_session.c
src/net.c
src/resource.c

As RFC7641 is now fully supported, these code segments should always be
compiled in and WITHOUT_OBSERVE wrappers are no longer required.
src/net.c:
Remove WITHOUT_OBSERVE wrappers.
include/coap2/async.h:
Correct definition for coap_async_state_t and remove references for
supporting observing as this is no longer supported.

Observe: Remove WITHOUT_OBSERVE conditional statements in the library.

---

Makefile.am
examples/coap-rd.c
examples/coap-server.c
examples/contiki/server.c
examples/etsi_iot_01.c
include/coap2/block.h
include/coap2/coap_block_internal.h
include/coap2/coap_forward_decls.h
include/coap2/coap_internal.h
include/coap2/coap_resource_internal.h
include/coap2/coap_subscribe_internal.h
include/coap2/net.h
include/coap2/resource.h
include/coap2/subscribe.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap_attribute.txt.in
man/coap_observe.txt.in
man/coap_resource.txt.in
src/resource.c
tests/test_wellknown.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Create a new include/coap2/coap_resource_internal.h to hold all the information
not available to applications.
Makefile.am:
Include coap_resource_internal.h in EXTRA_DIST.
Remove functions no longer visible from CTAGS_IGNORE.
examples/contiki/server.c:
tests/test_wellknown.c
Replace direct access to coap_resource_t variables with functions as
appropriate.
include/coap2/resource.h:
include/coap2/subscribe.h:
include/coap2/coap_resource_internal.h: (New)
include/coap2/coap_subscribe_internal.h:
Move coap_resource_t, coap_addr_t, non API #defines and non API functions from
resource.h into coap_resource_internal.h, coap_subscribe_internal.h and
subscribe.h.
Replace inline functions accessing coap_resource_t with actual function
definitions.
Add new …

coap_resource_t: Obfuscate coap_resource_t from applications.

---

.github/workflows/main.yml
README.md
examples/etsi_iot_01.c
examples/tiny.c
scripts/github_dist.sh

.github/workflows/main.yml:
Do a 'make check' for matrix builds.
Move documentation into separate job to reduce matrix build times
Add in CMake job.
Add in distribution job.
scripts/github_dist.sh:
Do the distribution checks using a script.
examples/tiny.c:
Fix include coap.h directory in old examples.
README.md:
Update status badges to get only the branch actions and remove CMake status badge.

workflow: Add in distribution and CMake checks

---

examples/coap-server.c
examples/etsi_iot_01.c
include/coap2/net.h
include/coap2/option.h
include/coap2/pdu.h
src/block.c
src/net.c
src/option.c
src/pdu.c
src/uri.c
tests/test_error_response.c
tests/test_options.c

Update coap_opt_filter_t to be a structure rather than a 16bit array that is
aliased with the real structure format.
Update code to use pointers where appropriate.

coap_opt_filter_t: Make it a proper structure

---

src/pdu.c

Just make write_char() a statc function.

pdu.c: Remove inline expansion warnings for write_char()

---

examples/client.c
examples/coap-server.c
include/coap2/net.h
man/coap_handler.txt.in
src/net.c

In handle_response() the ACK is sent before calling ctx->response_handler() so
if the response_handler() wants to send RST the server ignores it as the ACK
has already been received.
By updating coap_response_handler_t to return a value, this can be used to
send the ACK (return of COAP_RESPONSE_OK) or a RST (return of COAP_RESPONSE_FAIL) 
after ctx->response_handler() is called.
man/coap_handler.txt.in:
Create a new enum coap_response_t for use as the return value for 
coap_response_handler_t.
Update coap_response_handler_t and associated documentation.
src/net.c:
Send CoAP ACK or RST depending on return value of ctx->response_handler().
Update message_handler() to use the new coap_response_handler_t return values
(coap_response_t).
In part …

net.c: Delay sending ACK until after response_handler() is called

---

examples/coap-server.c
src/net.c

Merging #552 and #554 into develop caused Observe CON 2.05 initial block
response not to get an ACK from the client and so the Observe response kept
getting re-transmitted and caused other CON traffic to get queued up.
Troubleshooting highlighted an issue when a PUT/POST was updating the contents
of a resource and an Observe was active sending many payloads in a body.
src/net.c:
Make sure that an ACK is sent (if appropriate) when working with a block based
response.
Give dynamic data associated with a resource a reference count, and only free
off the data when the reference count has dropped to 0.

net.c: Fix side effect from merging 2 PRs

---

.github/workflows/main.yml
CMakeLists.txt
examples/lwip/Makefile
examples/tiny.c
include/coap2/encode.h
man/examples-code-check.c

CMakeLists.txt:
Add in missing file.
configure.ac:
Add in -Werror option so warnings are easily caught.
examples/tiny.c:
include/coap2/encode.h:
Fix COAP_PSEUDOFP_ENCODE_8_4_DOWN 'ls' ordering complaint.
man/examples-code-check.c:
Fix compile warning, allow 'Unused but set variables' in examples and set
-Werror when compling the examples.
examples/lwip/Makefile:
Add in compilation option -Wno-address-of-packed-member to remove warnings.

Ubuntu 20.4: Fix builds as Ubuntu 20.4 will be used by github workflows

---

src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_openssl.c

If cert_chain_verify_depth is 0 and cert_chain_validation is set in
coap_dtls_pki_t, then a Cert + its signing CA should be valid (no intermediary
CAs).
Correct set and check cert_chain_verify_depth.
Fix building on openssl-1.1.0

cert_chain_verify_depth: Handle value of 0

---

examples/coap-client.c
examples/coap-server.c
include/coap2/coap_block_internal.h
include/coap2/coap_prng.h
include/coap2/coap_session.h
include/coap2/encode.h
include/coap2/pdu.h
src/block.c
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_prng.c
src/encode.c
src/net.c
src/pdu.c
win32/coap-client/coap-client.vcxproj

Change some of the types of variables, and cast change sizes where known to
be safe.
There still are some C4116 warning and a couple of C4090 warning which are OK,
so disabled by a #pragma.

variables: Remove size changing warnings when using Visual Studio

---

examples/coap-server.c
man/coap-server.txt.in
man/coap_handler.txt.in
src/block.c
src/net.c

Correctly track the tokens so that the token that application sees in the
response is the same token as used in the initial request.
Update coap-server so that response data can be sent back to echo the data
that was in the request.
Fixes
CID 1502431
CID 1502428
CID 1502422

RFC7959: Handle both Block1 and Block2 for same request/response

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
examples/tiny.c
include/coap2/libcoap.h
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/mem.c
src/resource.c
tests/testdriver.c

Remove the UNUSED and UNUSED_PARAM definitions and use a single definition
of COAP_UNUSED as defined in libcoap.h
Replace all UNUSED / UNUSED_PARAM usages with COAP_UNUSED.

COAP_UNUSED: Remove UNUSED and UNUSED_PARAM and use COAP_UNUSED instead

---

man/examples-code-check.c
src/coap_tinydtls.c
src/pdu.c
tests/oss-fuzz/pdu_parse_target.c
win32/libcoap.vcxproj
win32/testdriver/testdriver.vcxproj

Replace UNUSED with COAP_UNUSED that got missed from a merge.
man/examples-code-check.c:
src/pdu.c:
tests/oss-fuzz/pdu_parse_target.c:
Fix trailing white space.
win32/libcoap.vcxproj:
win32/testdriver/testdriver.vcxproj:
Correct include/coap2 paths.

General: Fix minor issues

---

include/coap2/coap_block_internal.h
src/block.c
src/net.c
src/resource.c

If the response code was set after calling coap_add_data_large_response(),
the continuing blocks were sent with code 0.00.
Now check following call to response handler that the correct code is held
within the lg_xmit information.

Block2: Fix ordering issue when calling coap_add_data_large_response()

---

include/coap2/coap_io.h
include/coap2/coap_session.h
src/coap_io.c
src/coap_session.c
src/net.c

The first block response is unicast, and the client requests the further blocks
using unicast.  https://tools.ietf.org/html/rfc7959#section-2.8
However, the hash for the server lookup of incoming data is based on
coap_addr_tuple_t which includes the local address - which changes between
receipt of mcast and unicast requests.  This causes 2 sessions to be set up,
and the subsequent request/responses are treated as individual block random
access causing mismatch of information by the client.
Fix is to hash only on the remote address (IP + port) and local port for
servers.

mcast block2: Support mcast request with block2 responses

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
examples/tiny.c
include/coap2/async.h
include/coap2/coap_block_internal.h
include/coap2/coap_session.h
include/coap2/coap_subscribe_internal.h
include/coap2/net.h
include/coap2/pdu.h
libcoap-2.map
libcoap-2.sym
man/coap_block.txt.in
man/coap_handler.txt.in
man/coap_pdu_setup.txt.in
man/examples-code-check.c
src/async.c
src/block.c
src/coap_cache.c
src/coap_debug.c
src/coap_io.c
src/coap_session.c
src/net.c
src/pdu.c
src/resource.c
tests/test_error_response.c
tests/test_pdu.c
tests/test_wellknown.c

CoAP transaction id was formerly defined as a hash of the remote address and
message id of the CoAP PDU.  It now only refers to, and is used as, the
message id.
Replace occurrences of 'transaction id' with 'message id' to reflect naming in
RFC7252.
Correct the definition of coap_tid_t to what it actually represents.
Replace occurrences of coap_tid_t with coap_mid_t.
Replace uses of tid with mid
Remove unused function coap_find_transaction().

message id: clean up documentation usage of transaction which is message id

---

src/coap_debug.c
src/coap_gnutls.c

Increase available buffer space.
src/coap_gnutls.c
Do not access NULL pointer offset.

nits: Fix runtime warnings

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c

Examples: Output runtime libcoap version in usage()

---

include/coap2/pdu.h

Doxygen comment only, but allow COAP_INVALID_TID to still be used.

COAP_INVALID_TID: Inform this is deprecated and to use COAP_INVALID_MID

---

src/net.c

An empty response ACK is ignored if there was a request on the Send-Q.
However if there was a subsequent duplicate ACK this would then fall through
to the general handling logic in coap_dispatch(), and would trigger the ping
handler (if set) and send a RST (if not mcast) which is not correct.
Correct a change added in by #554 so that all empty response ACKs are ignored.

net.c: Handle duplicate empty ACK

---

man/coap_attribute.txt.in
man/coap_keepalive.txt.in
man/coap_recovery.txt.in
man/coap_session.txt.in
man/coap_string.txt.in
man/examples-code-check.c

Correct man pages as appropriate to line up with the header files.
If there were no EXAMPLES, previously this was not caught.

man: Extra checks on function definitions

---

Makefile.am
configure.ac
examples/coap-server.c
examples/etsi_iot_01.c
include/coap2/async.h
include/coap2/coap_async_internal.h
include/coap2/coap_forward_decls.h
include/coap2/coap_internal.h
include/coap2/coap_net_internal.h
libcoap-2.map
libcoap-2.sym
man/Makefile.am
man/coap_async.txt.in
src/async.c
src/coap_io.c
src/net.c

Move coap_async_state_t to coap_async_internal.h and rename to coap_async_t
as it no longer has any state.
Refactor the async logic to simplify usage and provide libcoap based delay
functionality support for request/response traffic such as multicast.  Let
libcoap decide when the delayed response is to be sent.
Move internal async based function definitions to coap_async_internal.h.
Replace most references to "struct coap_async_state_t" with
"coap_async_t".
Provide new functions to allow applications to access parts of
coap_async_t as appropriate.
Update examples to use these new access functions where appropriate.
Add in new man page.

coap_async_state_t: Obfuscate coap_async_state_t for applications

---

examples/coap-server.c
examples/etsi_iot_01.c
include/coap2/async.h
include/coap2/coap_session.h
man/coap_async.txt.in
src/async.c
src/net.c

See https://tools.ietf.org/html/rfc7252#section-8.2
Also updated coap_find_async() to search on token instead of mid as
mid is not used in reliable transports.

Multicast: Add in response delay

---

include/coap2/coap_prng.h
src/async.c

There still is a #warning for inet_ntop().

lwip: Fix compiler warnings

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/contiki/server.c
examples/etsi_iot_01.c
examples/lwip/server-coap.c
include/coap3/async.h
include/coap3/block.h
include/coap3/coap_block_internal.h
include/coap3/coap_event.h
include/coap3/net.h
include/coap3/resource.h
man/coap_async.txt.in
man/coap_block.txt.in
man/coap_handler.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in
man/coap_resource.txt.in
src/async.c
src/block.c
src/coap_session.c
src/net.c
src/resource.c

Also remove the unneeded parameters which can easily be derived - e.g context
and token.
This is a last opportunity to get these call-back handlers simplified and generally tidied up.

handlers: Make parameters const where appropriate

---

CMakeLists.txt
doc/Makefile.am

The man pages are still not built - otherwise all the doxygen documentation 
is built.
Add back in missing "Bug List" to the Makefile version which is there in
the cmake version.
Fixes #652

cmake: Fix missing directories error

---

CMakeLists.txt

Prevents TinyDTLS includes from being passed into the interface variable when ENABLE_DTLS is OFF but USE_VENDORED_TINYDTLS is ON.

CMakeLists.txt: Fix interface export when DTLS is off

---

include/coap3/coap_session.h
man/coap_recovery.txt.in
src/coap_session.c
tests/test_session.c

coap_session.c: Correct coap_session_get_max_retransmit() name

---

include/coap3/net.h
src/net.c

Now that coap_method_handler_t passes in the request PDU as const, make
functions that have request PDUs as a parameter const for that parameter.

net.h: Make request PDUs const in functions

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c

Increase scratch buffer size (needed for Mbed TLS)

examples: Fix truncated usage() output

---

src/coap_tinydtls.c

Remove the initial size of the ASN1 information

coap_tinydtls.c: Fix ASN1 when calling validate_cn_call_back

---

Makefile.am
configure.ac
doc/Makefile.am

Include README and COPYING as well, so that they can be a part of a library
distribution.
Make this optional with ./configure --enable-license-install
which is enabled by default.

LICENSE: Install in documentation root (--docdir)

---

HOWTO.dual.softhsm2
HOWTO.pkcs11
src/coap_openssl.c

For OpenSSL, correct typo in src/coap_openssl.c
For GnuTLS, make sure that the PKCS11 CA Certificate is trusted.
Updated HOWTO.pkcs11 for how to do this. Unfortunatately, this cannot be
done using pkcs11-tool.
The coap-server -n option (don't check peer) is no longer a requirement, so
removed from the HOWTO.

PKCS11: Fix -C ca option

---

examples/coap-client.c
examples/coap-server.c
src/coap_gnutls.c

Implement CN and SNI call-back checks for GnuTLS.  The validate_cn_call_back
function provides "RPK" for the common name and the ASN1 of the peers
certificate.
Fix the provided ASN1 when using TinyDTLS. TinyDTLS does not support SNI.
Update coap-server and coap-client to enable validate_cn_call_back and
validate_sni_call_back for RPK.

RPK: Support verification of peer certificate

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
include/coap3/coap_debug.h
libcoap-3.map
libcoap-3.sym
man/coap_tls_library.txt.in
src/coap_debug.c

Added new function coap_string_tls_support() for outputting what key types the
TLS library supports to remove duplicated code out of the examples.

TLS Support: Move common TLS support descriptions into libcoap

---

examples/Makefile.am
examples/coap-rd.c

Add rd_t information as user data to the resource (which has hashed lookup)
rather than maintaining a separate hash within coap-rd.
Fix calls to coap_resource_init() and coap_add_attr() where proper
coap_str_const_t * were not being passed in that were safe to free off.
Bringing coap-rd up to the latest draft-ietf-core-resource-directory is to be
done separately.

coap-rd: Remove requirement for uthash.h

---

examples/coap-server.c
include/coap3/coap_cache.h
include/coap3/coap_subscribe_internal.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_cache.txt.in
man/coap_observe.txt.in
src/block.c
src/coap_cache.c
src/net.c
src/resource.c

The original requesting PDU is now kept with the Observe request along with
its data and used whenever an additional response needs to be generated.
Abstracted information from the requesting PDU is no longer kept in
coap_subscription_t as it can be obtained from the kept PDU.
No longer any need to check for request PDU in request handlers as it is now
always provided.
coap_resource_notify_observers() now ignores the query parameter, as a
cache_key is now used for request matching.
Add in hnd_get_fetch_time() to coap-server for testing.

Observe: Support FETCH with data for triggered responses

---

src/pdu.c
tests/test_pdu.c

Handle correctly the case when inserting before the last option and the last
option has a large delta and size that takes it over 5 bytes. Correctly
define the remainder of option space when calling coap_opt_parse().

pdu.c: Fix coap_insert_option()

---

src/coap_gnutls.c

Include {} for if statement.
Issue introduced in c987bee

coap_gnutls.c: Fix if typo causing certificate not to be checked

---

src/coap_gnutls.c

Make sure that `san_or_cn` is freed off before returning from
cert_verify_gnutls().

coap_gnutls.c: Fix memory leak in cert_verify_gnutls()

---

include/coap3/coap_net_internal.h
src/net.c

'unknown' is updated by coap_option_check_critical if there is a critical
option, but as it is not passed in by reference, any caller does not see
any change to 'unknown'.
Pass in 'unknown' by reference.
Issue got missed in change e2e7830

net.c: coap_option_check_critical() not updating 'unknown' by ref

---

.gitignore
ChangeLog
Makefile.am
configure.ac
doc/upgrade_4.2.1_4.3.0.txt
examples/Makefile.am
man/Makefile.am
man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in

If --enable-add-default-names is set (the default), then the installed default
libraries and installed default example executables will point to the
appropriate object that has the (D)TLS library type in the name.  E.g.
libcoap-3.so -> libcoap-3-openssl.so
coap-client -> coap-client-openssl
If --enable-add-default-names is not set, then this will not happen.
As well as the libraries, the example binaries are now created with the (D)TLS
library extension in all cases.

configure.ac: Add in --enable-add-default-names option

---

doc/upgrade_4.2.1_4.3.0.txt
examples/coap-client.c
examples/coap-server.c
include/coap3/block.h
include/coap3/coap_net_internal.h
include/coap3/net.h
include/coap3/pdu.h
libcoap-3.map
libcoap-3.sym
man/coap_block.txt.in
man/coap_observe.txt.in
src/block.c
src/coap_session.c
src/net.c
src/resource.c

As it is not that intuitive when to use coap_send() or coap_send_large()
in applications, rename libcoap usage of coap_send() to coap_send_internal()
and then all usages of coap_send_large() to coap_send() so that only
coap_send() is required in applications.
Documentation updated accordingly.

coap_send(): Consolidate coap_send() and coap_send_large() for applications

---

man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in

Document where to raise an issue for the examples inline with the other man
pages.

man pages: Indicate where to raise issues

---

man/coap_encryption.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_io.txt.in
man/coap_observe.txt.in
man/coap_pdu_setup.txt.in

Use the updated functions that cause libcoap to do all of the
RFC7959 work in the man examples.

man pages: Update to use the coap_block(3) functions

---

examples/Makefile.am

For example (when building OpenSSL variant), coap-client and
coap-client-openssl are identically built and debug information is being
abstracted, it complains that the two binaries are identical.
Make coap-server, coap-client and coap-rd non-installable, (they still need
to be built in the examples directory, so cannot use check_PROGRAMS) and then
soft-link them as appropriate in the target $(bindir).

examples: Fix RPM Package Manager complaining about duplicate objects

---

doc/upgrade_4.2.1_4.3.0.txt
man/coap_async.txt.in
src/async.c
src/net.c

Correct some parameters for the dummy coap_async_*() functions.
Update some documentation for clarity.

async: Fix building with './configure --disable-async'

---

CMakeLists.txt

I had to change this in CMakeList.txt to be able to do cmake compilation with -DDTLS_BACKEND=mbedtls option

Fix condition for MBEDTLS_INCLUDE_DIRS

---

src/coap_mbedtls.c

Also fix a warning when DTLS is not enabled in ESP-IDF.
See #700

coap_mbedtls.c: Allow ESP-IDF systems to be compiled without PSK support

---

include/coap3/resource.h
man/coap_resource.txt.in

Remind users in the documentation that the full path defining the resource in
the uri_path parameter does not normally need a leading '/'.
E.g. It should be "full/path/for/resource", not "/full/path/for/resource".
See #714

coap_resource_init: Leading '/' is not required for uri_path

---

src/coap_gnutls.c

Old version of GnuTLS, used in Raspbian,  contains no definition
for GNUTLS_CRT_RAW. This patch fixes build error:
`error: ‘GNUTLS_CRT_RAW’ undeclared`
Signed-off-by: Eug Krashtan <eug.krashtan@gmail.com>

gnutls:  GNUTLS_CRT_RAW not defined

---

include/coap3/coap_block_internal.h
src/block.c
src/coap_io.c

Following transmission of a large body by a server using BLOCK2,
session->lg_xmit is not getting released. It does get released when the session
is freed off.
A client doing transmission of a large body idoes release session->lg_xmit.
Timeout lg_xmit after 4 * ACK_TIMEOUT seconds after final block is transmitted.

RFC7959: session->lg_xmit not being released for a server

---

src/async.c
src/net.c

There currently are 2 requirements for async (delayed response)
1. Application support to delay separate response while doing other processing
2. Delay any response for random time if receiving multicast request
The MID is used by the client to match initial response (empty ack or
piggy-backed response).  Any subsequent response (usually the separate
response or unsolicited Observe) should have a different MID as generated by
the server (and are matched using the token).
Fix is to move the tracking of the client MID from coap_register_async()
(so 1. is supported correctly) into handle_request() for multicast requests
(so that 2. continues to be supported correctly).
coap_check_async() will then call the appropriate request handler with the 
appropriate MID (application different, …

async: Correct MID usage in response

---

examples/coap-client.c
examples/coap-server.c
include/coap3/coap_event.h

examples/coap-client.c:
Explicitly define each enum case to remove complier warnings.
Abstracted out of #611.

coap_event.h: Make coap_event_t an enum

---

CMakeLists.txt
cmake_coap_config.h.in

Set -D__APPLE_USE_RFC_3542=1 if APPLE
At same time do not install uthash.h.
See Issue #730

CMakeLists.txt: Fix macOS builds by checking for if_nametoindex support

---

README.md
doc/main.md
src/coap_mbedtls.c

Add in support for when TLS is enabled, but DTLS is not enabled (ESP-IDF)

coap_mbedtls.c: Add in TLS support

---

src/coap_debug.c
src/coap_session.c
src/net.c

Add in support for when TLS is enabled, but DTLS is not enabled, specific
to Mbed TLS configurations (ESP-IDF).

DTLS/TLS: Support TLS when DTLS is not enabled

---

examples/coap-client.c
man/coap-client.txt.in

Demonstrate Token usage for tracking the multiple requests so
that it is easy to see how to extend this for bespoke applications.

coap-client: Add in support for generating multiple requests

---

include/coap3/coap_debug.h

The syslog LOG_ definitions are defined in <syslog.h> and can be defined in
coap_debug.h (wrapped by a HAVE_SYSLOG_H wrapper to prevent duplicaton).
However, the coding order of
include <coap3/coap.h>
include <stdio.h
works, but
include <stdio.h
include <coap3/coap.h>
but fails if the application build environment does not define HAVE_SYSLOG_H
(as is the case of the examples in the examples/ directory).
The former "just" happens to work as the values of the variables are the same.
This fix is to remove the coap_log_t enum and replace it by simple #define
if LOG_ALERT is not already defined.
Make coap_log_t int to remove Visual Studio compile warnings.
See #749

coap_debug.h: Allow <syslog.h> to be included before and after <coap3/coap.h>

---

include/coap3/coap_dtls_internal.h
include/coap3/coap_net_internal.h
include/coap3/coap_session_internal.h
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c

Make the retrieval of  PSK hint / key / identity items simpler, remove
duplicate coding, remove a set of memcpy() and handle all these internally 
as coap_bin_const_t.
This removes the need for libcoap internally to allocate (potentially
limited) holding space for these items on the stack.
The respective (D)TLS interface modules then convert these items into
the format required for the underlying (D)TLS libraries.
If the underlying (D)TLS library indicates that there is insufficient
space for an item (defined by a max_len type parameter), then the item
is truncated to that size and a warning issued about the provided item
being too large for the underlying (D)TLS library.
The item access functions are now standalone, not indexed through
coap_context_t.
Addresses #708.

PSK: Make PSK hint / key / identity retrieval simpler

---

include/coap3/coap_block_internal.h
src/block.c
src/net.c
src/resource.c

Simplify token handling by having a state token for Block1 requests where the
top 16 bits are an incrementing request counter and the bottom 48 bits are the
base token.
Re-order struct coap_lg_crcv_t to reduce data space usage.
Track request method for Block2 requests.
Make coap_add_data_large_internal() a static function.
Abstracted from PR #611

RFC7959: Handle both client and server initiating requests

---

examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
include/coap3/resource.h
libcoap-3.map
libcoap-3.sym
man/coap_attribute.txt.in
man/coap_block.txt.in
man/coap_handler.txt.in
man/coap_observe.txt.in
man/coap_resource.txt.in
src/net.c
src/resource.c

Add in additional handler coap_register_request_handler() in addition to
coap_register_handler() but now only refer to and use
coap_register_request_handler() to aid readability.

handlers: Clarify which handlers are client only, server only or both

---

src/net.c

The interface description of coap_send_internal says that COAP_INVALID_MID is returned  in the case of errors. Presently, it, however, returns `(coap_mid_t)bytes_written` in a special case. Accidentally, bytes_written == -1 == COAP_INVALID_MID in this specific case, which is why no problems occur in practice due to this. As a cosmetic fix, this PR changes the return value to COAP_INVALID_MID.

Corrects return value in net.c#coap_send_internal

---

src/block.c
src/net.c
src/resource.c

Aids tracking issues with the libcoap block handling logic to easily
differentiate when libcoap sends a response and when app handler is called
to send a response.

request_handler: Report only when app's request handler is actually called

---

src/block.c

Allows a following request not to match cached multi-payload large response.
Fixes #793 for requests that are not specifying Block2 to define return blocking and reponses that are not all multi-payload.

block.c: Do not match large response if no Block2 option in request

---

src/coap_session.c
src/net.c

Fix the buffer start offset when writing the next part of the PDU.
Also correctly report the number of bytes actually written,
See #774

coap_write_session: Account correctly for partial TCP writes

---

examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
include/coap3/resource.h
man/coap_resource.txt.in
src/resource.c

Support deleting a resource both before and after calling
coap_delete_resource().
Make the coap_delete_resource() usage in examples less complex.
Resolves #788 
Replaces #787

resource.c: Support deleting resources that have not yet been added

---

configure.ac

Do not make it a hard error if mbedtls library exists, but the mbedtls
development environment is missing.
Just remove mbedtls support if this is the case.

configure.ac: Fix have mbedtls lib, but no mbedtls-dev issue

---

include/coap3/encode.h
man/coap_pdu_setup.txt.in

Document return value can be 0 for both being valid and returning on error.
Same is true for coap_encode_var_safe().
[Error should assert() by default]
See Issue #815

coap_pdu_setup.txt.in: Better document coap_encode_var_safe8()

---

CMakeLists.txt
Makefile.am
examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
include/coap3/coap_debug.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_logging.txt.in
src/coap_debug.c

Add new function coap_package_build() which returns "git describe --tags"
if available at library build time, else standard package version.
The value of "git describe --tags" is created at run time and passed in as
a compiler -D definition rather than let autotools update a file with
the value which may become stale in moving through git commits as well as
have the wrong value in the git repository after a commit or merge.
The alternative of Makefile updating a coap_build.h file always causes
coap_debug.o to get rebuilt even if coap_build.h is not actually changed.
Update copyright end dates for updated files.
See #798

versioning: Make current git describe available

---

include/coap3/block.h
include/coap3/coap_pdu_internal.h
include/coap3/pdu.h
src/block.c
src/coap_session.c
src/net.c
src/option.c
src/pdu.c
src/resource.c

Make coap_add_option() invalid after calling a coap_add_data*() function.
Add in internal support for adding options to PDUs that contain data with
a replacement coap_add_option_internal() function.  Call this new function
in the appropriate places in the libcoap src.
Add coap_log warnings when the application tries to build a PDU in the wrong
order and then return failure.
Update documentation re-inforcing the PDU building order.
Prevents the issue raised in Issue #811 happening without warnings.

pdu building: Enforce the application order of building a PDU

---

cmake_coap_config.h.in

Build the coap_config.h file in the same way that the make system does
without wrapping the definitions with ""
See Issue #808

cmake_coap_config.h.in: Fix definitions for when building with tinydtls

---

examples/coap-client.c
man/coap_endpoint_client.txt.in
src/coap_session.c
src/net.c

Prevent multiple coap_new_client_session*() calls that are connecting to
the same server/port being bound to the same local ip/port.
Update logging for session creation / removal to easily differentiate between
sessions that have the same 4-tuple.
Document that coap_new_endpoint() is not required in client based code.
If coap-client '-p port' but not '-a addr' is provided, fix code so that
the port is bound to.
Only remove outstanding CON requests with token matches if there is an
ACK response.
Update the logging to differentiate between the 6 occurrences where the mid
is removed.
Addresses issues raised in Issue #810.

sessions: Prevent multiple client session confusion

---

src/pdu.c

Fix off-by-one error for option delta = 269.
Correct / clarify the tests in coap_insert_option() when working out extended
option delta for inserting new option.

pdu.c: Fix coap_insert_option with delta = 269

---

.github/workflows/main.yml
scripts/msbuild.sln.cmd

The provided host for windows-latest is migrating across from
windows-2019 to windows-2022 on github.  This allows things to be built on
a windows-2022 system.

github workflow: Support windows-2022

---

man/coap_pdu_setup.txt.in

Standalone documentation split out of #786.

coap_pdu_setup.txt.in: Clarify / more make readable the pdu setup information

---

examples/coap-server.c
include/coap3/coap_net_internal.h
include/coap3/coap_pdu_internal.h
include/coap3/coap_session_internal.h
src/block.c
src/coap_session.c
src/net.c
src/pdu.c
tests/test_error_response.c

The CoAP Proxy may not know how to handle a Critical option, but if it
is safe to forward it should be able to handle this.
RFRC7252 5.4.1
Critical/elective rules apply to non-proxying endpoints.  A proxy
processes options based on Unsafe/Safe-to-Forward classes as defined
in Section 5.7.
If this is an incoming proxy type request special case any
critical options that are safe to forward.
Track ongoing sessions from an enabled proxy server so unknown critical
response options can be passed back to the originating requestor.
Update coap-server to handle Proxy-Scheme for proxying.
Update tests to use option 25 instead of 9.
Closes #825.

Proxy: Support unknown Critical but Safe-To-Forward options

---

src/block.c

Commit 9cb2f62a3 [1] has introduced library-internal handling of
Block1 and Block2 requests. To add the data to the response body the
function coap_add_data_large_internal() is used.
This change calls the function independent of a Block2 request unless
request is NULL. The response code is set to 500 if
coap_add_data_large_internal() failed.
Fixes Coverity-Id 1514379
[1] https://github.com/obgm/libcoap/commit/9cb2f62a3eef2e0aeb682615b785d4734b473bd4

block.c: Fix possible null-pointer dereference

---

src/coap_prng.c

- For targets having their hardware RNG implementation using `mbedtls_hardware_poll()`
- This change was made because, for `mbedtls-3.x`, passing an RNG function to all functions that accept an `f_rng` parameter is mandatory
- Related to #822

`coap_prng.c`: Added alternate RNG implementation

---

src/coap_mbedtls.c

Support self-signed certificates that have expired.
Correct variable ret initialization in coap_tls_read().
Catch some additional MbedTLS SSL error codes in do_mbedtls_handshake().

coap_mbedtls.c: Make TLS error recovery more rigorous

---

src/block.c

block.c: Fix data leak in coap_add_data_large_internal

---

examples/coap-client.c
man/coap-client.txt.in

This then allows any (D)TLS to be set up between sending off the requests and
better demonstrates how this can be done in user code.
Allocate separate data for each post/put PDU. (Replaces PR #768)

coap-client.c: Delay sending each request using -G by 1 second

---

configure.ac
m4/ac_check_cryptolibs.m4
src/coap_tinydtls.c

This PR modifies the autotools scripts (mostly `configure.ac`) to allow using a tinydtls version that is different from the one provided in the submodule.
To do so, set the `--with-system-tinydtls` (as well as the `--with-tinydtls`) configure script option when building.
It is also possible to override the linker and compiler flags using the `TinyDTLS_LIBS` and `TinyDTLS_CFLAGS` environment variables, analogously to the `(OpenSSL|GnuTLS)_(LIBS|CFLAGS)` environment variable for the other TLS backends.

Allow usage of a non-vendored TinyDTLS version when using autotools

---

src/coap_io.c
src/net.c

Move around some of the COAP_CONSTRAINED_STACK mutex locking to prevent
recursive locking (issue when a proxy initiates an ongoing reliable client
connection).
Code abstracted from #833.

recursive mutex: Stop recursive Mutex when doing handler callbacks

---

include/coap3/async.h
include/coap3/coap_io_internal.h
libcoap-3.map
libcoap-3.sym
man/coap_async.txt.in
man/coap_io.txt.in
src/async.c
src/coap_io.c
src/net.c
src/resource.c

Add in new function coap_async_trigger() to immediately release an async
session, rather than using coap_async_set_delay(async, 1)
Add new internal function coap_update_epoll_timer() to reduce code
duplication and use it for the async logic.
Move doing coap_io_prepare_epoll() for every epoll event to just doing it once
outside of the loop.
Fixes delay issue in #794
Update documentation.

async: Handle changes to delay when using epoll

---

src/net.c

In `net.c`, there is a place where `coap_pdu_init` is called without checking its result. This is likely to cause segmentation faults when the memory gets scarce. My fix inserts a check.

net.c: fix null pointer exception

---

examples/coap-server.c
man/coap_cache.txt.in

When using the cache logic to build up the data of a body transferred over
several blocks, the BLOCK options must be excluded when deriving the cache key.
Update documentation reminding the user of the need to do this.
See #743

Caching: Highlight requirements ignoring certain CoAP Options

---

examples/coap-client.c
examples/coap-server.c
src/coap_io.c
src/coap_mbedtls.c

The example coap-client application was setting the SIGPIPE signal to
SIG_IGN too late.
For applications that do not handle SIGPIPE, set MSG_NOSIGNAL in send() flags 
to stop SIGPIPE being generated (but send() still returns EPIPE).
Drop the logging level when a client session cannot be extablished.
Can be reproduced when server requires certificates, but client does not
provide any certificate when using coaps+tcp:// and Mbed TLS.
````
Window 1
$ coap-server -c server.pem -C ca.pem
Window 2
$ coap-client coaps+tcp://127.0.0.1
$ echo $
````

TLS SIGPIPE: Stop programs exiting with code 141 (128 + 13:SIGPIPE)

---

include/coap3/coap_dtls_internal.h
man/coap_io.txt.in
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

Two cases for not updating active sockets[] with file descriptors from a
session (non epoll code)
-   coap_retransmit() can release a session
-   coap_dtls_handle_timeout() can disconnect a session
Move the restransmit test code to before any updates to socket[].
Update coap_dtls_handle_timeout() to return a value indicating a DTLS timeout
has occurred.  At the same time move the coap_dtls_handle_timeout() checks
into the first sessions iteration loop, removing having to iterate through the
sessions twice if DTLS.

coap_io_prepare_io: Re-order function code for correctly updating sockets[]

---

include/coap3/coap_session_internal.h
src/block.c
src/coap_session.c
src/net.c

Commit 069a0786ce85ea9b847160cc93529c06bd737079 (#833) introduced the concept
of delaying PDU building until the CSM message had been received from server
so that PDUs could be correctly sized.
However, this meant that the functions coap_new_client_session*() would not
complete until the CSM was in for reliable protocols.  Some applications need
the returned session to handle / differentiate between different events.
CSM can update
session->mtu
session->csm_block_supported
session->csm_bert_rem_support
coap_client_delay_first() is now called in coap_add_data_large_request()
and coap_session_max_pdu_size() (not coap_session_max_pdu_rcv_size() as
this is for receiving PDUs).
coap_client_delay_first() has been updated to catch recursive requests as well
as using more of the common code for …

CSM: Move coap_client_delay_first() to later in code processing

---

src/coap_gnutls.c

Treat GNUTLS_E_UNEXPECTED_PACKET as a reason for DTLS closure.
To test, gnutls server and client with different PSK keys and coaps://
GNUTLS_E_UNEXPECTED_PACKET raised if alert sent by server in the
middle of the setup handshaking.

coap_gnutls.c: Handle another error in do_gnutls_handshake()

---

examples/coap-client.c
include/coap3/net.h
man/coap_pdu_setup.txt.in
src/net.c

Always delete PDUs on error before return from coap_send() (aligning with
previous documentation).
Check that the socket is still available before continuing with the PDU
transmission in coap_send().
Update documentation to be clearer on non-usage of PDU on return from
coap_send().
Trap coap_send() errors in coap-client.
Move event handlers setup code to earlier in coap-client to trap events
early on in the CoAP setup process.

coap_send: Make error checks for coap_send() more rigorous

---

src/coap_io.c

Add in tracking for EHOSTUNREACH in coap_network_read().

coap_io.c: Track ICMP Host Administravely Prohibited error

---

include/coap3/coap_resource_internal.h
include/coap3/resource.h
src/net.c
src/resource.c
tests/test_wellknown.c

This removes a lot of code duplication by creating a pseudo resource
for .well-known/core that is not included in the .well-known/core output.
In particular specific Block2 option handling is no longer required.
Updated tests which now include checking that queries work.

net.c: Update .well-known/core handling to use common logic

---

include/coap3/coap_block_internal.h
src/block.c
src/pdu.c
src/resource.c

If the response is large, it can take time to transfer over the body.  If
the server then initiates a new unsolicited response during the existing
transfer, then overflow / retry issues start to occur, compounded if multiple
unsolicited responses are triggerred during an existing transfer.
Hold back the notify of the new unsolicited response(s) until the
existing response has completed (or failed for another reason).
Other code has been tightened up incase the server or client are
not libcoap based and also exhibit this behavior, so to have a better chance
of recovery.
Fixes #758.  #740 may help here as well.

Large Observes: Prevent server sending new response if active response

---

examples/coap-client.c
examples/coap-server.c
include/coap3/coap_net_internal.h
include/coap3/net.h
include/coap3/resource.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap-server.txt.in
man/coap_endpoint_server.txt.in
man/coap_handler.txt.in
man/coap_resource.txt.in
src/net.c
src/resource.c

Add in new function coap_mcast_per_resource() to enable granularity of
handling multicast requests differently at the resource level.
The granularity is handled by how the flags variable is set up in
coap_resource_init().  These additional flags are ignored if
function coap_mcast_per_resource() has not been invoked.
Added 2 functions coap_resource_unknown_init2() and 
coap_resource_proxy_uri_init2() that support defining the mcast flags as 
per coap_resource_init().
Responses are now delayed rather than the request being delayed before being
passed to the request handler.
Update coap-server with the -r option to enable multicast on specific
resources.
Requires #858 to support multicast delays for .well-known/core requests.
Fixes #854.

mcast support: Support multicast granular to the resource level

---

README.md
doc/main.md
include/coap3/block.h
include/coap3/coap_block_internal.h
include/coap3/coap_cache.h
include/coap3/coap_event.h
include/coap3/coap_session_internal.h
include/coap3/pdu.h
man/coap.txt.in
man/coap_block.txt.in
src/block.c
src/coap_debug.c
src/coap_session.c
src/net.c
src/pdu.c

Add in support for the Echo and Request-Tag options.
A unique Request-Tag is added to any PUT/POST/FETCH request that contains
a large body.  The server is then able to differentiate between concurrent
sending of large data using the same session.
If a server responds with a 4.01 and Echo option, then the libcoap client
retransmits the request adding in the received option.
If the server responds normally with an Echo option, then the next request
from the client (added by libcoap) will contain that request option.
It is the responsibility of the server application to add in the Echo
option unless this is triggered by OSCORE.
Request-Tag code abstracted from #611 
Echo code abstracted from #764

RFC 9175:  Add in support

---

src/resource.c

When sending an unsolicited Observe message, this may trigger a
session disconnection which can remove a subscription.

resource.c: Make subscribers iteration safe in coap_notify_observers

---

examples/coap-server.c
src/net.c

As an incoming proxy request may delay its response (e.g. initiate an
ongoing connection), send back empty ACK immediately so that the
client does not timeout and re-transmit the request.
Do not process duplicated (i.e. re-transmitted) proxy requests.
Correct a couple of typos in example proxy code.

proxy: Make proxy requests separate responses

---

src/coap_mbedtls.c

- Updated the deprecated APIs with the respective alternatives
- `mbedtls_ssl_conf_min_version` => `mbedtls_ssl_conf_min_tls_version`
- Updated fields for `mbedtls_ssl_ciphersuite_t`
- `max_major_version`/`max_minor_version` => `max_tls_version`
- Added macros for backward compatibility

`coap_mbedtls.c`: Upgrade to Mbed TLS `v3.2.1`

---

include/coap3/coap_mutex.h

Both LwIP and Contike are single threaded at present, so no need for
stub mutex function warnings

mutex: Do not output mutex warnings for LwIP and Contiki

---

include/coap3/coap_block_internal.h
src/block.c

Use the Token used for the initial Observe response, not any
interim stateful tokens used for Block handling.

observe: Make sure the correct token in used for cancellation

---

src/net.c

It was possible to jump to skip_handler with added_block uninitialized.
(Found by valgrind.)

net.c: Move variable into correct block

---

include/coap3/coap_session.h
include/coap3/coap_session_internal.h
libcoap-3.map
libcoap-3.sym
man/coap_observe.txt.in
src/coap_session.c

Add in a new function coap_session_set_no_observe_cancel() to support this.
Fixes issues raised in #810 and #887

Observe: Support disabling observe cancellation on session close

---

include/coap3/coap_pdu_internal.h
src/block.c
src/pdu.c

Replace usage of hdr_size with max_hdr_size as appropriate as hdr_size
is not set until PDU is encoded. This should eliminate potential buffer
overruns.
Better checks for available space for the payload when using BlockX.
Clarify documentation.

PDU Data: Clean up internal usage of PDU data

---

coap_config.h.contiki
include/coap3/coap_subscribe_internal.h
src/coap_io.c
src/net.c
src/resource.c

Support for larger COAP_OBS_MAX_NON and COAP_OBS_MAX_FAIL definitions.
Change default for COAP_OBS_MAX_FAIL to 1 as there will already have
been MAX_RETRANSMIT(4) of the notification over a period of 93 seconds if
defaults are used.
Code and documentation clean up

Observe: Clean up server timing out after observe failures

---

src/block.c

Fix potential buffer overrun corruptions.

block.c: Correct size of allocated PDU buffer

---

doc/Makefile.am
doc/docbook.local.css

Add in a new index tag for all the functions defined within the man pages.
Highlight the occurrence of that function name in the appropriate displayed
page.
For the man pages that have been restructured to break out the individual
functions, jump to the function definition.

Doxygen: Add in individual man pages for the ease of finding the functions

---

man/Makefile.am

Update the NAME section with all of the alternative names.  All the different
files are already built.
Addresses and fixes #785.  Not all the versions of asciidoc output the warning limit.

Manual pages: Update NAME section to contain all of the alternative names

---

doc/Makefile.am
man/coap_attribute.txt.in

Fix the link for the last entry in the name list where asciidoc
converts the minus sign to an extended dash (em dash)
Remove the updating of navtree.js as it is done differently in later
versions of doxygen.
Add in the missing name entry for coap_attribute.

Doxygen: Fix missing links for later versions of asciidoc

---

.github/workflows/main.yml
CMakeLists.txt
examples/coap-client.c

Add new option WARNING_TO_ERROR for CMakeLists.txt
Includes cmake builds for Windows and macOS
[Fix coap-client S_ISDIR() duplication bug]

CMake: Force all Warnings to Errors when doing github actions

---

examples/lwip/config/lwipopts.h
src/pdu.c

Define PBUF_POOL_BUFSIZE appropriately in lwipopts.h

LwIP: Support receiving ethernet MTU sized packets

---

man/coap.txt.in

The RFC references appear without the hyperlink in the man pages, but now appear as hyperlinked in the doxygen output.
SEE ALSO updated with missing references.

coap.txt.in: Fix missing references and hyperlink RFC references

---

examples/coap-client.c

Delay exit briefly checking if there are any response packets following observe cancellation and process as appropriate.
If multiple observes are outstanding, cancelling them using CON will cause issues as NSTART limit is hit.  The server then does not know about all of the cancellations.
Also, this can allow the server to properly shutdown observe activity when blocks are used.

coap-client.c: Cleanup following observe cancellation

---

examples/coap-client.c
examples/coap-server.c
include/coap3/coap_event.h
man/coap_handler.txt.in
src/net.c

Apart from debug log messages, there is no way for a user to be notified when a message retransmission happens.
This event can be useful for diagnosing issues related to lossy networks or unresponsive CoAP servers (e.g. user can track total retransmissions as an indicator for general link quality).
Assigned event ID to 0x5002 to avoid creating a new 0x6000 event group, and because it's similar to COAP_EVENT_BAD_PACKET (0x5001).

coap_event: Add COAP_EVENT_MSG_RETRANSMITTED

---

src/block.c

It is possible that there is, say, a Block2 option already in the PDU so need to make sure ETAG option is always added in.

block.c: Make sure ETAG option gets properly added

---

.github/workflows/main.yml
examples/lwip/Makefile
examples/lwip/README
examples/lwip/client-coap.c
examples/lwip/client-coap.h
examples/lwip/client.c
examples/lwip/config/lwipopts.h
examples/lwip/config/lwippools.h
examples/lwip/server-coap.c
examples/lwip/server-coap.h
examples/lwip/server.c
include/coap3/mem.h
scripts/github_dist.sh
src/coap_debug.c
src/coap_io.c
src/coap_io_lwip.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c
src/pdu.c
src/resource.c

The dtls versions of the server and client are built as
server-dtls and client-dtls.
Add in flexible option support for server and client.  These are
a subset of the coap-server and coap-client options.

LwIP: Add in TinyDTLS support

---

src/coap_openssl.c

OpenSSL 3.0+ has removed the SSL_OP_LEGACY_SERVER_CONNECT option from the default set list meaning that a OpenSSL 3.0+ client is unable to set up a session with a TinyDTLS server.
This fix adds back in SSL_OP_LEGACY_SERVER_CONNECT to the set list of options.
This removes the message that reports the failure
"unsafe legacy renegotiation disabled"
that causes the session set up to fail.
There is debate as to whether RFC 5746 is appropriate for DTLS sessions, which is what OpenSSL 3.0+ now enforces unless 
SSL_OP_LEGACY_SERVER_CONNECT is set.
See https://github.com/eclipse/tinydtls/issues/175

coap_openssl.c: Support OpenSSL 3.0+ client talking to legacy server

---

src/net.c

If NSTART > 1, any retransmit timeouts are reported on the difference in time with an earlier entry in the transmit queue, rather than the actual delay before the node entry gets retransmitted.
This change reports on the actual delay for a node before it gets retransmitted, which more accurately records when the node will get retransmitted.
See #949.

net.c: Report the node's retransmit timeout as actual timeout

---

examples/coap-server.c
include/coap3/coap_dtls.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_tls_library.txt.in
src/coap_debug.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

As well as adding in the DTLS_PSK wrappers in the appropriate place, add in
coap_dtls_psk_is_supported(), coap_dtls_pki_is_supported(), coap_dtls_pkcs11_is_supported()
and coap_dtls_rpk_is_supported() functions to support better granularity of what
capabilities are available in the (D)TLS libraries.
Update coap_string_tls_support() to use these new functions.
Fixes #762

TinyDTLS: Support build with DTLS_PSK not defined.

---

configure.ac
examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
include/coap3/coap_debug.h
include/coap3/coap_dtls.h
man/Makefile.am
man/coap-client.txt.in
man/coap-rd.txt.in
man/coap-server.txt.in
man/coap_logging.txt.in
man/examples-code-check.c
src/coap_debug.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

Set up coap_log_t as an enum, using syslog variable names prefixed by
COAP_.
Add function coap_dtls_log() for logging information from (D)TLS libraries.
Update the log output to have a prefix of DTLS- for the logging levels to
indicate that output is from the (D)TLS library instead of the CoAP library.
(D)TLS libraries updated to be consistent in the usage of
coap_dtls_set_log_level()/coap_dtls_get_log_level().
Add in coap_log_emerg(), coap_log_alert() etc. as wrappers to reduce the line
length required for log entries.  Updating all the coap_log() functions to
no longer use syslog variants will be a part of a separate PR.
Added in the "-V" option to the examples, with an initial default of
COAP_LOG_WARN, separating out the CoAP and (D)TLS logging levels.
Note: TinyDTLS log output will be …

Logging: Make logging consistent across (D)TLS libraries

---

examples/coap-client.c
include/coap3/net.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_io.txt.in
src/block.c
src/coap_io.c
src/net.c

coap_io_pending() checks to see if there are any PDUs pending transmission, whether there are any large (block) transmissions in progress, whether there are still expected response packets(client) or expected request packets(server), and whether the client is expecting further observe responses.  If any of this is true, then it returns 1, else 0.
coap_io_pending() also invokes coap_io_process() to check that all that can be transmitted is, as well as processes any impending input packets.
This takes coap_can_exit() a step further who only checks the transmit state.
coap_handle_response_get_block() has been updated to release the current lg_crcv if all the fragmented body of a large transfer have been received.
See #947 and #494.
Documentation updated.

coap_io_pending: Add in new function to check if there is any i/o pending

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where libcoap already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>

github workflow: add CIFuzz Github action

---

.github/workflows/main.yml
CMakeLists.txt
README.md
configure.ac

Fix issues thrown up with ubuntu-latest moving to ubuntu-22.04.
clang 14+ generates dwarf-5 code which valgrind does not currently support so downgrade to output dwarf-4.
Use ./autogen.sh for tinydtls builds rather than 'autorecond --force --install'
Remove some spurios } in the workflow

github workflows: Support Ubuntu 22.04 images

---

include/coap3/coap_pdu_internal.h
src/net.c
src/pdu.c

Extend coap_option_check_critical() for repeating options that are not repeatable, so 4.02 error code can be returned.
https://www.rfc-editor.org/rfc/rfc7252#section-5.4.5
Check for option Proxy-Scheme and return 4.02 if option Uri-Host is not present.
Clear M bit for option Block2 in a request as it must be ingnored on reception. https://datatracker.ietf.org/doc/html/rfc7959#section-2.2
check_repeatable() now is coap_option_check_repeatable() (still internal).
Found when testing #970 and #971

option checking: Do further option syntax checking for incoming PDUs

---

include/coap3/coap_net_internal.h
src/coap_io.c

coap_io_process_with_fds() can lock up a mutex for a long time for stack constrained systems.
If 2 threads (in embedded system) provide client and server functionality using separate coap_context_t, then there will be random delays on the other thread while the first is waiting having called coap_io_process() or coap_io_process_with_fds().
No thread should lock up a mutex for a long time.  Moved the (mutex protected) variables into coap_context_t so there is no need to use a mutex.
See issue #845.

coap_io_process_with_fds: Move mutex protected variables into coap_context_t

---

examples/coap-client.c
include/coap3/block.h
include/coap3/coap_block_internal.h
man/coap-client.txt.in
man/coap_block.txt.in
src/block.c
src/net.c
src/resource.c

If multiple requests (apart from DELETE) are sent at the same time to
the same resource, and the responses need to make use of the Block2 option,
there is no way for the server to differentiate between which block set a
request (if there is a resource content change) is for unless a Request-Tag 
is used.
Disable this functionality by setting COAP_BLOCK_NO_PREEMPTIVE_RTAG when calling coap_context_set_block_mode().  Request-Tag will still be sent with any request that includes Block1 option.
Addresses corner case issue raised in #793, but did not make it into PR #786 to keep things simple.

request-tag: Add in support for sending Request-Tag option with every request

---

examples/coap-server.c
include/coap3/coap_block_internal.h
include/coap3/mem.h
src/block.c
src/coap_session.c
src/mem.c
src/net.c
src/resource.c

Assemble all the blocks before checking for Observe registration
or de-registration.
Track all the tokens used for the large FETCH registration and
re-use them for the de-registration as the server can elect to use
any of them when re-assembling the body for the registration Token.

FETCH Observe: Handle Observes when FETCH body is large

---

man/coap_lwip.txt.in
man/coap_uri.txt.in

The modline entries for Vim were not correct, various options get declared by a space in between, and also no special character at the end of the line are allowed.

Modeline: Correct vim modline syntax for missing files

---

src/block.c
src/coap_session.c
src/net.c
src/resource.c

Reliable code expects type to be CON and can get confused by NON.
Having random values for mid for reliable sessions makes no sense as the mid is not in the packet..
Only send out RST if non-reliable session.

Reliable: Fix usage of PDU type and mid

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/coap_list.c
examples/contiki/coap-observer.c
examples/contiki/server.c
examples/etsi_iot_01.c
examples/lwip/client-coap.c
examples/lwip/server-coap.c
man/coap_async.txt.in
man/coap_block.txt.in
man/coap_cache.txt.in
man/coap_encryption.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_handler.txt.in
man/coap_io.txt.in
man/coap_observe.txt.in
man/coap_pdu_access.txt.in
man/coap_pdu_setup.txt.in

Drop the use of syslog LOG_DEBUG etc. for coap_log() and use the coap_log_debug() etc. macros which make use of COAP_LOG_DEBUG etc.
Application examples updated, as well as the man page examples.
Continuation of work done in #891.

logging: Use new logging macros for examples and man pages

---

src/block.c
src/coap_async.c
src/coap_cache.c
src/coap_openssl.c
src/coap_tinydtls.c
src/net.c
src/resource.c
src/uri.c

The use of coap_malloc() and coap_free() does not work with environments that have their own memory managers (e.g. LwIP).
Convert coap_malloc() to coap_malloc_type(COAP_STRING,) and coap_free() to coap_free_type(COAP_STRING,) in the library.

mem: Use coap_malloc_type() and coap_free_type() in libcoap

---

src/block.c
src/coap_async.c
src/coap_cache.c
src/coap_debug.c
src/coap_gnutls.c
src/coap_io.c
src/coap_io_lwip.c
src/coap_io_riot.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_option.c
src/coap_session.c
src/coap_tcp.c
src/coap_tinydtls.c
src/mem.c
src/net.c
src/pdu.c
src/resource.c
src/str.c
src/uri.c

Drop the use of syslog LOG_DEBUG etc. for coap_log() and use the coap_log_debug() etc. macros which make use of COAP_LOG_DEBUG etc.

logging: Use the new logging macros for libcoap code

---

examples/coap-client.c
include/coap3/coap_block_internal.h
src/block.c
src/coap_session.c
src/net.c

For clients, update the stateless token used for subsequent block transmissions back to the token used for the coap_send() when reporting NACK errors.
See #949.

NACK: make sure token is correct as presented to NACK handler

---

examples/coap-client.c
examples/coap-server.c

Exit code of -1 is not defined in example man pages - use a value of 1

examples: Align exit codes with documentation

---

examples/coap-client.c
examples/coap-server.c
examples/contiki/coap-observer.c
examples/contiki/server.c
examples/etsi_iot_01.c
examples/lwip/client-coap.c
examples/lwip/server-coap.c
man/coap_logging.txt.in
src/block.c
src/coap_debug.c
src/coap_io.c
src/coap_io_riot.c
src/coap_session.c
src/net.c
src/resource.c
tests/oss-fuzz/pdu_parse_target.c
tests/test_options.c
tests/test_pdu.c

This removes the reliance of syslog definitions in libcoap by using libcoap's version.

log_levels: Replace usage of syslog LOG_ with COAP_LOG_

---

doc/Makefile.am
man/Makefile.am
man/coap.txt.in
man/coap_async.txt.in
man/coap_attribute.txt.in
man/coap_block.txt.in
man/coap_cache.txt.in
man/coap_context.txt.in
man/coap_encryption.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_handler.txt.in
man/coap_io.txt.in
man/coap_keepalive.txt.in
man/coap_logging.txt.in
man/coap_lwip.txt.in
man/coap_observe.txt.in
man/coap_pdu_access.txt.in
man/coap_pdu_setup.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/coap_string.txt.in
man/coap_tls_library.txt.in
man/coap_uri.txt.in

Provide consistency across all of the man pages as per :-
Provide missing function headers for functions.
Hyper link the function definitions.
Hyper link RFC references (except in code blocks).
Use https://rfc-editor.org/rfc/rfc.... instead of
https://tools.ietf.org/html/rfc.... for the RFC links.
Use https://rfc-editor.org/rfc/rfc.... instead of
https://datatracker.ietf.org/doc/html/rfc.... for the RFC links.

documentation: Tidy up documentation

---

examples/coap-server.c
include/coap3/coap_cache.h
include/coap3/coap_dtls_internal.h
include/coap3/coap_session.h
include/coap3/pdu.h
include/coap3/resource.h
src/block.c
src/coap_cache.c
src/coap_io_lwip.c
src/net.c
src/resource.c

Use https://rfc-editor.org/rfc/rfc.... instead of
https://tools.ietf.org/html/rfc.... for the RFC links.
Use https://rfc-editor.org/rfc/rfc.... instead of
https://datatracker.ietf.org/doc/html/rfc.... for the RFC links.

RFC links: Provide consistency for links to RFCs

---

examples/coap-client.c

If the host has not been specified in the URI, do not add in an empty Uri-Host option as that is illegal.

coap-client.c: Fix case when no host is specified in the URI

---

include/coap3/coap_resource_internal.h
src/resource.c

resource.c: Add COAP_RESOURCE_MAX_SUBSCRIBER to limit subscribers
If COAP_RESOURCE_MAX_SUBSCRIBER is > 0
coap_add_observer() now checks and returns NULL
if COAP_RESOURCE_MAX_SUBSCRIBER is exceeded.
net.c then detects this and respond.
Per RFC7641 4.1. Request:
A server that is unable or unwilling to add a new entry to the list
of observers of a resource MAY silently ignore the registration
request and process the GET request as usual.  The resulting response
MUST NOT include an Observe Option, the absence of which signals to
the client that it will not be notified of changes to the resource
and, e.g., needs to poll the resource for its state instead.
Useful for constrained systems that wants to support
observers but need to be mindful of memory usage.

resource.c: Add COAP_RESOURCE_MAX_SUBSCRIBER to limit subscribers

---

Makefile.am
include/coap3/coap_internal.h
include/coap3/coap_uri_internal.h
include/coap3/uri.h
src/coap_oscore.c
src/uri.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Remove complexity from parsing and make it easier to add in new schemes.

uri.c: Simplify coap_split_uri_sub()

---

configure.ac
man/Makefile.am
man/coap-rd.txt.in
man/coap.txt.in
man/coap_address.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_observe.txt.in
man/coap_oscore.txt.in
man/coap_uri.txt.in

Add in new coap_address(3) man page.
Tidy up endpoint documentation.
Fix other minor nits in the documentation.

documentation: Tidy up man pages

---

coap_config.h.contiki
examples/coap-client.c
examples/coap-server.c
examples/lwip/client-coap.c
examples/lwip/config/coap_config.h
examples/lwip/config/coap_config.h.in
include/coap3/coap_address.h
include/coap3/uri.h
libcoap-3.map
libcoap-3.sym
man/coap_address.txt.in
src/coap_address.c

coap_resolve_address_info() emulates getaddrinfo() but has the extensibility to support other socket types based on the address to resolve.
coap-client and coap-server updated to use this new functionality.
coap_address(3) updated to include the new functions.

coap_address.[ch]: Add coap_resolve_address_info() and coap_free_address_info()

---

examples/coap-client.c
examples/coap-server.c
examples/oscore-interop-server.c
src/coap_oscore.c

Check return from cose_encrypt0_encrypt() and correct spelling error.

oscore: Handle encrypt error return

---

CMakeLists.txt
cmake_coap_config.h.in
configure.ac
src/coap_prng.c

coap_prng.c: Remove support for rand() (CVE-2021-34430)

---

examples/coap-client.c
examples/coap-server.c
include/coap3/coap_address.h
include/coap3/uri.h
libcoap-3.map
libcoap-3.sym
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_address.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_uri.txt.in
src/coap_address.c
src/coap_debug.c
src/coap_io.c
src/coap_tcp.c
src/uri.c

Support the AF_UNIX address family for transporting CoAP internally within
an appliance.
[The format of the URI for the client to parse may get updated]
The URI prefix for a client is coap:// for datagram sockets,
coap+tcp:// for stream sockets, coaps:// for DTLS over datagram sockets
and coaps+tcp:// for TLS over stream sockets.  In otherwords, no change.
The host portion of the URI is the unix domain name with / substituted with
%2F so that the host and uri-path can be delimited.  The initial %2F 
determines that Unix Domain sockets will be used instead of IP based
sockets.
i.e. coap://%2Fsome%2Funix%2Fdomain%2Fpath/some/path
gives an unix uri-host of `%2Fsome%2Funix%2Fdomain%2Fpath` and
overall uri-path of `/some/path` when parsed.
For the server, a new -U option defines the COAP …

Unix Domain: Add in support for Unix Domains

---

src/coap_debug.c

`in_port_t` might be hidden under `_GNU_SOURCE` feature test macro, which
is not defined at the top of the file. This happens with newlib build with
Zephyr SDK and with Zephyr RTOS. As a result following build error occurs:
```
/libcoap/src/coap_debug.c: In function 'coap_print_addr':
/libcoap/src/coap_debug.c:189:3: error: unknown type name 'in_port_t'; did you mean 'io_port_t'?
189 |   in_port_t port;
|   ^~~~~~~~~
|   io_port_t
```
Workaround that issue by replacing `in_port_t` with `uint16_t`, as that is
the only place where former typedef was used.
Alternative to: #1030
Closes: #1030

debug.c: replace 'in_port_t' with 'uint16_t'

---

include/coap3/coap_mutex_internal.h
src/coap_debug.c
src/coap_mbedtls.c
src/net.c

Introduce new macro, which will be used for defining static mutex
objects, for use from COAP_CONSTRAINED_STACK enabled code. This macro
will automatically initialize mutex using platform/OS specific macro if
such exists.
Provide mutex implementation for Zephyr RTOS, so that libcoap inside Zephyr
can be used with COAP_CONSTRAINED_STACK enabled.
This PR is a minimal set of changes in-tree that allows to integrate `libcoap`
into Zephyr RTOS application. I/O, (D)TLS and time routines implementation can
be easily added out-of-tree, so that Zephyr socket layer (either UDP/TCP or
Zephyr specific DTLS/TLS) can be utilized. For reference, this work is for now
part of https://github.com/golioth/golioth-firmware-sdk/pull/76. There will be
possiblity to upstream libcoap integration with Zephyr in the …

mutex: add COAP_MUTEX_DEFINE() and support Zepyr RTOS mutex

---

src/net.c

`pdu->actual_token.length` is a `size_t`, so use `"%zu"` format specifier.
`session->max_token_size` is a `uint32_t`, so use `"%" PRIu32` format specifier.
This allows to correctly handle those in a cross platform way.

net: fix coap_log_warn() in coap_send()

---

CMakeLists.txt
Makefile.am
cmake_coap_config.h.in
coap_config.h.contiki
configure.ac
examples/lwip/Makefile
examples/lwip/config/coap_config.h
examples/lwip/config/coap_config.h.in
include/coap3/coap_dtls_internal.h
include/coap3/coap_internal.h
include/coap3/coap_io_internal.h
include/coap3/coap_net_internal.h
include/coap3/coap_netif_internal.h
include/coap3/coap_session_internal.h
src/coap_gnutls.c
src/coap_io.c
src/coap_io_contiki.c
src/coap_io_lwip.c
src/coap_io_riot.c
src/coap_mbedtls.c
src/coap_netif.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tcp.c
src/coap_tinydtls.c
src/net.c
src/resource.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Add in skeleton coap_netif.c coap_netif_internal.h files, populated with coap_netif_dgrm_read(), coap_netif_dgrm_read_ep(), and coap_netif_dgrm_write() functions that are called by the CoAP and (D)TLS code which in turn call the appropriate coap_socket_*() functions.
The coap_dtls_send() function parameters are aligned with coap_netif_dgrm_write().

netif: Create netif layer, initially provide datagram read/write

---

include/coap3/coap_io_internal.h
src/coap_io.c
src/coap_io_contiki.c
src/coap_io_lwip.c
src/coap_io_riot.c
src/coap_netif.c
src/coap_session.c

Replace coap_network_{send|read}() with coap_socket_{send|recv}().
Move coap_epoll_ctl_mod() into coap_io.c to be along with all the other epoll specific functions for consistency.

netif: Replace coap_network_{send|read}() with coap_socket_{send|recv}()

---

src/net.c

Useful when coap-client is used to send block transfers.
Without this, users have to run coap-client with `-v 7` before they can see why coap-client ends earlier than expected.
Logging at warning level to match the default log level set by coap-client source code.

coap-client: Make retransmission give up more visible

---

include/coap3/block.h
include/coap3/pdu.h

Fixes misspellings of "already" in the block and pdu header files.

block.h/pdu.h: fix misspellings of "already"

---

examples/coap-server.c
include/coap3/coap_dtls_internal.h
include/coap3/coap_io_internal.h
include/coap3/pdu.h
src/coap_dtls.c
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_netif.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/net.c
src/pdu.c

Current stack:-
Application
CoAP
CoAP-Session
DTLS
Netif
Sockets
Network Stack
Depending on the CoAP protocol, indexing functions through coap_layers_coap[] (in src/coap_io.c) will invoke the correct layer function when used at the CoAP and DTLS layers.
It is then easy to add in another protocol layer by updating coap_layers_coap[].

layers: Add in protocol layers support

---

CMakeLists.txt
Makefile.am
examples/coap-client.c
examples/coap-server.c
examples/lwip/Makefile
include/coap3/coap.h.in
include/coap3/coap.h.windows
include/coap3/coap.h.windows.in
include/coap3/coap_crypto_internal.h
include/coap3/coap_internal.h
include/coap3/coap_io.h
include/coap3/coap_pdu_internal.h
include/coap3/coap_session_internal.h
include/coap3/coap_ws.h
include/coap3/coap_ws_internal.h
libcoap-3.map
libcoap-3.sym
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/coap_ws.c
src/net.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Add in stub Websockets files.
Add in coap_crypto_hash(0 function.
Actual WebSocket support for applications will follow.

WebSockets: Add in libcoap infrastructure

---

examples/coap-server.c

Missing part of a Websockets merge.

coap-server.c: Fix scheme hint type tracking

---

src/coap_session.c

The response will never get seen as coap_session_mfree() continues to close down the socket.

coap_session.c: Make sure that lg_crcv is properly freed off

---

CMakeLists.txt
README.md
cmake_coap_config.h.in
configure.ac
doc/main.md
examples/coap-client.c
examples/coap-server.c
include/coap3/coap_event.h
include/coap3/coap_io.h
include/coap3/coap_io_internal.h
include/coap3/coap_session.h
include/coap3/coap_session_internal.h
include/coap3/coap_uri.h
include/coap3/coap_ws_internal.h
include/coap3/pdu.h
man/coap-server.txt.in
man/coap_uri.txt.in
src/coap_address.c
src/coap_debug.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_session.c
src/coap_uri.c
src/coap_ws.c
src/net.c
src/pdu.c

Follows RFC6455, as specified in RFC8323.
Make support configurable.
Add in example support.
Update other code to be aware of WebSockets as a CoAP protocol.

WebSockets: Add in support for WebSockets layer

---

include/oscore/oscore.h

Fixes a misspelling of Environment.

oscore.h: Fix misspelling of Environment

---

CMakeLists.txt
configure.ac
include/coap3/coap_debug.h
man/coap_logging.txt.in
man/coap_oscore.txt.in
src/block.c
src/coap_debug.c
src/coap_io.c
src/coap_openssl.c
src/coap_oscore.c
src/coap_session.c
src/coap_ws.c
src/net.c
src/oscore/oscore.c
src/oscore/oscore_context.c
src/pdu.c

This allows for code reduction if not all logging levels are required.
Done by defining ./configure --enable-max-logging-level=X, where X can have the value of 0 through 8 inclusive.
COAP_LOG_EMERG is always logged.
Can save up to 40k bytes.

logging: Support defining maximum logging level

---

src/coap_address.c
src/coap_uri.c

Determine whether the requested URI scheme is supported by libcoap as an additional check.

coap_uri.c: Do more libcoap functionality checking in coap_split_uri_sub()

---

CMakeLists.txt
cmake_coap_config.h.in
configure.ac
examples/coap-client.c
examples/coap-server.c
include/coap3/coap_net_internal.h
include/coap3/coap_subscribe.h
include/coap3/coap_subscribe_internal.h
include/coap3/resource.h
include/oscore/oscore_cbor.h
include/oscore/oscore_context.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_persist.txt.in
src/block.c
src/coap_oscore.c
src/coap_subscribe.c
src/net.c
src/oscore/oscore_context.c
src/pdu.c
src/resource.c

Add in optional callbacks for when observe subscriptions start and stop.
Add in optional callbacks for when the observe counter is updated (can be ratelimited) for a resource as well as track when a resource is deleted.
Add is support for new functions
coap_persist_observe() for server to add in tracked observe information.
coap_resource_set_observe_num() to update observe counter from tracked information.
coap_observe_track() to define the optional callback functions.
coap-server has -t option to track observe information (most of the code updates).
UDP sessions supported, as well as OSCORE over UDP.
Documentation updated

Persist observe: Support tracking observe information over server restarts

---

src/coap_subscribe.c
src/resource.c

In addition, make sure large (multi packet) FETCH observe information is properly restored.

Persist_OSCORE: Include nonce in the saved OSCORE information

---

include/coap3/pdu.h

As discussed earlier (#757), the Content-Format `COAP_MEDIATYPE_ANY`  now is removed from libcoap.

Remove COAP_MEDIATYPE_ANY

---

include/coap3/coap_io_internal.h
include/coap3/coap_session.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_session.txt.in
src/coap_io.c
src/coap_session.c
src/net.c

If the server is responding to a mcast request with a packet that is a part of larger body (i.e. responding with Block2 option) the requests for the missing packets have to be using unicast, which continues to be supported.
The application can determine the unicast remote address before the next coap_send() by using coap_session_get_addr_remote().
Addresses #1096.

mcast_ips: Restore mcast ip for mcast sessions for each new coap_send()

---

configure.ac

Fixes typo of websockets in configuration help string.

websockets: fix typo in configuration

---

src/block.c

Corrects combined packets re-assembly.
Thanks to Shang Zewen for reporting this issue and providing the information to reproduce it.

block.c: Handle missing / incorrect SIZE1 and SIZE2 options

---

README.md

PR #1122 [1] has updated the reference to coap.space. As this site provides a secure version but no redirect, the URI scheme is changed to https.
[1] https://github.com/obgm/libcoap/pull/1121

README.md: Update URI for coap.space to use HTTPS

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/lwip/client-coap.c
examples/lwip/server-coap.c
examples/riot/examples_libcoap_client/client-coap.c
examples/riot/examples_libcoap_server/server-coap.c
examples/riot/pkg_libcoap/Makefile
examples/tiny.c
include/coap3/coap_address.h
include/coap3/coap_forward_decls.h
include/coap3/coap_uri.h
man/Makefile.am
man/coap-client.txt.in
man/coap_address.txt.in
man/coap_logging.txt.in
man/coap_uri.txt.in
src/coap_address.c
src/coap_uri.c

This means that apps need to have no knowledge of what IP support is available.
Updates coap_uri_into_options() and coap_resolve_address_info() which have only been recently added to develop branch and are not in any previous release.

examples: Remove references to sockaddr* structures

---

src/coap_io.c

Windows uses IPPROTO_IP for IP_PKTINFO access.

coap_io.c: Handle windows version of SOL_IP definition

---

CMakeLists.txt
cmake_coap_config.h.in
coap_config.h.contiki
coap_config.h.riot
coap_config.h.riot.in
coap_config.h.windows
coap_config.h.windows.in
configure.ac

Clean up CMakeLists.txt and cmake_coap_config.h.in as well.

configure.ac: Add consistency to how coap_config.h is documented

---

man/Makefile.am
man/coap_address.txt.in
man/coap_attribute.txt.in
man/coap_block.txt.in
man/coap_cache.txt.in
man/coap_context.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
man/coap_io.txt.in
man/coap_logging.txt.in
man/coap_observe.txt.in
man/coap_oscore.txt.in
man/coap_pdu_access.txt.in
man/coap_pdu_setup.txt.in
man/coap_persist.txt.in
man/coap_recovery.txt.in
man/coap_resource.txt.in
man/coap_session.txt.in
man/coap_string.txt.in
man/coap_tls_library.txt.in
man/examples-code-check.c

Update examples-code-check.c to cross-check NAME and SYNOPSIS entries.
Update examples-code-check.c to cross-check SYNOPSIS and RETURN VALUE entries.
Make the formating style of RETURN VALUES consistent.

man: Correct man page errors

---

man/examples-code-check.c

Fixes snprintf() warning of writing into smaller buffer.

examples-code-check.c: Disable potential compile warning

---

CMakeLists.txt
cmake_coap_config.h.in
coap_config.h.riot
coap_config.h.riot.in
configure.ac
examples/lwip/Makefile
examples/lwip/config/lwippools.h
examples/riot/pkg_libcoap/Makefile.libcoap
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_mem.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/coap_ws.c
tests/test_tls.c
win32/libcoap.vcxproj

Prevents possibility of name clashes when integrating with other code / OS.

DTLS Libraries: Replace HAVE_<dtlslib> defines with COAP_WITH_<dtls_lib>

---

configure.ac
include/coap3/coap_event.h
include/coap3/coap_net.h
include/coap3/coap_session.h
include/coap3/resource.h
man/Makefile.am
man/coap_deprecated.txt.in
man/examples-code-check.c

New: man/coap_deprecated.txt.in

man: Document deprecated functions

---

include/coap3/coap_dtls_internal.h
src/coap_mbedtls.c

Requires MbedTLS 3.2.0 or later and MBEDTLS_SSL_DTLS_CONNECTION_ID defined (which is the default in later versions of MbedTLS).

coap_mbedtls.c: Add in Connection ID support (RFC9146)

---

examples/riot/Makefile
examples/riot/README

See [9920d3e2](https://github.com/RIOT-OS/RIOT/pull/19745) which introduced running objdump which will take many minutes of CPU time when running a GitHub workflow without RIOT_CI_BUILD=1 set.

RIOT: Stop objdump analyzing the examples

---

include/coap3/coap_pdu_internal.h
man/coap_logging.txt.in
src/coap_debug.c
src/coap_session.c
src/net.c
src/pdu.c

`v:1 t:xxx c:yyy i:zzzz` is shown as` v:Reliable c:yyy` or `v:WebSocket c:yyy` as appropriate.

Reliable PDUs: coap_show_pdu(): Do not show all the non-reliable headers

---

src/net.c

Fix for piggybacked response answering to request with No-Response option set.
When No-Response option is interpreted in no_response function from net.c, for piggybacked response payload is removed to send only bare ACK. That means that used_size is set to 0. This causes an error in coap_get_data_large function from pdu.c, because when used_size is 0 then variable len has incorrect (and very large) value. This causes application to crash.

Fix for piggybacked response answering request with No-Response

---

src/coap_tinydtls.c

LwIP test build uses latest tinydtls source for DTLS builds.

coap_tinydtls.c: Fix recent removal of DTLS_EVENT_RENEGOTIATE from TinyDTLS

---

include/coap3/coap_layers_internal.h
src/coap_dtls.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_net.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/coap_ws.c

Prevents issues with things such as '#define write lwip_write'.

layers: Update coap_layer_func_t function names to be prefixed with l_

---

examples/coap-client.c
examples/coap-server.c
src/coap_session.c

Try to get the PDU information from session->lg_crcv, else call NACK handler with `sent == NULL` so client understands there are network related issues.

coap_session.c: Report COAP_NACK_ICMP_ISSUE for NON to NACK handler

---

examples/lwip/Makefile

Fixes distribution build when doing a tarball installation.

lwip/Makefile: make sure correct hash is used for tinydtls with tarball build

---

configure.ac
examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/contiki/server.c
examples/etsi_iot_01.c
examples/lwip/client-coap.c
examples/lwip/server-coap.c
examples/oscore-interop-server.c
examples/riot/examples_libcoap_client/client-coap.c
examples/riot/examples_libcoap_server/server-coap.c
examples/tiny.c
include/coap3/coap_net_internal.h
man/Makefile.am
man/coap_block.txt.in
man/coap_cache.txt.in
man/coap_init.txt.in
man/coap_io.txt.in
man/coap_observe.txt.in
man/coap_persist.txt.in
src/coap_net.c

This then makes sure that all things libcoap are properly initialized before use, and coders realize they need to do this.
Note: coap_new_context() continues to make sure that coap_startup() is invoked if not done previously, but this may be too late.

coap_startup: Make coap_startup() first function call in examples

---

src/coap_oscore.c

Seen when building OSCORE code.

esp-idf: Fix compiler warning

---

src/coap_address.c

Handle implementations that do not fill in ai_socktype and hence remove any duplicate entries.

coap_resolve_address_info: Simplify conditional OS logic

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/lwip/client-coap.c
examples/lwip/server-coap.c
examples/riot/examples_libcoap_client/client-coap.c
examples/riot/examples_libcoap_server/server-coap.c
examples/riot/pkg_libcoap/Makefile
include/coap3/coap_address.h
man/coap_address.txt.in
src/coap_address.c

coap_resolve_address_info() was created post 4.3.1, so no API change going into 4.3.2.

coap_resolve_address_info: Add in support for defining WebSocket ports

---

include/coap3/coap_mutex_internal.h
src/coap_debug.c
src/coap_mbedtls.c
src/coap_net.c
src/coap_subscribe.c

Not all OS implementations properly support static initializations.

Mutexes: Clean up / simplify use of mutexes

---

man/coap-client.txt.in
man/coap_oscore.txt.in

This MR is only about two small misspelled words.
seperator -> separator
particularily -> particularly

Small typo fixes within the source for coap[-client,-oscore] man pages

---

src/coap_prng.c

Contiki-NG now has a secure PRNG, which we can use in `coap_prng.c`.

Contiki-NG: Switch to secure PRNG

---

src/coap_session.c

Copying from the multidimensional coap_layers_coap array into the coap_layers of endpoint::sock.lfunc triggers a warning from GCC v13.2.0 as the global variable has no space for the end marker COAP_PROTO_LAST:
```
src/coap_session.c: In function 'coap_new_endpoint':
src/coap_session.c:1759:3: warning: 'memcpy' offset [672, 767] is out of the bounds [0, 672] of object 'coap_layers_coap' with type 'coap_layer_func_t[7][3]' [-Warray-bounds=]
1759 |   memcpy(&ep->sock.lfunc, coap_layers_coap[proto], sizeof(ep->sock.lfunc));
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/coap3/coap_io_internal.h:21,
from ./include/coap3/coap_internal.h:109,
from src/coap_session.c:17:
./include/coap3/coap_layers_internal.h:113:26: note: …
```

coap_session.c: Fix GCC array bounds warning for memcpy

---

src/coap_block.c

Two unexact format specifiers in `coap_block.c` caused compiler errors on an embedded target. This PR fixes the issue.

coap_block.c: Use correct format specifier when logging chunk size

---

src/coap_async.c

This is a bug I encountered a while ago while ago.
LL_PREPEND was setting s as the first element in the linked list, and then memset was clearing it; resulting in any other pending async requests being lost

fix memory leak in coap_async

---

include/coap3/coap_mutex_internal.h

Changes definition of coap_mutex_t as k_mutex to sys_mutex to build properly with Zephyr.
Fixes #1219 
See https://github.com/obgm/libcoap/pull/1033 and https://github.com/obgm/libcoap/pull/1197 for more information.

Define coap_mutex_t as sys_mutex on Zephyr

---

src/coap_address.c

Adds a check to ensure IPV4 broadcast as multicast is not enabled when using Zephyr as it will break builds with Zephyr's minimal libc, which is missing ifaddr.h.
Fixes #1217

coap_address.c: do not enable IPV4 broadcast as multicast with Zephyr

---

.github/workflows/main.yml
coap_config.h.contiki
src/coap_debug.c
src/coap_time.c

This PR fixes that Contiki-NG fails to compile on macOS due to an unused function and a redefinition of `ntohs`.

Contiki-NG: Fix compilation on macOS

---

Makefile.am
include/coap3/coap_debug.h
include/coap3/coap_debug_internal.h
include/coap3/coap_internal.h
libcoap-3.map
libcoap-3.sym
man/coap_init.txt.in
src/coap_debug.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_net.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c

After calling `coap_cleanup()`, allow another call to `coap_startup()` to re-initialize the libcoap library.

coap_cleanup: Allow coap_startup() to be called after coap_cleanup()

---

.github/workflows/main.yml
src/coap_openssl.c

OpenSSL dev environment is no longer included in windows-latest builds.
Disable Windows build OpenSSL 3 deprecation warnings

workflows: Revert #1073 to add OpenSSL dev environment

---

build-env/Dockerfile.develop

Installs the package adduser where /sbin/adduser apparently has been moved.

Dockerfile.develop: Add package adduser

---

include/coap3/coap_io_internal.h
include/coap3/coap_net_internal.h
src/coap_async.c
src/coap_io.c
src/coap_io_contiki.c
src/coap_net.c
src/coap_resource.c

I noticed that retransmissions are sometimes sent only after receiving something. The reason was that no `tcpip_event` occurred after sending, which would have caused the retransmission timer to be re-scheduled. This PR fixes the issue. Besides, I added a commit that leverages Contiki-NG's `process_exit` function for simplifying the cleanup procedure in `coap_io_contiki.c`.

Contiki-NG: Fix retransmissions and simplify cleanup

---

include/coap3/coap_time.h

Calling `clock_init` is unnecessary and potentially harmful.

Contiki-NG: Remove call to clock_init as Contiki-NG already does it

---

include/coap3/coap_net.h
src/coap_net.c

Replying an RST in response to an ACK is not compliant, is it? Hence, we should sort out this case when, e.g., processing a piggybacked response.

Suppress RST when the processing of a non-empty ACK fails

---

man/coap_handler.txt.in
src/coap_block.c

sent PDU passed to a response handler is now reset to initial sent PDU (token restored, Block options removed), but some or all of original data may be missing if Block operations were needed for the request or the repsonse.
Updated documentation to reflect this.

coap_response_handler: Tidy up sent parameter

---

src/coap_oscore.c

The memory that OSCORE reserves for accommodating the `plain_pdu` may be insufficient. This is because the subsequent `add_token` containing the unmasked code also consumes one byte. In effect, `coap_pdu_resize` may become necesary.

OSCORE: Account for pseudo-token to prevent coap_pdu_resize

---

src/coap_net.c

This replaces a `memset` with `coap_option_filter_clear`.

coap_net.c: Reuse coap_option_filter_clear in coap_dispatch

---

src/coap_debug.c

Fixes https://github.com/obgm/libcoap/issues/1273

coap_debug.c: reset all globals in coap_debug_reset

---

src/coap_session.c

When use `coap-client` with -T command, the other server received inconsistent.
```
coap-client send token "aaa", the other server received "aab"
coap-client send token "obstoken", the other server received "obstokeo"
```

Fix inconsistent tokens received by other servers

---

src/coap_openssl.c

Supported by defining COAP_OPENSSL_PKCS11_ENGINE_ID value through complier / configure additional parameters which gets passed into ENGINE_by_id().
E.g.
````
$ ./configure CPPFLAGS=-DCOAP_OPENSSL_PKCS11_ENGINE_ID='\"pkcs11\"'
````

OpenSSL: Support user defined PKCS11 engine id.

---

CMakeLists.txt
LICENSE
Makefile.am
examples/lwip/Makefile
examples/lwip/client-coap.c
examples/lwip/config/lwippools.h
examples/riot/pkg_libcoap/Makefile.libcoap
include/coap3/coap_internal.h
include/coap3/coap_sha1_internal.h
src/coap_io_contiki.c
src/coap_notls.c
src/coap_sha1.c
src/coap_tcp.c
src/coap_tinydtls.c
src/coap_ws.c
win32/libcoap.vcxproj
win32/libcoap.vcxproj.filters

Use SHA1 code from RFC3174 sections 7.1 and 7.2.

WebSocket: Add support for noTLS and TinyDTLS

---

src/coap_block.c

Not applied to RFC9177 Q-Block1 missing blocks which are handled in a different way.
Follows RFC7959 Section 2.5
A server MAY
also return a 4.08 error code for any (final or non-final) Block1
transfer that is not in sequence;
To remove the requirement of an application having to do this if COAP_BLOCK_SINGLE_BODY is not set.

block.c: Report 4.08 for missing Block1 chunks of data

---

cmake_coap_config.h.in

HAVE_ entries sorted to aid future additions.

cmake_coap_config.h.in: Add missing HAVE_ definitions

---

.github/ISSUE_TEMPLATE/bug_report.md
doc/Makefile.am
examples/oscore_testcases.sh
get_config.sh
man/Makefile.am

When building libcoap, the following warning is printed many times:
```
egrep: warning: egrep is obsolescent; using grep -E
```
This is because `egrep` is [deprecated](https://git.savannah.gnu.org/gitweb/?p=grep.git;a=blobdiff;f=NEWS;h=4a62fb7ff21168ca274c7ac9dda508f9eb219190;hp=39a0903829a92c4363b9e06f8adb0d14320b3a19;hb=a9515624709865d480e3142fd959bccd1c9372d1;hpb=e87ccc7038d4f44f4601b3e8775fef09b1420dff). (deprecated in grep 2.5.3, warning since grep 3.8)
This PR replaces `egrep` with `grep -E`.

Use `grep -E` instead of deprecated `egrep`

---

include/coap3/coap_session_internal.h
src/coap_net.c
src/coap_session.c

This fixes the issue of a client not ACKing a duplicate CON message from the server.
A duplicate CON message is sent by the server if the client's ACK to the original confirmable message did not reach it.
See issue #1306 for full description.

Client fails to ACK a retransmitted CON message

---

src/coap_oscore.c

Handles comments in the OSCORE configuration that is in DOS format.
Fixes #1310.

coap_oscore.c: Fix parsing OSCORE configuration information

---

.pre-commit-config.yaml
CMakeLists.txt
src/coap_mbedtls.c
src/coap_uri.c
src/oscore/oscore_cbor.c
zephyr/CMakeLists.txt
zephyr/Kconfig
zephyr/config-mbedtls-libcoap.h
zephyr/libcoap.conf
zephyr/module.yml

zephyr/ Initial files added
Tested with
````
west build -p always -b native_posix samples/net/eth_native_posix -- -DCONF_FILE=prj.conf -DEXTRA_ZEPHYR_MODULES=//<libcoap path>/libcoap -DEXTRA_CONF_FILE=/<libcoap path>/libcoap/zephyr/libcoap.conf -DCONFIG_LIBCOAP=y
````
with `samples/net/eth_native_posix/src/main.c` updated to run a simple libcoap CoAP client.

Zephyr: Initial Zephyr integration setup

---

src/coap_io.c

coap_io.c: Cleanup timeout checking code in coap_io_process_with_fds()

---

examples/coap-client.c

Only set up Identity Hint checks (not available for (D)TLS1.3, and so forces downgrade to (D)TLS1.2) if -h option is used for the coap-client.

coap-client.c: Enable (D)TLS1.3 support for PSK

---

include/coap3/coap_mutex_internal.h
src/coap_threadsafe.c

Should fix CIDs
1583518-1583525
1583527-1583549
1583551-1583553
1583555-1583562
1583565-1583584
1583586-1583589

multithread: Re-arrange lock checks for locked callbacks

---

configure.ac

This allows the configuration of Libcoap for Expressif ESP32.
LE: I didn't do an exhaustive check related to the full support for adding a platform, but this helped me to configure Libcoap for ESP32.

ESP32: Add platform support

---

CMakeLists.txt
configure.ac
src/coap_io.c
src/coap_net.c

Support compiling QNX 7 SDK.
Replaces #1334.  Changes are identical.

QNX: Add in build support

---

src/coap_net.c

Fix generated response PDU in handle_request() to be of type CON if reliable protocol (as a lot of code assumes it to be of pseudo type CON) to stop a warning in coap_show_pdu().

coap_net.c: Response PDU not set to CON if reliable protocol

---

coap_config.h.contiki.in
coap_config.h.riot
coap_config.h.riot.in
coap_config.h.windows
coap_config.h.windows.in
configure.ac
examples/lwip/config/coap_config.h
examples/lwip/config/coap_config.h.in
src/coap_mem.c

Add in coap_config.h.contiki.in to aid versioning updates.
Make the PACKAGE_ definitions consistent.

coap_config.h*: Make the various OS coap_config.h more consistent

---

examples/coap-server.c
examples/etsi_iot_01.c
include/coap3/coap_block.h
include/coap3/coap_block_internal.h
man/coap-server.txt.in
man/coap_block.txt.in
src/coap_block.c
src/coap_net.c

Add in new COAP_BLOCK_NOT_RANDOM_BLOCK1 option for coap_context_set_block_mode(). This disables receipt of any Block1 packet (but not Q-BLock1) if the block numbers are not sequentially received starting with 0.  A 4.08 code is returned for every packet out of order and its data is ignored.
If COAP_BLOCK_SINGLE_BODY is set in coap_context_set_block_mode(), but not COAP_BLOCK_NOT_RANDOM_BLOCK1, then all Block1 packets are assembled in the correct order before passing the body up to the application.  The receive logic will timeout after MAX_TRANSMIT_WAIT (93 seconds) if there are any missing blocks, or 10 seconds if the last block is seen.
If COAP_BLOCK_SINGLE_BODY is not set in coap_context_set_block_mode(), and not COAP_BLOCK_NOT_RANDOM_BLOCK1, then the random order packets are passed up …

coap_block.c: Handle Block1 packets with random order block numbers

---

include/coap3/coap_net.h
include/coap3/coap_net_internal.h

This resolves a compilation error I encountered with OpenMote targets.

Contiki-NG: Fix compilation error "unknown type name 'fd_set'"

---

configure.ac
examples/coap-client.c
examples/coap-server.c
include/coap3/coap_dtls.h
include/coap3/coap_dtls_internal.h
include/coap3/coap_str.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap-client.txt.in
man/coap-oscore-conf.txt.in
man/coap-server.txt.in
man/coap-tls-engine-conf.txt.in
man/coap_encryption.txt.in
man/coap_tls_library.txt.in
src/coap_dtls.c
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_notls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/coap_wolfssl.c

Two new functions added
coap_tls_engine_configure()
coap_tls_engine_remove()

OpenSSL: Add in support for configuring an alternative TLS ENGINE

---

examples/coap-client.c
include/coap3/coap_block.h
include/coap3/coap_block_internal.h
include/coap3/coap_subscribe.h
src/coap_block.c
src/coap_net.c

If Observe cancellation is detected in sending pdu in coap_send(), call coap_cancel_observe() to to the necessary work.

coap_net.c: Tidy up Observe cancellation in coap_send()

---

src/coap_block.c

It is possible the server does not support / resource, but does support Q-Block - and responds with a 4.04, so Q-Block support cannot be detected.
See #1371

coap_block.c: Use /.well-known/core when testing for Q-Block Support

---

src/coap_net.c

As per https://datatracker.ietf.org/doc/html/rfc7252#section-3
Implementations of this specification MUST set this field to 1 (01 binary). Other values are reserved for future versions. Messages with unknown version numbers MUST be silently ignored.

coap_net.c: Silently drop incorrect CoAP version packets

---

include/coap3/coap_mutex_internal.h
man/Makefile.am
man/coap_context.txt.in
man/coap_locking.txt.in
man/examples-code-check.c
src/coap_block.c
src/coap_net.c
src/coap_resource.c
src/coap_subscribe.c

This is to reduce contention on the context lock when a request/response handler takes time to get / update information.

locking: Unlock context when calling request/response handlers

---

src/oscore/oscore_cbor.c

Restore missing buffer increment.

oscore_cbor.c: Fix bad scan-build fix

---

src/coap_openssl.c

Go back to using SSL_use_certificate_file().
Unexpected side effects with CA validation which needs further troubleshooting to get to root cause.

coap_openssl.c: Revert out using SSL_use_certificate_chain_file()

---

src/coap_mbedtls.c

mbedtls have made some APIs private as a result of which [coap_client](https://github.com/espressif/idf-extra-components/tree/master/coap/examples/coap_client) example fails to build with mbedtls v3.6.0
This MR adds the implementattion
```
/home/harshitmalpani/github/idf-extra-components/coap/libcoap/src/coap_mbedtls.c:1054:18: error: implicit declaration of function 'mbedtls_ssl_ciphersuite_uses_psk'; did you mean 'mbedtls_ssl_ciphersuite_get_id'? [-Werror=implicit-function-declaration]
1054 |         else if (mbedtls_ssl_ciphersuite_uses_psk(cur)) {
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                  mbedtls_ssl_ciphersuite_get_id
```
For reference: https://github.com/Mbed-TLS/mbedtls/pull/8715#issuecomment-2106347176

Fix build failures with mbedtls 3.6.0

---

src/coap_session.c

There was one place in the code, where server session was closing, but no event about that was generated. When any dynamically allocated app_data was attached to that session, it couldn't be freed properly, causing memory leaks. This PR fixes that.

Fixed missing event for server session removal

---

examples/riot/pkg_libcoap/Makefile
include/coap3/coap_resource.h
man/Makefile.am
man/coap_resource.txt.in
src/oscore/oscore_cbor.c

Add documentation for coap_get_resource_from_uri_path().
Remove duplicate coap_get_resource_from_uri_path() definition.
Better fix for scan-build issue.
Update RIOT libcoap base version.
Addresses #1383.

Nits: Tidy up code

---

include/coap3/coap_net.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_context.txt.in
man/coap_deprecated.txt.in
src/coap_net.c

I somehow missed the documented coap_set/get_app_data functions but found them while adding new coap_context_set/get_app_data functions myself. I think the prefix of the latter would better fit the scheme - like coap_session_set_data and coap_resource_set_userdata. I am fine with using the existing functions now but I thought I send the PR anyways as I already finished it and in case you see a benefit here. If you think this change is not worth the effort, I don't mind if you just close the PR. Thanks!

coap_net: additionally provide coap_context_set/get_app_data 

---

include/coap3/coap_net.h
include/coap3/coap_net_internal.h
include/coap3/coap_threadsafe_internal.h
src/coap_io.c
src/coap_io_contiki.c
src/coap_io_lwip.c
src/coap_io_riot.c
src/coap_net.c
src/coap_session.c
src/coap_threadsafe.c
tests/test_sendqueue.c

Update libcoap functions that need to be called locked with a name suffix of _locked.
Move matching functions out of coap_threadsafe.c to be coded just ahead of the newly renamed _locked function.
Properly define the _locked function in the appropriate _internal.h file for documentation, removing the #defines from coap_threadsafe_internal.h.
Work in progress for all the functions.
Remove coap_lock_* requirements for testdriver (coap_delete_node()).
Addresses issue reported in #1384.

locking: Simplify maintenance / debugging /documentation

---

src/coap_wolfssl.c

Fixes #1397 when WOLFSSL_DTLS_MTU is enabled.
`wolfSSL_dtls_set_mtu()` does correctly get called elsewhere.

coap_wolfssl.c: Fix DTLS MTU support

---

include/coap3/coap_encode.h

My compiler complained about the implicit declaration of `strncasecmp` in `coap_dtls.c`. I did not pinpoint the commit that introduced this problem. Contiki-NG did not include `strings.h` anyway.

Contiki-NG: Fix compilation error "implicit declaration of strncasecmp"

---

examples/coap-client.c
examples/coap-server.c
man/coap-client.txt.in
man/coap-server.txt.in

If the PSK is defined with a leading 0x, then the hex representation of the following bytes is converted to a binary PSK.
Fixes #1418.

Binary PSK: Add in support for examples coap-client and coap-server

---

include/coap3/coap_threadsafe_internal.h
man/coap_locking.txt.in
src/coap_threadsafe.c

Attempt to simplify locking to prevent Coverity issues being generated.

locking: app call-backs when coap_free_context() called

---

src/coap_net.c

A preprocessor guard in `coap_net.c` does not take effect since it is misspelled.

coap_net: Fix preprocessor guard

---

include/coap3/coap_net.h
include/coap3/coap_net_internal.h
include/coap3/coap_resource.h
include/coap3/coap_resource_internal.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_handler.txt.in
man/coap_resource.txt.in
man/examples-code-check.c
src/coap_net.c
src/coap_resource.c

As described in #1425, this PR makes it possible for the application to control what is returned for .well-known/core requests.

Enable application control over .well-known/core response

---

include/coap3/coap_net.h
include/coap3/coap_net_internal.h
include/coap3/coap_resource.h
include/coap3/coap_resource_internal.h
libcoap-3.map
libcoap-3.sym
man/coap_handler.txt.in
man/coap_resource.txt.in
src/coap_net.c
src/coap_resource.c

New `COAP_RESOURCE_HANDLE_WELLKNOWN_CORE `flag for `coap_resource_unknown_init2()`.

reverse-proxy: Support for .well-known/core being passed

---

include/coap3/coap_subscribe_internal.h
src/coap_block.c
src/coap_net.c
src/coap_resource.c

Handle Observe cancellation with large blocked FETCH that needs to use diffferent tokens when there is packet loss by checking the cache-key if the token is not found (Q-Block1).
Let FETCH with Q-Block1 use NON now that cache-key is getting checked if token mismatch.
Handle getting an unsolicited Observe response in the middle of sending the FETCH blocks that ultimately will be doing the Observe cancellation following re-assembly. (The unsolicited Observe token will be the same token that is used to respond to the observe cancellation).

Block1: Handle large FETCH with large blocked request and Observe

---

ChangeLog
coap_config.h.contiki
coap_config.h.riot
coap_config.h.windows
configure.ac
examples/lwip/config/coap_config.h
include/coap3/coap.h.riot
include/coap3/coap.h.windows

LIBCOAP_VERSION and LIBCOAP_PACKAGE_BASE are unchanged until 4.3.5 is released.

release 4.3.5rc1: Release candidate 1 for 4.3.5

---

examples/coap-client.c
examples/coap-server.c
examples/lwip/client-coap.c
examples/riot/examples_libcoap_client/client-coap.c
include/coap3/coap_dtls.h
man/coap_encryption.txt.in
man/coap_endpoint_client.txt.in
man/coap_endpoint_server.txt.in
src/coap_session.c

Move requirements for client to determine how to set up the SNI for
PSK/PKI encrypted communications down into libcoap. The client just
needs to indicate the host to connect to in the client_sni field of
coap_dtls_cpsk_t or coap_dtls_pki_t.
New internal function coap_sanitize_client_sni() makes sure that
the SNI sent follows RFC 6066.  As per
https://datatracker.ietf.org/doc/html/rfc6066#section-3
Literal IPv4 and IPv6 addresses are not permitted in "HostName".
all IPv4 and IPv6 addresses are dropped for the SNI, and so no SNI is
sent.  DNS hostnames will get transmitted as the SNI.

coap-client.c: Fix SNI generation

---

include/coap3/coap_block_internal.h
src/coap_block.c
src/coap_net.c

Set up lg_crcv if separate ACK response received for a coap_send() CON request to be able to handle Block2 responses.
Handle Block1 request getting back a Block2 request that has an initial separate response once the Block1 has completed by adjusting the stateless token counter.
Separate response is typical for proxy support (OSCORE previously handled)..

block: Handle separate responses that then are followed with Block2

---

examples/coap-client.c
examples/coap-rd.c
examples/coap-server.c
examples/etsi_iot_01.c
examples/etsi_testcases.sh
examples/lwip/client-coap.c
examples/riot/examples_libcoap_client/client-coap.c
examples/riot/tests_pkg_libcoap/libcoap-test.c
include/coap3/coap_uri.h
include/coap3/coap_uri_internal.h
libcoap-3.map
libcoap-3.sym
man/Makefile.am
man/coap_block.txt.in
man/coap_pdu_setup.txt.in
man/coap_uri.txt.in
src/coap_option.c
src/coap_oscore.c
src/coap_uri.c
tests/test_uri.c

Create new options coap_uri_into_optlist(), coap_path_into_optlist() and coap_query_into_optlist() to be used instead of coap_uri_into_options(), coap_split_path() and coap_split_query() functions so the requirement for a scratch buffer is not needed.
Getting the minimum size for a scratch buffer is not straight forward and potential for unexpected boundary condition errors to occurif too small.
Correct parsing and stripping out of "%2E%2E" ("..") and "%2E" (".") path segments.  ".." now removes the previous segment (if it exists).
Update documentation and unit testcases.
Update examples to use new options.

path_query parsing: Remove need to define scratch buffer

---

src/coap_uri.c

Replaces `u_char` with `uint8_t` since Contiki-NG does not define `u_char`.

Contiki-NG: Fix compilation error "unknown type name 'u_char'"

---

src/coap_debug.c

Remove obsolete quotation marks as discussed in #1460

coap-debug.c: remove quotation when printing Unix domain socket paths

---

configure.ac

Newer MbedTLS versions provide pkg-config files for easier dependency management/linking, see the release notes of versions [3.6.0](https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0) and [2.28.8](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.8).
This PR allows the autoconf build script to utilize the mbedtls pkg-config file if it exists, falling back to the previous method of finding MbedTLS if no pkg-config file was found.
Additionally, this change allows overriding `MbedTLS_CFLAGS` and `MbedTLS_LIBS`, which was previously not possible (unlike all the other DTLS libraries).

configure.ac: use MbedTLS pkg-config if available

---

src/coap_mbedtls.c

TLS1.3 is enabled by default in 3.6.0. This PR fixes the supported encryption algorithms as well as handling a new session ticket indication for coaps+tcp://.
However, if client certificates are not defined, then MbedTLS 3.6.0 fails with no certificate CA, even if the CA Cert is presented along with the Server Cert during the processing of the server certificate and fails with "SSL - No CA Chain is set, but required to operate" when coaps+tcp:// is used. See https://github.com/Mbed-TLS/mbedtls/issues/9223
Workaround (with examples/coap-client) is to set the -R options (when the -c option is not set), or to programmatically call coap_context_set_pki_root_cas);, or to use a MBedTLS version < 3.6.0.

coap-mbedtls.c: Support 3.6.0 Mbed TLS

---

CMakeLists.txt
CMakeLists.txt.in
src/coap_io.c

When building libcoap with mingw, I noticed that coap_session_get_ifindex() always return zero. In the code, it looks like this is always set to zero if HAVE_STRUCT_CMSGHDR is unset in line: https://github.com/obgm/libcoap/blob/7d5e5f3b8c31f7af60b697659f9a97de7db9a3cc/src/coap_io.c#L1165
Wouldn't -1 be a better value to indicate an undefined value?
If libcoap is built for Windows without mingw, HAVE_STRUCT_CMSGHDR is always defined. In this PR, I removed the special handling of mingw, added a few aliases and the code seems to work with HAVE_STRUCT_CMSGHDR defined and mingw.

enable HAVE_STRUCT_CMSGHDR when building with mingw

---

include/coap3/coap_block_internal.h
src/coap_block.c

This prevents premature de-allocation of the lg_crcv when large files are getting uploaded.

block handling: Update lg_crcv->last_used when sending Block1

---

examples/coap-client.c
examples/coap-server.c
include/coap3/coap_dtls.h
man/coap-client.txt.in
man/coap-server.txt.in
man/coap_encryption.txt.in
src/coap_gnutls.c
src/coap_mbedtls.c
src/coap_openssl.c
src/coap_tinydtls.c
src/coap_wolfssl.c

Currently only supported by Mbed TLS if the optional MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED is defined for the Mbed TLS library build.

TLS: EC-JPAKE support (RFC8236)

---

include/coap3/coap_net_internal.h
include/coap3/coap_threadsafe_internal.h
man/coap_locking.txt.in
src/coap_net.c
src/coap_session.c
src/coap_threadsafe.c

When context is de-allocated, other threads can still access the context lock held within context. Indicating being freed when coap_free_context() was called worked in most cases, but not all.

Locking: Use single global lock instead of context lock

---

examples/lwip/client-coap.c
examples/lwip/client.c
examples/lwip/config/lwipopts.h
include/coap3/coap_io_internal.h
src/coap_io_lwip.c
src/coap_net.c

Do not call coap_free_context() from within sigint handler. Always call coap_io_process().
Use sys_arch_sem_wait() for timeouts while waiting for input.

client-coap.c: Fix client spin loop for NO_SYS == 0

---

include/coap3/coap_mutex_internal.h
src/coap_debug.c
src/coap_mbedtls.c
src/coap_net.c
src/coap_subscribe.c

If a proxy reads in a packet via coap_read_endpoint, which then invokes an ongoing proxy TCP connection, while waiting for the CSM response of the new session, coap_read_endpoint would get invoked again if there is any data to read on any of the listening endpoints..
With a Constrained Stack, the read in data is protected by mutex m_read_enpoint - which is still locked when trying to wait for the CSM.
As the code is either single threaded, or protected by global_lock if multi-threaded, there is no need to maintain mutexes such as m_read_endpoint.  This PR removes these not needed mutexes.

Constrained Stack: No need for individual locks

---

configure.ac

PKG_CHECK_MODULES_STATIC is only supported by pkg-config > 0.29
Use pkg-config --static instead.

configure.ac: Not all pkg-config support PKG_CHECK_MODULES_STATIC

---

examples/coap-client.c
include/coap3/coap_dtls.h
include/coap3/coap_dtls_internal.h
include/coap3/coap_net.h
include/coap3/coap_session_internal.h
libcoap-3.map
libcoap-3.sym
man/coap_context.txt.in
src/coap_debug.c
src/coap_gnutls.c
src/coap_io.c
src/coap_mbedtls.c
src/coap_net.c
src/coap_notls.c
src/coap_openssl.c
src/coap_session.c
src/coap_tinydtls.c
src/coap_wolfssl.c

Only support changing the client's source port if the DTLS library has support / configured for CID.
Used when debugging server handling source address changes and CID is in use.
Add in support for TinyDTLS (Client only) if TinyDTLS is patched appropriately.

Connection-ID: Only change source port when CID has been negotiated

---

src/coap_proxy.c

Adds a cast to int in order to avoid a compilation error on an embedded target.

coap_proxy.c: Fix error "'.*' expects argument of type 'int'"

---

src/coap_address.c

`addr_ip` was declared as a pointer, but sometimes not used in this manner.

Contiki-NG: Fix coap_resolve_address_info

---

include/coap3/coap_ws_internal.h
src/coap_ws.c

The pull request as discussed in #1503.

websockets: accept longer header lines and specific header sent by firefox browser

---

src/coap_session.c

Server enabled for mcast receipt.  When the server is acting as a proxy sends a mcast packet out over a slave client type socket, it receives the mcast packet on the server socket (which could then be forward out of the client socket....).
This change prevents the server socket from passing up the libcoap stack a mcast packet that it knows the client socket is sending.

mcast_loop: Drop mcast packet that server sent on different socket

---

man/coap_logging.txt.in

Fixes small typo in logging documentation.

man: fix typo in logging documentation
